chore(io-stress): Add node level disk io stress experiment
litmuschaos/litmus-go pull request #117
Opened 2020-09-12 10:16 UTC by uditgaurav

Signed-off-by: Udit Gaurav <udit.gaurav@mayadata.io>

2020-09-12 10:24 UTC, uditgaurav commented
#### Logs of the experiment:

```
INFO[2020-09-12T15:51:52+05:30] [PreReq]: Getting the ENV for the  experiment 
INFO[2020-09-12T15:51:52+05:30] [PreReq]: Updating the chaos result of node-io-stress experiment (SOT) 
INFO[2020-09-12T15:51:55+05:30] The application information is as follows     Namespace=default Label="run=nginx" Chaos Duration=60 Ramp Time=0 Number of Workers=4 IO Stress Percentage=90
INFO[2020-09-12T15:51:55+05:30] [Status]: Verify that the AUT (Application Under Test) is running (pre-chaos) 
INFO[2020-09-12T15:51:55+05:30] [Status]: Checking whether application containers are in running state 
INFO[2020-09-12T15:51:56+05:30] The running status of container are as follows  Status=Running container=nginx Pod=nginx-7bb6f8885-fbfpj
INFO[2020-09-12T15:51:58+05:30] [Status]: Checking whether application pods are in running state 
INFO[2020-09-12T15:51:58+05:30] The running status of Pods are as follows     Status=Running Pod=nginx-7bb6f8885-fbfpj
INFO[2020-09-12T15:52:00+05:30] [Info]: Details of application under chaos injection  IO Stress Percentage=90 Number of workers=4 NodeName=ip-172-31-24-159.us-east-2.compute.internal
INFO[2020-09-12T15:52:00+05:30] [Status]: Checking the status of the helper pod 
INFO[2020-09-12T15:52:00+05:30] [Status]: Checking whether application containers are in running state 
INFO[2020-09-12T15:52:05+05:30] The running status of container are as follows  container=node-io-stress Pod=node-io-stress-wnokum Status=Running
INFO[2020-09-12T15:52:07+05:30] [Status]: Checking whether application pods are in running state 
INFO[2020-09-12T15:52:08+05:30] The running status of Pods are as follows     Status=Running Pod=node-io-stress-wnokum
INFO[2020-09-12T15:52:10+05:30] [Wait]: Waiting for 90s till the completion of the helper pod 
INFO[2020-09-12T15:52:10+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:11+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:12+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:14+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:15+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:16+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:18+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:19+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:20+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:22+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:23+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:25+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:26+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:27+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:29+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:30+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:31+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:33+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:34+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:35+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:37+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:38+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:39+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:41+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:42+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:43+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:45+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:46+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:47+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:48+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:50+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:51+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:52+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:54+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:55+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:56+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:58+05:30] helper pod status: Running                   
INFO[2020-09-12T15:52:59+05:30] helper pod status: Running                   
INFO[2020-09-12T15:53:01+05:30] helper pod status: Running                   
INFO[2020-09-12T15:53:02+05:30] helper pod status: Running                   
INFO[2020-09-12T15:53:03+05:30] helper pod status: Running                   
INFO[2020-09-12T15:53:05+05:30] helper pod status: Succeeded                 
INFO[2020-09-12T15:53:05+05:30] The running status of Pods are as follows     Pod=node-io-stress-wnokum Status=Succeeded
INFO[2020-09-12T15:53:06+05:30] [Status]: Getting the status of application node 
INFO[2020-09-12T15:53:06+05:30] The running status of Nodes are as follows    Node=ip-172-31-24-159.us-east-2.compute.internal Ready=true
INFO[2020-09-12T15:53:06+05:30] [Cleanup]: Deleting the helper pod           
INFO[2020-09-12T15:53:09+05:30] [Confirmation]: Disk in the application node has been stressed successfully 
INFO[2020-09-12T15:53:09+05:30] [Status]: Verify that the AUT (Application Under Test) is running (post-chaos) 
INFO[2020-09-12T15:53:09+05:30] [Status]: Checking whether application containers are in running state 
INFO[2020-09-12T15:53:10+05:30] The running status of container are as follows  container=nginx Pod=nginx-7bb6f8885-fbfpj Status=Running
INFO[2020-09-12T15:53:12+05:30] [Status]: Checking whether application pods are in running state 
INFO[2020-09-12T15:53:12+05:30] The running status of Pods are as follows     Status=Running Pod=nginx-7bb6f8885-fbfpj
INFO[2020-09-12T15:53:14+05:30] [The End]: Updating the chaos result of node-io-stress experiment (EOT) 
```

2020-09-12 10:25 UTC, uditgaurav commented
#### Chaos Result

```
Name:         node-io-stress
Namespace:    default
Labels:       name=node-io-stress
Annotations:  <none>
API Version:  litmuschaos.io/v1alpha1
Kind:         ChaosResult
Metadata:
  Creation Timestamp:  2020-09-12T10:21:54Z
  Generation:          2
  Resource Version:    17246532
  Self Link:           /apis/litmuschaos.io/v1alpha1/namespaces/default/chaosresults/node-io-stress
  UID:                 364da593-b4b5-4a39-a364-d2ecf1011718
Spec:
  Experiment:  node-io-stress
Status:
  Experimentstatus:
    Fail Step:  N/A
    Phase:      Completed
    Verdict:    Pass
Events:
  Type    Reason   Age    From  Message
  ----    ------   ----   ----  -------
  Normal  Awaited  3m37s        experiment: node-io-stress, Result: Awaited
  Normal  Pass     2m17s        experiment: node-io-stress, Result: Pass
```

2020-09-12 11:20 UTC, ksatchit commented on experiments/generic/node-io-stress/README.md
> +<td> This experiment causes a disk resource exhaustion on the Kubernetes node. The experiment aims to verify resiliency of applications whose replicas may be evicted on account on nodes turning unsch
```suggestion
<td> This experiment causes disk stress on the Kubernetes node. The experiment aims to verify the resiliency of applications that share this disk resource for ephemeral or persistent storage purposes. </td>
```

2020-09-12 11:24 UTC, ksatchit commented on chaoslib/litmus/node-io-stress/lib/node-io-stress.go
> +						"--io",
Let us take the disk device as a user-param. If unspecified, we can allow stress-ng to pick defaults

2020-09-12 11:26 UTC, ksatchit commented on chaoslib/litmus/node-io-stress/lib/node-io-stress.go
> +						strconv.Itoa(experimentsDetails.IOStressPercentage) + "%",
This needs to be represented by a different param name in the ENV & types. 

```golang
ENV experimentDetails.IOStressPercentage, _ = strconv.Atoi(Getenv("IO_STRESS_PERCENTAGE", "90"))
```

2020-09-12 13:08 UTC, ksatchit commented on pkg/generic/node-io-stress/environment/environment.go
> +	experimentDetails.IOStressPercentage, _ = strconv.Atoi(Getenv("IO_STRESS_PERCENTAGE", "90"))
FilesystemUtilizationPercentage

2020-09-12 13:49 UTC, uditgaurav commented
## Stress-ng Metrics at Different values

```
root@gke-cluster-1-default-pool-b94c2161-x1hm:~# stress-ng --io 1 --hdd 4 --hdd-bytes 10G -t 900s --metrics --yaml out.yaml                                         
stress-ng: info:  [103315] dispatching hogs: 1 io, 4 hdd
stress-ng: info:  [103315] successful run completed in 902.50s (15 mins, 2.50 secs)
stress-ng: info:  [103315] stressor       bogo ops real time  usr time  sys time   bogo ops/s   bogo ops/s
stress-ng: info:  [103315]                           (secs)    (secs)    (secs)   (real time) (usr+sys time)
stress-ng: info:  [103315] io                    2    902.50      0.00      0.09         0.00        22.22
stress-ng: info:  [103315] hdd              171342    902.32      0.41     17.99       189.89      9312.07
```
```
root@gke-cluster-1-default-pool-b94c2161-x1hm:~# stress-ng --io 1 --hdd 8 --hdd-bytes 10G -t 1000s --metrics --yaml out.yaml
stress-ng: info:  [111992] dispatching hogs: 1 io, 8 hdd
stress-ng: info:  [111992] successful run completed in 1002.25s (16 mins, 42.25 secs)
stress-ng: info:  [111992] stressor       bogo ops real time  usr time  sys time   bogo ops/s   bogo ops/s
stress-ng: info:  [111992]                           (secs)    (secs)    (secs)   (real time) (usr+sys time)
stress-ng: info:  [111992] io                    2   1002.25      0.01      0.00         0.00       200.00
stress-ng: info:  [111992] hdd              188794   1001.71      0.40     18.34       188.47     10074.39
```
```
root@gke-cluster-1-default-pool-b94c2161-x1hm:~# stress-ng --io 8 --hdd 8 --hdd-bytes 10G -t 1000s --metrics --yaml out.yaml
stress-ng: info:  [121588] dispatching hogs: 8 io, 8 hdd
stress-ng: info:  [121588] successful run completed in 1002.26s (16 mins, 42.26 secs)
stress-ng: info:  [121588] stressor       bogo ops real time  usr time  sys time   bogo ops/s   bogo ops/s
stress-ng: info:  [121588]                           (secs)    (secs)    (secs)   (real time) (usr+sys time)
stress-ng: info:  [121588] io                    8   1002.24      0.00      0.00         0.01         0.00
stress-ng: info:  [121588] hdd              191972   1001.45      0.70     18.77       191.69      9859.89
```
```
root@gke-cluster-1-default-pool-b94c2161-x1hm:~# stress-ng --io 8 --hdd 8 --hdd-bytes 11% -t 1000s --metrics --yaml out.yaml
stress-ng: info:  [130261] dispatching hogs: 8 io, 8 hdd
stress-ng: info:  [130261] successful run completed in 1006.49s (16 mins, 46.49 secs)
stress-ng: info:  [130261] stressor       bogo ops real time  usr time  sys time   bogo ops/s   bogo ops/s
stress-ng: info:  [130261]                           (secs)    (secs)    (secs)   (real time) (usr+sys time)
stress-ng: info:  [130261] io                    8   1006.48      0.00      0.00         0.01         0.00
stress-ng: info:  [130261] hdd              191714   1003.92      0.45     20.03       190.97      9361.04
```

2020-09-12 13:58 UTC, ksatchit commented on chaoslib/litmus/node-io-stress/lib/node-io-stress.go
> +						"--io",
Just realized stress-ng flags don't include disk names!

2020-09-12 14:04 UTC, ksatchit commented on chaoslib/litmus/node-io-stress/lib/node-io-stress.go
> +		"Filesy-System-Utilization-Percentage": experimentsDetails.FilesystemUtilizationPercentage,
```suggestion
		"FilesSystemUtilizationPercentage": experimentsDetails.FilesystemUtilizationPercentage,
```

2020-09-12 14:05 UTC, ksatchit commented on chaoslib/litmus/node-io-stress/lib/node-io-stress.go
> +		"Number-of-workers":                    experimentsDetails.NumberOfWorkers,
NumberOfWorkers

2020-09-12 14:05 UTC, ksatchit commented on experiments/generic/node-io-stress/node-io-stress.go
> +		"File-System-Utilization-Percentage": experimentsDetails.FilesystemUtilizationPercentage,
same as earlier wrt names

2020-09-12 14:06 UTC, ksatchit commented on pkg/generic/node-io-stress/environment/environment.go
> +	experimentDetails.FilesystemUtilizationPercentage, _ = strconv.Atoi(Getenv("FILES_SYSTEM_UTILIZATIONPERCENTAGE", "90"))
```suggestion
	experimentDetails.FilesystemUtilizationPercentage, _ = strconv.Atoi(Getenv("FILESYSTEM_UTILIZATION_PERCENTAGE", "90"))
```

2020-09-12 14:49 UTC, uditgaurav commented
Latest Logs: 
```
INFO[2020-09-12T20:16:11+05:30] [PreReq]: Getting the ENV for the  experiment 
INFO[2020-09-12T20:16:11+05:30] [PreReq]: Updating the chaos result of node-io-stress experiment (SOT) 
INFO[2020-09-12T20:16:14+05:30] The application information is as follows     Ramp Time=0 NumberOfWorkers=4 FilesystemUtilizationPercentage=10 Namespace=default Label= Chaos Duration=120
INFO[2020-09-12T20:16:14+05:30] [Status]: Verify that the AUT (Application Under Test) is running (pre-chaos) 
INFO[2020-09-12T20:16:14+05:30] [Status]: Checking whether application containers are in running state 
INFO[2020-09-12T20:16:14+05:30] The running status of container are as follows  container=nginx Pod=nginx-7bb6f8885-v9r6q Status=Running
INFO[2020-09-12T20:16:16+05:30] [Status]: Checking whether application pods are in running state 
INFO[2020-09-12T20:16:16+05:30] The running status of Pods are as follows     Status=Running Pod=nginx-7bb6f8885-v9r6q
INFO[2020-09-12T20:16:19+05:30] [Info]: Details of application under chaos injection  NodeName=ip-172-31-24-159.us-east-2.compute.internal FilesystemUtilizationPercentage=10 NumberOfWorkers=4
INFO[2020-09-12T20:16:19+05:30] [Status]: Checking the status of the helper pod 
INFO[2020-09-12T20:16:19+05:30] [Status]: Checking whether application containers are in running state 
INFO[2020-09-12T20:16:21+05:30] The running status of container are as follows  Pod=node-io-stress-vlpwta Status=Running container=node-io-stress
INFO[2020-09-12T20:16:23+05:30] [Status]: Checking whether application pods are in running state 
INFO[2020-09-12T20:16:24+05:30] The running status of Pods are as follows     Pod=node-io-stress-vlpwta Status=Running
INFO[2020-09-12T20:16:26+05:30] [Wait]: Waiting for 150s till the completion of the helper pod 
INFO[2020-09-12T20:16:26+05:30] helper pod status: Running                   
INFO[2020-09-12T20:16:27+05:30] helper pod status: Running                   
INFO[2020-09-12T20:16:28+05:30] helper pod status: Running                   
INFO[2020-09-12T20:16:30+05:30] helper pod status: Running                   
INFO[2020-09-12T20:16:31+05:30] helper pod status: Running                   
INFO[2020-09-12T20:16:32+05:30] helper pod status: Running                   
INFO[2020-09-12T20:16:34+05:30] helper pod status: Running                   
INFO[2020-09-12T20:16:35+05:30] helper pod status: Running                   
INFO[2020-09-12T20:16:36+05:30] helper pod status: Running                   
INFO[2020-09-12T20:16:37+05:30] helper pod status: Running                   
INFO[2020-09-12T20:16:39+05:30] helper pod status: Running                   
INFO[2020-09-12T20:16:40+05:30] helper pod status: Running                   
INFO[2020-09-12T20:16:41+05:30] helper pod status: Running                   
INFO[2020-09-12T20:16:42+05:30] helper pod status: Running                   
INFO[2020-09-12T20:16:44+05:30] helper pod status: Running                   
INFO[2020-09-12T20:16:45+05:30] helper pod status: Running                   
INFO[2020-09-12T20:16:46+05:30] helper pod status: Running                   
INFO[2020-09-12T20:16:48+05:30] helper pod status: Running                   
INFO[2020-09-12T20:16:49+05:30] helper pod status: Running                   
INFO[2020-09-12T20:16:50+05:30] helper pod status: Running                   
INFO[2020-09-12T20:16:51+05:30] helper pod status: Running                   
INFO[2020-09-12T20:16:53+05:30] helper pod status: Running                   
INFO[2020-09-12T20:16:54+05:30] helper pod status: Running                   
INFO[2020-09-12T20:16:55+05:30] helper pod status: Running                   
INFO[2020-09-12T20:16:56+05:30] helper pod status: Running                   
INFO[2020-09-12T20:16:58+05:30] helper pod status: Running                   
INFO[2020-09-12T20:16:59+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:00+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:02+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:03+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:04+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:05+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:07+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:08+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:09+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:10+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:12+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:13+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:14+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:16+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:17+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:18+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:19+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:21+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:22+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:23+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:24+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:26+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:27+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:28+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:30+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:31+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:32+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:33+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:35+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:36+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:37+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:38+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:40+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:41+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:42+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:43+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:45+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:46+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:47+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:49+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:50+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:51+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:52+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:54+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:55+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:56+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:57+05:30] helper pod status: Running                   
INFO[2020-09-12T20:17:59+05:30] helper pod status: Running                   
INFO[2020-09-12T20:18:00+05:30] helper pod status: Running                   
INFO[2020-09-12T20:18:01+05:30] helper pod status: Running                   
INFO[2020-09-12T20:18:03+05:30] helper pod status: Running                   
INFO[2020-09-12T20:18:04+05:30] helper pod status: Running                   
INFO[2020-09-12T20:18:05+05:30] helper pod status: Running                   
INFO[2020-09-12T20:18:06+05:30] helper pod st [...]

2020-09-12 18:10 UTC, ksatchit commented on chaoslib/litmus/node-io-stress/lib/node-io-stress.go
> +		hddbytes = strconv.Itoa(experimentsDetails.FilesystemUtilizationBytes) + "G"
Do we want to check against "0" alone?

2020-09-12 18:10 UTC, ksatchit commented on pkg/generic/node-io-stress/environment/environment.go
> +	experimentDetails.FilesystemUtilizationPercentage, _ = strconv.Atoi(Getenv("FILESSYSTEM_UTILIZATION_PERCENTAGE", ""))
Should this have a default?

2020-09-12 18:20 UTC, uditgaurav commented on pkg/generic/node-io-stress/environment/environment.go
> +	experimentDetails.FilesystemUtilizationPercentage, _ = strconv.Atoi(Getenv("FILESSYSTEM_UTILIZATION_PERCENTAGE", ""))
No, We can pass the default value from experiment. If we define default value here then [ this check ](https://github.com/litmuschaos/litmus-go/blob/1ea5e0b8572b724b6bf85e250c3bdcd911e695bd/chaoslib/litmus/node-io-stress/lib/node-io-stress.go#L141) will get impacted.

2020-09-12 18:28 UTC, uditgaurav commented on chaoslib/litmus/node-io-stress/lib/node-io-stress.go
> +		hddbytes = strconv.Itoa(experimentsDetails.FilesystemUtilizationBytes) + "G"
Empty value in int so checked it with 0.

Example: Helper pod yaml which makes a decision according to the above condition:
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  creationTimestamp: "2020-09-12T18:24:56Z"
  labels:
    app: node-io-stress
    chaosUID: ""
    name: node-io-stress-muqozk
  name: node-io-stress-muqozk
  namespace: default
  resourceVersion: "17295404"
  selfLink: /api/v1/namespaces/default/pods/node-io-stress-muqozk
  uid: e7775804-a4f4-4284-bec8-bfc14eaef6ec
spec:
  containers:
  - args:
    - --io
    - "4"
    - --hdd
    - "4"
    - --hdd-bytes
    - 10G
    - --timeout
    - 120s
    command:
    - /stress-ng
    image: litmuschaos/go-runner:latest
    imagePullPolicy: Always
```

2020-09-12 18:36 UTC, ispeakc0de commented on pkg/generic/node-io-stress/environment/environment.go
> +	experimentDetails.FilesystemUtilizationPercentage, _ = strconv.Atoi(Getenv("FILESSYSTEM_UTILIZATION_PERCENTAGE", ""))
We can convert those if-else condition to:

```
if experimentsDetails.FilesystemUtilizationPercentage != 0 && experimentsDetails.FilesystemUtilizationBytes != 0 {
		hddbytes = strconv.Itoa(experimentsDetails.FilesystemUtilizationPercentage) + "%"
	} else{
hddbytes = strconv.Itoa(experimentsDetails.FilesystemUtilizationBytes) + "G"
}
```
and provide the default value for `FilesystemUtilizationBytes`

2020-09-12 18:47 UTC, ispeakc0de requested changes

2020-09-12 18:47 UTC, ispeakc0de commented on pkg/generic/node-io-stress/environment/environment.go
> +	experimentDetails.AuxiliaryAppInfo = Getenv("AUXILIARY_APPINFO", "")
can we add the auxiliary application status check in the this[experiments/generic/node-io-stress/node-io-stress.go] file

2020-09-12 18:47 UTC, ispeakc0de commented on pkg/generic/node-io-stress/types/types.go
> +	MemoryPercentage                int
Is this needed?

2020-09-12 18:52 UTC, uditgaurav commented on pkg/generic/node-io-stress/environment/environment.go
> +	experimentDetails.FilesystemUtilizationPercentage, _ = strconv.Atoi(Getenv("FILESSYSTEM_UTILIZATION_PERCENTAGE", ""))
We also want to give warning in a case where both values are given

2020-09-12 18:57 UTC, uditgaurav commented on pkg/generic/node-io-stress/environment/environment.go
> +	experimentDetails.AuxiliaryAppInfo = Getenv("AUXILIARY_APPINFO", "")
Added

2020-09-12 19:07 UTC, ispeakc0de commented on pkg/generic/node-io-stress/environment/environment.go
> +	experimentDetails.FilesystemUtilizationPercentage, _ = strconv.Atoi(Getenv("FILESSYSTEM_UTILIZATION_PERCENTAGE", ""))
`FILESSYSTEM_UTILIZATION_PERCENTAGE`  -> `FILESYSTEM_UTILIZATION_PERCENTAGE`

2020-09-12 19:10 UTC, ispeakc0de commented on pkg/generic/node-io-stress/environment/environment.go
> +	experimentDetails.FilesystemUtilizationPercentage, _ = strconv.Atoi(Getenv("FILESSYSTEM_UTILIZATION_PERCENTAGE", ""))
I think it's okay if he provides both values. we will use based on priority order and mention the same in the docs. `Warning` for only an extra variable can mislead. WDYT?

2020-09-12 19:21 UTC, uditgaurav commented on pkg/generic/node-io-stress/environment/environment.go
> +	experimentDetails.FilesystemUtilizationPercentage, _ = strconv.Atoi(Getenv("FILESSYSTEM_UTILIZATION_PERCENTAGE", ""))
okay, then we can use it!

2020-09-13 09:27 UTC, ksatchit commented on chaoslib/litmus/node-io-stress/lib/node-io-stress.go
> +	if experimentsDetails.FilesystemUtilizationPercentage != 0 {
Ref: https://github.com/litmuschaos/litmus-go/pull/118/files#r487504619

2020-09-13 09:30 UTC, ksatchit commented on experiments/generic/node-io-stress/node-io-stress.go
> +		"FilesystemUtilizationPercentage": experimentsDetails.FilesystemUtilizationPercentage,
Lets add both percentage and bytes for context

2020-09-13 09:31 UTC, ksatchit commented on pkg/generic/node-io-stress/environment/environment.go
> +	experimentDetails.FilesystemUtilizationBytes, _ = strconv.Atoi(Getenv("FILESSYSTEM_UTILIZATION_BYTES", "10"))
```suggestion
	experimentDetails.FilesystemUtilizationBytes, _ = strconv.Atoi(Getenv("FILESYSTEM_UTILIZATION_BYTES", "10"))
```

2020-09-13 09:32 UTC, ksatchit commented on pkg/generic/node-io-stress/environment/environment.go
> +	experimentDetails.FilesystemUtilizationBytes, _ = strconv.Atoi(Getenv("FILESSYSTEM_UTILIZATION_BYTES", "10"))
We shouldn't be using defaults for the bytes

2020-09-13 09:41 UTC, uditgaurav commented
Latest Logs:

```bash
INFO[2020-09-13T15:08:36+05:30] [PreReq]: Getting the ENV for the  experiment 
INFO[2020-09-13T15:08:36+05:30] [PreReq]: Updating the chaos result of node-io-stress experiment (SOT) 
INFO[2020-09-13T15:08:39+05:30] The application information is as follows     NumberOfWorkers=4 FilesystemUtilizationPercentage=0 FilesystemUtilizationBytes=0 Namespace=default Label="run=nginx" Chaos Duration=120 Ramp Time=0
INFO[2020-09-13T15:08:39+05:30] [Status]: Verify that the AUT (Application Under Test) is running (pre-chaos) 
INFO[2020-09-13T15:08:39+05:30] [Status]: Checking whether application containers are in running state 
INFO[2020-09-13T15:08:39+05:30] The running status of container are as follows  Status=Running container=nginx Pod=nginx-7bb6f8885-v9r6q
INFO[2020-09-13T15:08:41+05:30] [Status]: Checking whether application pods are in running state 
INFO[2020-09-13T15:08:41+05:30] The running status of Pods are as follows     Pod=nginx-7bb6f8885-v9r6q Status=Running
INFO[2020-09-13T15:08:44+05:30] [Info]: Details of application under chaos injection  FilesystemUtilizationPercentage=0 NumberOfWorkers=4 NodeName=ip-172-31-24-159.us-east-2.compute.internal
INFO[2020-09-13T15:08:44+05:30] Neither of FilesystemUtilizationPercentage or FilesystemUtilizationBytes provided, proceeding with a default FilesystemUtilizationPercentage value of 10%!(NOVERB) 
INFO[2020-09-13T15:08:44+05:30] [Status]: Checking the status of the helper pod 
INFO[2020-09-13T15:08:44+05:30] [Status]: Checking whether application containers are in running state 
INFO[2020-09-13T15:08:47+05:30] The running status of container are as follows  container=node-io-stress Pod=node-io-stress-uhfxpw Status=Running
INFO[2020-09-13T15:08:49+05:30] [Status]: Checking whether application pods are in running state 
INFO[2020-09-13T15:08:49+05:30] The running status of Pods are as follows     Pod=node-io-stress-uhfxpw Status=Running
INFO[2020-09-13T15:08:51+05:30] [Wait]: Waiting for 150s till the completion of the helper pod 
INFO[2020-09-13T15:08:51+05:30] helper pod status: Running                   
INFO[2020-09-13T15:08:52+05:30] helper pod status: Running                   
INFO[2020-09-13T15:08:54+05:30] helper pod status: Running                   
INFO[2020-09-13T15:08:55+05:30] helper pod status: Running                   
INFO[2020-09-13T15:08:56+05:30] helper pod status: Running                   
INFO[2020-09-13T15:08:57+05:30] helper pod status: Running                   
INFO[2020-09-13T15:08:59+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:00+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:01+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:03+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:04+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:05+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:06+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:08+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:09+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:10+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:12+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:13+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:14+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:15+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:17+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:18+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:19+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:20+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:22+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:23+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:25+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:27+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:28+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:29+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:30+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:32+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:33+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:34+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:35+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:37+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:38+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:39+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:41+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:42+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:43+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:45+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:46+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:47+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:49+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:50+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:51+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:52+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:54+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:55+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:56+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:58+05:30] helper pod status: Running                   
INFO[2020-09-13T15:09:59+05:30] helper pod status: Running                   
INFO[2020-09-13T15:10:00+05:30] helper pod status: Running                   
INFO[2020-09-13T15:10:01+05:30] helper pod status: Running                   
INFO[2020-09-13T15:10:03+05:30] helper pod status: Running                   
INFO[2020-09-13T15:10:04+05:30] helper pod status: Running                   
INFO[2020-09-13T15:10:05+05:30] helper pod status: Running                   
INFO[2020-09-13T15:10:06+05:30] helper pod status: Running                   
INFO[2020-09-13T15:10:08+05:30] helper pod status: Running                   
INFO[2020-09-13T15:10:09+05:30] helper pod status: Running                   
INFO[2020-09-13T15:10:10+05:30] helper pod status: Running                   
INFO[2020-09-13T15:10:11+05:30] helper pod status: Running                   
INFO[2020-09-13T15:10:13+05:30] helper pod status: Running                   
INFO[2020-09-13T15:10:14+05:30] helper pod status: Running                   
INFO[2020-09-13T15:10:15+05:30] helper pod status: Running                   
INFO[2020-09-13T15:10:17+05:30] helper pod status: Running                   
INFO[2020-09-13T15:10:18+05:30] helper pod status: Running                   
INFO[2020-09-13T15:10:19+05:30] helper pod status: Running                   
INFO[2020-09-13T15:10:20+05:30] helper pod status: Running                   
INFO[2020-09-13T15:10:22+05:30] helper pod status: Running                   
INFO[2020-09-13T15:10:23+05:30] helper pod status: Running                   
INFO[2020-09-13T15:10:24+05:30] helper pod status: Running                   
INFO[2020-09-13T15:10:26+05:30] helper pod status: Running                   
INFO[2020-09-13T15:10:27+05:30] helper pod status: Running                   
INFO[2020-09-13T15:10:28+05:30] helper pod status: Running                   
INFO[2020-09-13T15:10:29+05:30] helper po [...]

2020-09-13 11:14 UTC, ispeakc0de approved these changes

2020-09-13 11:16 UTC, ksatchit approved these changes

2020-09-13 11:17 UTC, merged