chore(experiment): Add pod level disk io stress chaos experiment
litmuschaos/litmus-go pull request #118
Opened 2020-09-12 15:49 UTC by uditgaurav

2020-09-12 18:10 UTC, uditgaurav commented
Logs:

- [pod_io_stress.txt](https://github.com/litmuschaos/litmus-go/files/5213073/pod_io_stress.txt)

2020-09-12 18:18 UTC, ksatchit commented on chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
> +func WaitForChaosComplition(appNs string, appLabel string, clients clients.ClientSets, duration int, containerName string) (string, error) {
```suggestion
func WaitForChaosCompletion(appNs string, appLabel string, clients clients.ClientSets, duration int, containerName string) (string, error) {
```

2020-09-12 19:04 UTC, ispeakc0de requested changes

2020-09-12 19:04 UTC, ispeakc0de commented on chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
> +		"io.kubernetes.pod.name=" + experimentsDetails.TargetPod + "",
"io.kubernetes.pod.name=" + experimentsDetails.TargetPod,

2020-09-12 19:04 UTC, ispeakc0de commented on pkg/generic/pod-io-stress/environment/environment.go
> +	experimentDetails.FilesystemUtilizationPercentage, _ = strconv.Atoi(Getenv("FILESYSTEM_UTILIZATION_PERCENTAGE", "10"))
do we have to change the default values here?

2020-09-12 19:04 UTC, ispeakc0de commented on pkg/generic/pod-io-stress/types/types.go
> +	PodsAffectedPerc                int
Are we using it anywhere? We can use it actually as we are doing in other pod-level experiments.

2020-09-12 19:04 UTC, ispeakc0de commented on pkg/utils/common/common.go
> +func GetPodAndNodeName(namespace, targetPod, appLabels string, clients clients.ClientSets) (string, string, error) {
the same requirements can be fulfilled via `GetPodList`. if we want only a single pod instead of a list. We can call that function for this and extract out 1st pod & node name and return them.

2020-09-12 19:36 UTC, uditgaurav commented on chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
> +func WaitForChaosCompletion(appNs string, appLabel string, clients clients.ClientSets, duration int, containerName string) (string, error) {
Here the situation is a little different. I think `status.WaitForCompletion` checks the pod and container status to be completed but in my case, the container will not complete I need to delete the pods after the chaos duration. That's why need to create a different function. Mentioned in the comment also.

2020-09-13 05:02 UTC, ksatchit commented
Can we test scenarios where ephemeral storage limits are specified?

2020-09-13 07:33 UTC, uditgaurav commented on pkg/generic/pod-io-stress/types/types.go
> +	PodsAffectedPerc                int
it is used in `common.GetPodList`

2020-09-13 07:39 UTC, uditgaurav commented
>Can we test scenarios where ephemeral storage limits are specified?
In such a case the pod does not get evicted

**-oyaml** of pod
```yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu request for container
        nginx'
    creationTimestamp: "2020-09-13T06:52:31Z"
    generateName: nginx-5d486d6f66-
    labels:
      pod-template-hash: 5d486d6f66
      run: nginx
    name: nginx-5d486d6f66-wn75q
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: nginx-5d486d6f66
      uid: e75343a6-a9f3-4e4d-a360-be23edb721f0
    resourceVersion: "353550"
    selfLink: /api/v1/namespaces/default/pods/nginx-5d486d6f66-wn75q
    uid: 9de10a9d-7bbb-4100-9052-2c612e70b1c5
  spec:
    containers:
    - image: nginx:1.17.0
      imagePullPolicy: IfNotPresent
      name: nginx
      ports:
      - containerPort: 80
        protocol: TCP
      resources:
        limits:
          ephemeral-storage: 4Gi
        requests:
          cpu: 100m
          ephemeral-storage: 2Gi
...
```

```bash
root@nginx-5d486d6f66-wn75q:/# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          97G   20G   78G  20% /
tmpfs            64M     0   64M   0% /dev
tmpfs           995M     0  995M   0% /sys/fs/cgroup
/dev/sda1        97G   20G   78G  20% /etc/hosts
shm              64M     0   64M   0% /dev/shm
tmpfs           995M   12K  995M   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs           995M     0  995M   0% /proc/acpi
tmpfs           995M     0  995M   0% /proc/scsi
tmpfs           995M     0  995M   0% /sys/firmware
```

2020-09-13 08:50 UTC, ksatchit commented on chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
> +	experimentsDetails.TargetPod = targetPodList.Items[0].Name
Can we support podAffectPercentage, i.e., parallel chaos

2020-09-13 08:58 UTC, ksatchit commented on chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
> +						return errors.Errorf("Chaos Duration is not completed")
Does this need to be an error (this is desired behavior right ? i.e., the  helper status pod is not failed & timeDiff < duration). Can we wait and loop over returning an error. This will get propagated upwards in line.130

2020-09-13 09:10 UTC, ksatchit commented on pkg/generic/pod-io-stress/environment/environment.go
> +	experimentDetails.FilesystemUtilizationPercentage, _ = strconv.Atoi(Getenv("FILESYSTEM_UTILIZATION_PERCENTAGE", ""))
better to have defaults for this - say, 10%  - as the % is a relative entity.

2020-09-13 09:20 UTC, ksatchit commented on chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
> +	}
```golang
if experimentsDetails.FilesystemUtilizationBytes == 0 {
	if experimentsDetails.FilesystemUtilizationPercentage == 0 {
		hddbytes = //defaultOfUtilizationpercentage (you can either give here OR have a const to say: DefaultFsUtilPercentage=10)
	} else {
		hddbytes = strconv.Itoa(experimentsDetails.FilesystemUtilizationPercentage) + "%" //Util % you gave
	}
} else {
	if experimentsDetails.FilesystemUtilizationPercentage == 0 {
		hddbytes = strconv.Itoa(experimentsDetails.FilesystemUtilizationBytes) + "G" //Util bytes you gave
	} else {
		hddbytes = strconv.Itoa(experimentsDetails.FilesystemUtilizationPercentage) + "%" //Util % you gave
		logf.Warn("Both FsUtilPercentage & FsUtilBytes provided as inputs, using the FsUtilPercentage value to proceed with stress exp")
	}
}
```

2020-09-13 09:20 UTC, ksatchit commented on pkg/generic/pod-io-stress/environment/environment.go
> +	experimentDetails.FilesystemUtilizationPercentage, _ = strconv.Atoi(Getenv("FILESYSTEM_UTILIZATION_PERCENTAGE", ""))
Refer: https://github.com/litmuschaos/litmus-go/pull/118/files#r487504619

2020-09-13 09:21 UTC, ksatchit commented on pkg/generic/pod-io-stress/types/types.go
> +	FilesystemUtilizationBytes      int
can this also be grouped along w/ other stress attributes - just for readability

2020-09-13 13:48 UTC, ispeakc0de commented on chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
> +		msg := "Injecting " + experimentsDetails.ExperimentName + " chaos on " + appNodeName + " pod"
appNodeName or app pod?

2020-09-13 13:48 UTC, ispeakc0de commented on chaoslib/pumba/pod-io-stress/lib/pod-io-stress.go
> +								apiv1.Capability("SYS_ADMIN"),
do we need to type cast this?

2020-09-13 14:55 UTC, ispeakc0de approved these changes

2020-09-13 15:51 UTC, ksatchit approved these changes

2020-09-13 15:52 UTC, ispeakc0de approved these changes

2020-09-13 15:53 UTC, merged