chore(abort): Adding support for abortion in all experiments
litmuschaos/litmus-go pull request #145
Opened 2020-09-23 05:46 UTC by ispeakc0de

Signed-off-by: shubhamchaudhary <shubham.chaudhary@mayadata.io>

- Adding abort support for following experiments:

    - container-kill
    - disk-fill
    - kubelet-service-kill
    - network-chaos
    - node cpu-hog
    - node m.m hog
    - node drain
    - node taint
    - node io stress
    - pod io stress
    - pod-delete

2020-09-23 13:53 UTC, uditgaurav commented
/run-e2e-all

2020-09-23 18:28 UTC, uditgaurav requested changes

2020-09-23 18:28 UTC, uditgaurav commented on chaoslib/litmus/node-drain/lib/node-drain.go
> +			failStep := "Network Chaos injection stopped!"
Network Chaos injection?

2020-09-23 18:28 UTC, uditgaurav commented on chaoslib/litmus/node-taint/lib/node-taint.go
> +			failStep := "Network Chaos injection stopped!"
node-taint pls check at all places.

2020-09-25 07:55 UTC, ksatchit commented on experiments/generic/disk-fill/disk-fill.go
> +	go common.AbortWatcher(experimentsDetails.ExperimentName, clients, &resultDetails, &chaosDetails, &eventsDetails)
Disk fill lib needs a refactor to clean up used space before going down. Can we handle that separately

2020-09-25 08:00 UTC, ksatchit commented on experiments/generic/kubelet-service-kill/kubelet-service-kill.go
> +	go common.AbortWatcher(experimentsDetails.ExperimentName, clients, &resultDetails, &chaosDetails, &eventsDetails)
The kubelet service kill experiment uses a bash (systemctl) command to run the chaos - that *must* run to completion always. i.e., the kubelet service is recovered only after the duration of chaos completes. So, effectively it doesn't support yet.

2020-09-25 08:15 UTC, ksatchit commented on experiments/generic/container-kill/container-kill.go
> +	go common.AbortWatcher(experimentsDetails.ExperimentName, clients, &resultDetails, &chaosDetails, &eventsDetails)
Can we comment on our choice for invoking the AbortWatch here at pre-chaos over within the chaoslib in other experiments that need recovery

2020-09-25 08:36 UTC, ksatchit approved these changes

2020-09-25 08:36 UTC, uditgaurav approved these changes

2020-09-25 08:46 UTC, merged