Chore(New_Exp): Add stress chaos experiments and split out the exec stress experiment
litmuschaos/litmus-go pull request #368
Opened 2021-05-20 02:12 UTC by uditgaurav

Signed-off-by: uditgaurav <udit@chaosnative.com>

## This PR includes:

- New Stress experiments using non-exec mode: This includes the addition of a new set of stress chaos experiments using `cgroups` and `nsutil`.
- Splitting out the exec stress chaos experiment: Rename the older version of the stress experiment with the exec in suffix.
- The experiment has been tested on `docker` and `containerd` cluster runtime.

2021-05-20 20:38 UTC, uditgaurav commented
## Process on the target container
- _During Chaos Injection_

```bash
root@nginx-86c57db685-gdsng:/# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0  10648  6012 ?        Ss   19:37   0:00 nginx: master process nginx -g daemon off;
nginx       31  0.0  0.0  11052  2648 ?        S    19:37   0:00 nginx: worker process
root        34  0.0  0.0   3864  3320 pts/0    Ss   19:49   0:00 bash
root       367  0.0  0.0  50604  4244 ?        SL   20:01   0:00 stress-ng --timeout 60s --cpu 1
root       368 98.5  0.0  50604  4816 ?        R    20:01   0:31 stress-ng-cpu
root       369  0.0  0.0   7636  2720 pts/0    R+   20:01   0:00 ps aux
```

- _After Chaos Completion_

```bash
root@nginx-86c57db685-gdsng:/# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0  10648  6012 ?        Ss   19:37   0:00 nginx: master process nginx -g daemon off;
nginx       31  0.0  0.0  11052  2648 ?        S    19:37   0:00 nginx: worker process
root        34  0.0  0.0   3864  3320 pts/0    Ss   19:49   0:00 bash
root       370  0.0  0.0   7636  2756 pts/0    R+   20:02   0:00 ps aux
```

## Kubectl Top Output

```bash
Every 2.0s: kubectl top pods   
                                                     
NAME                        CPU(cores)   MEMORY(bytes)
nginx-86c57db685-gdsng      965m         31Mi
nginx-chaos-runner          3m           9Mi
pod-cpu-hog-helper-tsvmba   8m           8Mi
pod-cpu-hog-zu6qwa-26z29    2m           10Mi
```

## Helper Pod Logs
```bash
udit@ubuntu ~/g/s/g/l/litmus-go> kubectl logs -f pod-cpu-hog-helper-axyyul
W0520 20:32:00.226591   10306 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2021-05-20T20:32:00Z" level=info msg="[PreReq]: Getting the ENV variables"
time="2021-05-20T20:32:00Z" level=info msg="containerid: 30e9e141a51c"
time="2021-05-20T20:32:00Z" level=info msg="[Info]: Container ID=30e9e141a51c has process PID=4043"
time="2021-05-20T20:32:00Z" level=info msg="[Info]: Details of Stressor:" CPU Core=1 Timeout=60
time="2021-05-20T20:32:00Z" level=info msg="[Info]: starting process: pause nsutil -t 4043 -p -- stress-ng --timeout 60s --cpu 1"
time="2021-05-20T20:32:00Z" level=info msg="[Info]: Sending signal to resume the stress process"
time="2021-05-20T20:32:01Z" level=info msg="[Wait]: Waiting for chaos completion"
time="2021-05-20T20:33:01Z" level=info msg="[Info]: Chaos injection completed"
time="2021-05-20T20:33:01Z" level=info msg="[Info]: Stress process removed sucessfully"
```

## Experiment Pod Logs

```bash
udit@ubuntu ~/g/s/g/l/s/litmus-go> kubectl logs -f pod-cpu-hog-zu6qwa-26z29
W0520 20:01:15.070845       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2021-05-20T20:01:15Z" level=info msg="Experiment Name: pod-cpu-hog"
time="2021-05-20T20:01:15Z" level=info msg="[PreReq]: Getting the ENV for the  experiment"
time="2021-05-20T20:01:15Z" level=info msg="[PreReq]: Updating the chaos result of pod-cpu-hog experiment (SOT)"
time="2021-05-20T20:01:15Z" level=info msg="The application information is as follows" Ramp Time=0 Namespace=default Label="app=nginx" Chaos Duration=60
time="2021-05-20T20:01:15Z" level=info msg="[Status]: Verify that the AUT (Application Under Test) is running (pre-chaos)"
time="2021-05-20T20:01:15Z" level=info msg="[Status]: Checking whether application containers are in ready state"
time="2021-05-20T20:01:15Z" level=info msg="[Status]: The Container status are as follows" Readiness=true container=nginx Pod=nginx-86c57db685-gdsng
time="2021-05-20T20:01:17Z" level=info msg="[Status]: Checking whether application pods are in running state"
time="2021-05-20T20:01:17Z" level=info msg="[Status]: The status of Pods are as follows" Status=Running Pod=nginx-86c57db685-gdsng
time="2021-05-20T20:01:19Z" level=info msg="[Chaos]:Number of pods targeted: 1"
time="2021-05-20T20:01:19Z" level=info msg="[Info]: Target pods list for chaos, [nginx-86c57db685-gdsng]"
time="2021-05-20T20:01:19Z" level=info msg="[Info]: Details of application under chaos injection" PodName=nginx-86c57db685-gdsng NodeName=ip-192-168-66-49.us-west-2.compute.internal ContainerName=nginx
time="2021-05-20T20:01:19Z" level=info msg="[Status]: Checking the status of the helper pods"
time="2021-05-20T20:01:19Z" level=info msg="[Status]: Checking whether application containers are in ready state"
time="2021-05-20T20:01:21Z" level=info msg="[Status]: Checking whether application pods are in running state"
time="2021-05-20T20:01:23Z" level=info msg="[Status]: The status of Pods are as follows" Pod=pod-cpu-hog-helper-tsvmba Status=Running
time="2021-05-20T20:01:25Z" level=info msg="[Wait]: waiting till the completion of the helper pod"
time="2021-05-20T20:01:25Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:26Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:27Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:28Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:29Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:30Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:31Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:32Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:33Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:34Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:35Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:36Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:37Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:38Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:39Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:40Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:41Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:42Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:43Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:44Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:45Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:46Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:47Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:48Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:49Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:50Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:51Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:52Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:53Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:54Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:55Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:56Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:57Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:58Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:01:59Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:02:00Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:02:01Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:02:02Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:02:03Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:02:04Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:02:05Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:02:06Z" level=info msg="helper pod status: Running"
time="2021-05-20T20:02:07Z" level=info msg="helper pod status: Running"
time="2021-05-20T2 [...]

2021-06-11 10:24 UTC, ispeakc0de requested changes

2021-06-11 10:24 UTC, ispeakc0de commented on chaoslib/litmus/stress-chaos/helper/stress-helper.go
> +func getCgroupDestination(pid int, subsystem string) (string, error) {
can we add comment here?

2021-06-11 10:24 UTC, ispeakc0de commented on chaoslib/litmus/stress-chaos/helper/stress-helper.go
> +	mountinfoPath := fmt.Sprintf("/proc/%d/mountinfo", pid)
```suggestion
	mountInfoPath := fmt.Sprintf("/proc/%d/mountinfo", pid)
```

2021-06-11 10:24 UTC, ispeakc0de commented on chaoslib/litmus/stress-chaos/helper/stress-helper.go
> +	return "", errors.Errorf("never found desct for %v ", subsystem)
```suggestion
	return "", errors.Errorf("no destination found for %v ", subsystem)
```

2021-06-11 10:24 UTC, ispeakc0de commented on chaoslib/litmus/stress-chaos/lib/stress-chaos.go
> +		}
```suggestion
		if err := createHelperPod(experimentsDetails, clients, pod.Name, pod.Spec.NodeName, runID, labelSuffix);err != nil {
			return errors.Errorf("unable to create the helper pod, err: %v", err)
		}
```

2021-06-11 10:24 UTC, ispeakc0de commented on chaoslib/litmus/stress-chaos/lib/stress-chaos.go
> +		}
Can we use the `status.CheckHelperStatus` func here?

2021-06-11 10:24 UTC, ispeakc0de commented on chaoslib/litmus/stress-chaos/lib/stress-chaos.go
> +			return errors.Errorf("Unable to delete the helper pods, err: %v", err)
Error inside errors.Errorf() func should start with a lower case alphabet

2021-06-11 10:24 UTC, ispeakc0de commented on chaoslib/litmus/stress-chaos/lib/stress-chaos.go
> +	err := status.CheckApplicationStatus(experimentsDetails.ChaosNamespace, appLabel, experimentsDetails.Timeout, experimentsDetails.Delay, clients)
same as above

2021-06-11 10:24 UTC, ispeakc0de commented on experiments/generic/pod-cpu-hog-exec/experiment/pod-cpu-hog-exec.go
> +	case "pumba":
Do we want to add pumba lib here? as it is not an exec chaos

2021-06-11 10:24 UTC, ispeakc0de commented on experiments/generic/pod-cpu-hog-exec/rbac.yaml
> +  name: pod-cpu-hog-sa
do we want to rename the sa name also?

2021-06-11 10:24 UTC, ispeakc0de commented on experiments/generic/pod-cpu-hog/README.md
> + <td> </td>
we can some details here

2021-06-11 10:24 UTC, ispeakc0de commented on experiments/generic/pod-cpu-hog/experiment/pod-cpu-hog.go
> +		if err := litmusLIB.PrepareAndInjectStressChaos(&experimentsDetails, clients, &resultDetails, &eventsDetails, &chaosDetails); err != nil {
Is should also support pumba lib right?

2021-06-11 10:24 UTC, ispeakc0de commented on experiments/generic/pod-memory-hog-exec/experiment/pod-memory-hog-exec.go
> +	case "pumba":
same as above

2021-06-11 10:24 UTC, ispeakc0de commented on experiments/generic/pod-memory-hog/README.md
> + <td> </td>
same as above

2021-06-11 10:24 UTC, ispeakc0de commented on pkg/generic/stress-chaos/environment/environment.go
> +	experimentDetails.FilesystemUtilizationPercentage, _ = strconv.Atoi(common.Getenv("FILESYSTEM_UTILIZATION_PERCENTAGE", ""))
Can we do something similar to [this](https://github.com/litmuschaos/litmus-go/blob/d8125aef2470b140eed4870a6f59d721c49209aa/pkg/aws-ssm/aws-ssm-chaos/environment/environment.go#L43)

2021-06-11 11:51 UTC, uditgaurav commented on chaoslib/litmus/stress-chaos/helper/stress-helper.go
> +	if err = process.Signal(syscall.SIGTERM); err != nil && err.Error() != "os: process already finished" {
It does not require `string.Contains()` function, have tested it. Yes we can give constants.

2021-06-11 11:53 UTC, uditgaurav commented on chaoslib/litmus/stress-chaos/helper/stress-helper.go
> +	mountinfoPath := fmt.Sprintf("/proc/%d/mountinfo", pid)
This is fine. The file name is `mountinfoPath` inside the container.

2021-06-11 12:14 UTC, uditgaurav commented on chaoslib/litmus/stress-chaos/helper/stress-helper.go
> +	var (
No specific reason. There are multiple variables so we can keep them inside a block.

2021-06-11 12:14 UTC, uditgaurav commented on chaoslib/litmus/stress-chaos/helper/stress-helper.go
> +	for n, p := range paths {
namespace and path

2021-06-11 12:15 UTC, uditgaurav commented on chaoslib/litmus/stress-chaos/lib/stress-chaos.go
> +	err := status.CheckApplicationStatus(experimentsDetails.ChaosNamespace, appLabel, experimentsDetails.Timeout, experimentsDetails.Delay, clients)
This should be mandatory. We could add a lint to check this.

2021-06-11 13:37 UTC, ispeakc0de commented on chaoslib/litmus/stress-chaos/helper/stress-helper.go
> +	for n, p := range paths {
Can we use the full name?

2021-06-11 13:44 UTC, ispeakc0de commented on chaoslib/litmus/stress-chaos/lib/stress-chaos.go
> +	err := status.CheckApplicationStatus(experimentsDetails.ChaosNamespace, appLabel, experimentsDetails.Timeout, experimentsDetails.Delay, clients)
I mean we need to add this func `status.CheckHelperStatus` instead? not sure if go-lint can help to suggest this

2021-06-11 13:48 UTC, ispeakc0de commented on chaoslib/litmus/stress-chaos/helper/stress-helper.go
> +	if err = process.Signal(syscall.SIGTERM); err != nil && err.Error() != "os: process already finished" {
Okay we can keep inequality operator if you are confident about the exact error string

2021-06-15 14:18 UTC, ispeakc0de approved these changes

2021-06-15 14:31 UTC, ksatchit approved these changes

2021-06-15 14:31 UTC, merged