Experiment Update: Azure Instance Stop
litmuschaos/litmus-go pull request #377
Opened 2021-06-10 12:10 UTC by avaakash

**What this PR does / why we need it**:

- This will add multiple instance support for the azure instance terminate the experiment
- Added abortWatcher for chaos revert on abort signal
- This PR changes the name of the experiment to azure-instance-stop
- This PR updates the azure branch with the master branch

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Checklist:**
-   [ ] Fixes #<issue number>
-   [ ] PR messages has document related information
-   [ ] Labelled this PR & related issue with `breaking-changes` tag
-   [ ] PR messages has breaking changes related information
-   [ ] Labelled this PR & related issue with `requires-upgrade` tag
-   [ ] PR messages has upgrade related information
-   [ ] Commit has unit tests
-   [ ] Commit has integration tests
-   [ ] E2E run Required for the changes

2021-06-10 13:55 UTC, avaakash commented
## Experiment Logs

```bash
W0610 11:45:55.116723       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2021-06-10T11:45:55Z" level=info msg="Experiment Name: azure-instance-stop"
time="2021-06-10T11:45:55Z" level=info msg="[PreReq]: Getting the ENV for the  experiment"
time="2021-06-10T11:45:55Z" level=info msg="[PreReq]: Updating the chaos result of azure-instance-stop experiment (SOT)"
time="2021-06-10T11:45:55Z" level=info msg="The application information is as follows" Label= Chaos Duration=15 Ramp Time=0 Namespace=chaos
time="2021-06-10T11:45:55Z" level=info msg="[Status]: Verify that the AUT (Application Under Test) is running (pre-chaos)"
time="2021-06-10T11:45:55Z" level=info msg="[Status]: No appLabels provided, skipping the application status checks"
time="2021-06-10T11:45:55Z" level=info msg="[Info]: The instance under chaos(IUC) are: [azure-instance-delete azure-instance-stop]"
time="2021-06-10T11:45:56Z" level=info msg="[Status]: The instance azure-instance-delete state is: 'VM running'"
time="2021-06-10T11:45:56Z" level=info msg="[Status]: The instance azure-instance-stop state is: 'VM running'"
time="2021-06-10T11:45:56Z" level=info msg="[Status]: Azure instance(s) is in running state (pre-chaos)"
time="2021-06-10T11:45:56Z" level=info msg="[Info]: Target instanceName list, [azure-instance-delete azure-instance-stop]"
time="2021-06-10T11:45:56Z" level=info msg="[Chaos]: Stopping the Azure instance: azure-instance-delete"
time="2021-06-10T11:45:56Z" level=info msg="[Info]: Starting powerOff the instance"
time="2021-06-10T11:45:57Z" level=info msg="[Chaos]: Stopping the Azure instance: azure-instance-stop"
time="2021-06-10T11:45:57Z" level=info msg="[Info]: Starting powerOff the instance"
time="2021-06-10T11:45:58Z" level=info msg="[Wait]: Waiting for Azure instance 'azure-instance-delete' to get in the stopped state"
time="2021-06-10T11:45:58Z" level=info msg="[Status]: Checking Azure instance status"
time="2021-06-10T11:45:58Z" level=info msg="[Status]: The instance azure-instance-delete state is: 'VM stopping'"
time="2021-06-10T11:45:58Z" level=info msg="The instance state is VM stopping"
time="2021-06-10T11:46:01Z" level=info msg="[Status]: The instance azure-instance-delete state is: 'VM stopping'"
time="2021-06-10T11:46:01Z" level=info msg="The instance state is VM stopping"
time="2021-06-10T11:46:03Z" level=info msg="[Status]: The instance azure-instance-delete state is: 'VM stopping'"
time="2021-06-10T11:46:03Z" level=info msg="The instance state is VM stopping"
time="2021-06-10T11:46:06Z" level=info msg="[Status]: The instance azure-instance-delete state is: 'VM stopping'"
time="2021-06-10T11:46:06Z" level=info msg="The instance state is VM stopping"
time="2021-06-10T11:46:08Z" level=info msg="[Status]: The instance azure-instance-delete state is: 'VM stopped'"
time="2021-06-10T11:46:08Z" level=info msg="The instance state is VM stopped"
time="2021-06-10T11:46:10Z" level=info msg="[Wait]: Waiting for Azure instance 'azure-instance-stop' to get in the stopped state"
time="2021-06-10T11:46:10Z" level=info msg="[Status]: Checking Azure instance status"
time="2021-06-10T11:46:11Z" level=info msg="[Status]: The instance azure-instance-stop state is: 'VM stopped'"
time="2021-06-10T11:46:11Z" level=info msg="The instance state is VM stopped"
time="2021-06-10T11:46:13Z" level=info msg="[Wait]: Waiting for chaos interval of 10s"
time="2021-06-10T11:46:23Z" level=info msg="[Chaos]: Starting back the Azure instance: azure-instance-delete"
time="2021-06-10T11:46:23Z" level=info msg="[Info]: Starting back the instance to running state"
time="2021-06-10T11:46:24Z" level=info msg="[Chaos]: Starting back the Azure instance: azure-instance-stop"
time="2021-06-10T11:46:24Z" level=info msg="[Info]: Starting back the instance to running state"
time="2021-06-10T11:46:24Z" level=info msg="[Wait]: Waiting for Azure instance 'azure-instance-delete' to get in the running state"
time="2021-06-10T11:46:24Z" level=info msg="[Status]: Checking Azure instance status"
time="2021-06-10T11:46:25Z" level=info msg="[Status]: The instance azure-instance-delete state is: 'VM starting'"
time="2021-06-10T11:46:25Z" level=info msg="The instance state is VM starting"
time="2021-06-10T11:46:27Z" level=info msg="[Status]: The instance azure-instance-delete state is: 'VM running'"
time="2021-06-10T11:46:27Z" level=info msg="The instance state is VM running"
time="2021-06-10T11:46:29Z" level=info msg="[Wait]: Waiting for Azure instance 'azure-instance-stop' to get in the running state"
time="2021-06-10T11:46:29Z" level=info msg="[Status]: Checking Azure instance status"
time="2021-06-10T11:46:30Z" level=info msg="[Status]: The instance azure-instance-stop state is: 'VM starting'"
time="2021-06-10T11:46:30Z" level=info msg="The instance state is VM starting"
time="2021-06-10T11:46:33Z" level=info msg="[Status]: The instance azure-instance-stop state is: 'VM running'"
time="2021-06-10T11:46:33Z" level=info msg="The instance state is VM running"
time="2021-06-10T11:46:35Z" level=info msg="[Confirmation]: Azure instance stop chaos has been injected successfully"
time="2021-06-10T11:46:35Z" level=info msg="[Info]: The instance under chaos(IUC) are: [azure-instance-delete azure-instance-stop]"
time="2021-06-10T11:46:35Z" level=info msg="[Status]: The instance azure-instance-delete state is: 'VM running'"
time="2021-06-10T11:46:36Z" level=info msg="[Status]: The instance azure-instance-stop state is: 'VM running'"
time="2021-06-10T11:46:36Z" level=info msg="[Status]: Azure instance is in running state (post chaos)"
time="2021-06-10T11:46:36Z" level=info msg="[Status]: Verify that the AUT (Application Under Test) is running (post-chaos)"
time="2021-06-10T11:46:36Z" level=info msg="[Status]: No appLabels provided, skipping the application status checks"
time="2021-06-10T11:46:36Z" level=info msg="[The End]: Updating the chaos result of azure-instance-stop experiment (EOT)"
```

2021-06-11 11:22 UTC, ispeakc0de requested changes

2021-06-11 11:22 UTC, ispeakc0de commented on chaoslib/litmus/azure-instance-stop/lib/azure-instance-stop.go
> +		return errors.Errorf("no instance id found to terminate")
```suggestion
		return errors.Errorf("no instance name found to stop")
```

2021-06-11 11:22 UTC, ispeakc0de commented on experiments/azure/instance-stop/experiment/azure-instance-stop.go
> +// InstanceStop inject the azure instance termination chaos
```suggestion
// InstanceStop inject the azure instance stop chaos
```

2021-06-11 11:22 UTC, ispeakc0de commented on pkg/azure/instance-stop/environment/environment.go
> +func Getenv(key string, defaultValue string) string {
we can remove this definition of Getenv function and use common.Getenv instead

2021-06-11 11:22 UTC, ispeakc0de commented on pkg/cloud/azure/azure-instance-status.go
> +		return "", errors.Errorf("fail to get the instatus vm status")
Can we print the statuses data for this case when its length < 2?

2021-06-11 11:22 UTC, ispeakc0de commented on pkg/cloud/azure/azure-instance-status.go
> +	for i, instance := range *instanceDetails.Statuses {
if the index is static/fixed then do we need a loop here? can't we directly use *instanceDetails.Statuses [1].DisplayStatus?

2021-06-11 11:22 UTC, ispeakc0de commented on pkg/cloud/azure/azure-instance-status.go
> +func SetupSubsciptionID(experimentsDetails *experimentTypes.ExperimentDetails) error {
typo in subscription

2021-06-11 14:51 UTC, uditgaurav commented on chaoslib/litmus/azure-instance-stop/lib/azure-instance-stop.go
> +func PrepareAzureTerminateByID(experimentsDetails *experimentTypes.ExperimentDetails, clients clients.ClientSets, resultDetails *types.ResultDetails, eventsDetails *types.EventDetails, chaosDetails *
We haven't split the experiments based on ID and Tag, So right now only  `PrepareAzureStop` would also work. Later we can update if we split.

2021-06-11 20:49 UTC, avaakash commented on pkg/cloud/azure/azure-instance-status.go
> +	for i, instance := range *instanceDetails.Statuses {
We can do it like this `*(*instanceDetails.Statuses)[1].DisplayStatus`, and add a check for the length of `*instanceDetails.Statuses` to be more than 1 to get rid of the loop. @uditgaurav what's your opinion on this?

2021-06-11 20:59 UTC, avaakash commented on pkg/cloud/azure/azure-instance-status.go
> +		return "", errors.Errorf("fail to get the instatus vm status")
As per the code comment, the `*instanceDetails.Statuses` array has the status of the VM at [1] position, so if the length of the array is less than 2, that means the response didn't have VM status data, which might be possible rarely. 
More info: https://docs.microsoft.com/en-us/azure/virtual-machines/states-billing

2021-06-12 11:08 UTC, avaakash commented on experiments/azure/instance-stop/experiment/azure-instance-stop.go
> +		"Chaos Duration": experimentsDetails.ChaosDuration,
Have added the Instance Name and Resource Group name, any other detail that we can display that will be beneficial?

2021-06-14 10:49 UTC, uditgaurav commented on pkg/cloud/azure/azure-instance-status.go
> +	for i, instance := range *instanceDetails.Statuses {
yes we can remove the loop I guess.

2021-06-14 17:54 UTC, ispeakc0de commented on pkg/cloud/azure/azure-instance-status.go
> +		return "", errors.Errorf("fail to get the instatus vm status")
make sense but I am thinking if we can log the `statuses` then it would be helpful for the debug purpose(neg cases)

`return "", errors.Errorf("fail to get the instatus vm status")` --> `return "", errors.Errorf("fail to derive the instance status, statuses: %v", *instanceDetails.Statuses)`

2021-06-14 18:02 UTC, avaakash commented on pkg/cloud/azure/azure-instance-status.go
> +		return "", errors.Errorf("fail to get the instatus vm status")
That will just show the hex address, we can print the VM Provisioning data with `*(*instanceDetails.Statuses)[0].DisplayStatus`

2021-06-14 18:33 UTC, ispeakc0de commented on pkg/cloud/azure/azure-instance-status.go
> +		return "", errors.Errorf("fail to get the instatus vm status")
yes what if we use this ` return "", errors.Errorf("fail to derive the instance status, statuses: %v", *(*instanceDetails.Statuses))`?

2021-06-15 08:31 UTC, avaakash commented on pkg/cloud/azure/azure-instance-status.go
> +		return "", errors.Errorf("fail to get the instatus vm status")
That still won't work because `instanceDetails.Statuses` is a pointer array to [`InstanceViewStatus`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v55.2.0+incompatible/services/compute/mgmt/2017-12-01/compute#InstanceViewStatus). I am attaching outputs

`(*instanceDetails.Statuses)` - [{0xc00069c290 Info 0xc00069c2a0 <nil> 2021-06-15T08:28:42.4995679Z} {0xc00069c2f0 Info 0xc00069c310 <nil> <nil>}]
`(*instanceDetails.Statuses)[0]` - {0xc00069c290 Info 0xc00069c2a0 <nil> 2021-06-15T08:28:42.4995679Z}
`*(*instanceDetails.Statuses)[0].DisplayStatus` - Provisioning succeeded 
`*(*instanceDetails.Statuses)` - Error (Not Possible)
`*(*instanceDetails.Statuses)[0])` - Error (Not Possible)

2021-07-10 10:23 UTC, ispeakc0de approved these changes

2021-07-10 22:04 UTC, uditgaurav commented on pkg/cloud/azure/azure-operations.go
> +		return errors.Errorf("fail to stop the %v instance, err: %v", azureInstanceName, err)
```suggestion
		return errors.Errorf("fail to start the %v instance, err: %v", azureInstanceName, err)
```

2021-07-10 22:06 UTC, uditgaurav commented on pkg/cloud/azure/azure-instance-status.go
> +		return errors.Errorf("no instance found to terminate")
```suggestion
		return errors.Errorf("no instance found to stop")
```

2021-07-12 05:49 UTC, ispeakc0de approved these changes

2021-07-12 05:51 UTC, uditgaurav approved these changes

2021-07-12 13:53 UTC, ksatchit approved these changes

2021-07-12 13:53 UTC, merged