Chore(build): Build Go binary inside image
litmuschaos/litmus-go pull request #394
Opened 2021-06-29 12:37 UTC by uditgaurav

Signed-off-by: udit <udit@chaosnative.com>

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Checklist:**
-   [ ] Fixes #<issue number>
-   [ ] PR messages has document related information
-   [ ] Labelled this PR & related issue with `breaking-changes` tag
-   [ ] PR messages has breaking changes related information
-   [ ] Labelled this PR & related issue with `requires-upgrade` tag
-   [ ] PR messages has upgrade related information
-   [ ] Commit has unit tests
-   [ ] Commit has integration tests
-   [ ] E2E run Required for the changes

2021-06-29 14:47 UTC, uditgaurav commented
Can we rename the mandatory checl `lint` to `pre-check`. - @ksatchit

2021-06-29 15:43 UTC, Jonsy13 submitted a review, later dismissed

2021-07-02 11:37 UTC, Jonsy13 approved these changes

2021-07-02 11:51 UTC, ispeakc0de commented on .github/workflows/build.yml
> +  pre-checks:
Can we also remove this Dockerfile: https://github.com/litmuschaos/litmus-go/blob/master/Dockerfile

2021-07-02 12:02 UTC, ispeakc0de approved these changes

2021-07-02 12:32 UTC, rajdas98 requested changes

2021-07-02 12:32 UTC, rajdas98 commented on .github/workflows/build.yml
> +          go-version: 1.14
Can we use the latest version 1.16 and  same with other places?

2021-07-02 12:32 UTC, rajdas98 commented on .github/workflows/release.yml
> +          tags: litmuschaos/go-runner:${{ env.RELEASE_TAG }},litmuschaos/go-runner:latest
Can we move the docker repo and registry name to env so, that we can build easily in forked repo?

2021-07-02 12:32 UTC, rajdas98 commented on build/Dockerfile
> +ARG TARGETARCH
You can remove the TARGETARCH env. It will work because you already put it above

2021-07-02 16:22 UTC, uditgaurav commented on .github/workflows/build.yml
> +          go-version: 1.14
Yes, Currently we have 1.14 for other components operator and runner. That's why kept it the same will update accordingly . Anyways it should not impact.

2021-07-02 16:22 UTC, uditgaurav commented on build/Dockerfile
> +ARG TARGETARCH
This ENV is used to download the right binaries and the above one is used to build our experiment binaries. So this is required.

2021-07-02 16:22 UTC, uditgaurav commented on .github/workflows/release.yml
> +          tags: litmuschaos/go-runner:${{ env.RELEASE_TAG }},litmuschaos/go-runner:latest
We're passing the minimum variables from secret (that is credentials only) & we don't have a use case of passing the repo name and image tag from secrets now. We can add once we need this.

2021-07-02 20:15 UTC, rajdas98 commented on build/Dockerfile
> +ARG TARGETARCH
I meant `TARGETARCH`, it not required here, you already used it earlier

2021-07-05 05:43 UTC, uditgaurav commented on build/Dockerfile
> +ARG TARGETARCH
`TARGETARCH` is used at two places:
- Builder image: To build Binaries
- Our Main image: To download binaries

If we don't provide it at both places it will fail. Like If I remove it from here then it will unable to download
```dockerfile
RUN curl -L https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.16.0/crictl-v1.16.0-linux-${TARGETARCH}.tar.gz --output crictl-v1.16.0-linux-${TARGETARCH}.tar.gz && \
    tar zxvf crictl-v1.16.0-linux-${TARGETARCH}.tar.gz -C /usr/local/bin
```

2021-07-05 06:01 UTC, rajdas98 submitted a review, later dismissed

2021-07-09 07:36 UTC, rajdas98 reviewed
As discussed over slack, we will add 1.16 version of golang.

2021-07-09 07:37 UTC, rajdas98 approved these changes
LGTM

2021-07-09 07:50 UTC, Jonsy13 approved these changes

2021-07-09 08:36 UTC, ispeakc0de approved these changes

2021-07-09 12:32 UTC, merged