GCP VM Disk Loss Experiment
litmuschaos/litmus-go pull request #397
Opened 2021-07-01 09:42 UTC by neelanjan00

**Experiment Description:** GCP `vm-disk-loss` experiment causes loss of a non-boot disk volume from a GCP VM instance for the chaos duration. The tunables received from the user are `DiskVolumeNames`, `GCPProjectID`, `DiskZones`, and `DeviceNames`, and `Sequence` among the other common tunables. The experiment supports multiple disk losses per experiment. Chaos can be injected either in parallel mode or in serial mode. The experiment accepts a GCP Service Account's credentials defined as a Kubernetes Secret.

**Note:** Due to some issue with the GCP APIs, the service account needs to have editor or owner permission, and not just Compute Admin permission. An issue regarding the same will be raised in GCP Golang API Github repository.

**Unit Test Cases Covered**
1. No disk name provided
2. No device name provided
3. No disk zones provided
4. Unequal number of disks, devices, and zones
5. No GCP project ID provided
6. Incorrect disks, devices, zones, or GCP project ID provided
7. Disk not attached to any VM instance before starting the experiment

**Integration Test Cases Covered**
1. Fetching JSON credentials from Kubernetes Secret
2. Performing disk detachment from an instance 
3. Fetching disk attachment details i.e. the instance attached to a specified disk
4. Fetching disk attachment status i.e. whether the disk is attached to an instance or detached from an instance
5. Disk volume state check for verifying the correct initial state condition prior to the experiment

**Experiment Output**
The experiment was performed in parallel mode for two disk volumes namely, `test-disk` and `test-disk-1`, attached to `test-instance` and `test-instance-1` respectively, belonging to zones `us-central1-a` and `us-central1-b` respectively, and had device names `test-disk` and `test-disk-1` respectively.

**Logs:**
```
INFO[2021-07-01T15:05:15+05:30] Experiment Name: vm-disk-loss                
INFO[2021-07-01T15:05:15+05:30] [PreReq]: Getting the ENV for the  experiment 
INFO[2021-07-01T15:05:15+05:30] [PreReq]: Updating the chaos result of  experiment (SOT) 
INFO[2021-07-01T15:05:15+05:30] The application information is as follows     App Namespace= AppLabel= Ramp Time=0
INFO[2021-07-01T15:05:15+05:30] The volume information is as follows          Volume IDs="test-disk,test-disk-1" Zones="us-central1-a,us-central1-b" Ramp Time=0
INFO[2021-07-01T15:05:15+05:30] [Status]: Verify that the AUT (Application Under Test) is running (pre-chaos) 
INFO[2021-07-01T15:05:15+05:30] [Status]: No appLabels provided, skipping the application status checks 
INFO[2021-07-01T15:05:17+05:30] The selected disk volume is:                  InstanceName=test-instance VolumeName=test-disk VolumeType=pd-balanced Status=READY
INFO[2021-07-01T15:05:19+05:30] The selected disk volume is:                  Status=READY InstanceName=test-instance-1 VolumeName=test-disk-1 VolumeType=pd-balanced
INFO[2021-07-01T15:05:21+05:30] [Chaos]: Detaching the disk volume from the instance 
INFO[2021-07-01T15:05:23+05:30] Detaching disk having:                        InstanceName=test-instance Status=RUNNING Device=test-disk
INFO[2021-07-01T15:05:23+05:30] [Chaos]: Detaching the disk volume from the instance 
INFO[2021-07-01T15:05:24+05:30] Detaching disk having:                        InstanceName=test-instance-1 Status=RUNNING Device=test-disk-1
INFO[2021-07-01T15:05:24+05:30] [Info]: Checking if the detachment process initiated 
INFO[2021-07-01T15:05:25+05:30] The selected disk volume is:                  VolumeType=pd-balanced Status=READY InstanceName=test-instance VolumeName=test-disk
INFO[2021-07-01T15:05:29+05:30] [Wait]: Wait for disk volume detachment for volume test-disk 
INFO[2021-07-01T15:05:29+05:30] [Status]: Checking disk volume status for detachment 
INFO[2021-07-01T15:05:30+05:30] [Info]: The volume state is detached         
INFO[2021-07-01T15:05:32+05:30] [Wait]: Wait for disk volume detachment for volume test-disk-1 
INFO[2021-07-01T15:05:32+05:30] [Status]: Checking disk volume status for detachment 
INFO[2021-07-01T15:05:33+05:30] [Info]: The volume state is detached         
INFO[2021-07-01T15:05:35+05:30] [Wait]: Waiting for the chaos interval of 10s 
INFO[2021-07-01T15:05:46+05:30] [Chaos]: Attaching the disk volume to the instance 
INFO[2021-07-01T15:05:48+05:30] Attaching disk having:                        Status=RUNNING Device=test-disk InstanceName=test-instance
INFO[2021-07-01T15:05:48+05:30] [Wait]: Wait for disk volume attachment for volume test-disk 
INFO[2021-07-01T15:05:48+05:30] [Status]: Checking disk volume status for attachment 
INFO[2021-07-01T15:05:49+05:30] [Info]: The volume state is detached         
INFO[2021-07-01T15:05:52+05:30] The selected disk volume is:                  Status=READY InstanceName=test-instance VolumeName=test-disk VolumeType=pd-balanced
INFO[2021-07-01T15:05:52+05:30] [Info]: The volume state is attached         
INFO[2021-07-01T15:05:55+05:30] [Chaos]: Attaching the disk volume to the instance 
INFO[2021-07-01T15:05:58+05:30] Attaching disk having:                        Device=test-disk-1 InstanceName=test-instance-1 Status=RUNNING
INFO[2021-07-01T15:05:58+05:30] [Wait]: Wait for disk volume attachment for volume test-disk-1 
INFO[2021-07-01T15:05:58+05:30] [Status]: Checking disk volume status for attachment 
INFO[2021-07-01T15:05:59+05:30] [Info]: The volume state is detached         
INFO[2021-07-01T15:06:02+05:30] The selected disk volume is:                  VolumeType=pd-balanced Status=READY InstanceName=test-instance-1 VolumeName=test-disk-1
INFO[2021-07-01T15:06:02+05:30] [Info]: The volume state is attached         
INFO[2021-07-01T15:06:04+05:30] [Confirmation]:  chaos has been injected successfully 
INFO[2021-07-01T15:06:04+05:30] [Status]: Verify that the AUT (Application Under Test) is running (post-chaos) 
INFO[2021-07-01T15:06:04+05:30] [Status]: No appLabels provided, skipping the application status checks 
INFO[2021-07-01T15:06:06+05:30] The selected disk volume is:                  Status=READY InstanceName=test-instance VolumeName=test-disk VolumeType=pd-balanced
INFO[2021-07-01T15:06:08+05:30] The selected disk volume is:                  VolumeName=test-disk-1 VolumeType=pd-balanced Status=READY InstanceName=test-instance-1
INFO[2021-07-01T15:06:08+05:30] [The End]: Updating the chaos result of  experiment (EOT) 
```

**ChaosReultt:**
```
Name:         gcp-disk-chaos-vm-disk-loss
Namespace:    default
Labels:       app.kubernetes.io/component=experiment-job
              app.kubernetes.io/part-of=litmus
              app.kubernetes.io/version=latest
              chaosUID=09258335-fd9b-4766-9de4-606c7fc29532
              controller-uid=2d13af51-e33d-4b27-bc73-cc1bdff62d96
              job-name=vm-disk-loss-8fb4o3
              name=gcp-disk-chaos-vm-disk-loss
Annotations:  <none>
API Version:  litmuschaos.io/v1alpha1
Kind:         ChaosResult
Metadata:
  Creation Timestamp:  2021-07-01T06:53:31Z
  Generation:          8
  Managed Fields:
    API Version:  litmuschaos.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .:
          f:app.kubernetes.io/component:
          f:app.kubernetes.io/part-of:
          f:app.kubernetes.io/version:
          f:chaosUID:
          f:controller-uid:
          f:job-name:
          f:name:
      f:spec:
        .:
        f:engine:
        f:experiment:
      f:status:
        .:
        f:experimentStatus:
        f:history:
    Manager:         experiments
    Operation:       Update
    Time:            2021-07-01T06:53:31Z
  Resource Version:  186538
  UID:               9bd737b6-fc81-4356-b02d-bc0528393cde
Spec:
  Engine:      gcp-disk-chaos
  Experiment:  vm-disk-loss
Status:
  Experiment Status:
    Fail Step:                 N/A
    Phase:                     Completed
    Probe Success Percentage:  100
    Verdict:                   Pass
  History:
    Failed Runs:   2
    Passed Runs:   2
    Stopped Runs:  0
    Targ [...]

2021-07-12 08:51 UTC, neelanjan00 commented
Updated experiment logs:

```
W0712 08:47:21.767394       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2021-07-12T08:47:21Z" level=info msg="Experiment Name: gcp-vm-instance-stop"
time="2021-07-12T08:47:21Z" level=info msg="[PreReq]: Procured the ENV for the gcp-vm-instance-stop experiment"
time="2021-07-12T08:47:21Z" level=info msg="[PreReq]: Updating the chaos result of gcp-vm-instance-stop experiment (SOT)"
time="2021-07-12T08:47:21Z" level=info msg="The instance information is as follows" Ramp Time=0 Instance Names="test-instance,test-instance-1" Zones="us-central1-a,us-central1-b" Chaos Duration=30 Chaos Namespace=default
time="2021-07-12T08:47:21Z" level=info msg="[Status]: Verify that the AUT (Application Under Test) is running (pre-chaos)"
time="2021-07-12T08:47:21Z" level=info msg="[Status]: No appLabels provided, skipping the application status checks"
time="2021-07-12T08:47:21Z" level=info msg="[Info]: The instances under chaos(IUC) are: [test-instance test-instance-1]"
time="2021-07-12T08:47:25Z" level=info msg="[Status]: VM instance is in running state"
time="2021-07-12T08:47:25Z" level=info msg="[Info]: Target instanceID list, [test-instance test-instance-1]"
time="2021-07-12T08:47:25Z" level=info msg="[Chaos]: Stopping the desired VM instance"
time="2021-07-12T08:47:26Z" level=info msg="Stopping VM instance:" InstanceZone=us-central1-a InstanceName=test-instance
time="2021-07-12T08:47:26Z" level=info msg="[Chaos]: Stopping the desired VM instance"
time="2021-07-12T08:47:28Z" level=info msg="Stopping VM instance:" InstanceName=test-instance-1 InstanceZone=us-central1-b
time="2021-07-12T08:47:28Z" level=info msg="[Wait]: Wait for VM instance 'test-instance' to get in stopped state"
time="2021-07-12T08:47:28Z" level=info msg="[Status]: Checking VM instance status"
time="2021-07-12T08:47:29Z" level=info msg="The instance state is STOPPING"
time="2021-07-12T08:47:32Z" level=info msg="The instance state is STOPPING"
time="2021-07-12T08:47:35Z" level=info msg="The instance state is STOPPING"
time="2021-07-12T08:47:38Z" level=info msg="The instance state is STOPPING"
time="2021-07-12T08:47:41Z" level=info msg="The instance state is STOPPING"
time="2021-07-12T08:47:45Z" level=info msg="The instance state is TERMINATED"
time="2021-07-12T08:47:47Z" level=info msg="[Wait]: Wait for VM instance 'test-instance-1' to get in stopped state"
time="2021-07-12T08:47:47Z" level=info msg="[Status]: Checking VM instance status"
time="2021-07-12T08:47:48Z" level=info msg="The instance state is TERMINATED"
time="2021-07-12T08:47:50Z" level=info msg="[Wait]: Waiting for chaos interval of 30s"
time="2021-07-12T08:48:20Z" level=info msg="[Chaos]: Starting back the VM instance"
time="2021-07-12T08:48:22Z" level=info msg="Starting VM instance:" InstanceName=test-instance InstanceZone=us-central1-a
time="2021-07-12T08:48:22Z" level=info msg="[Chaos]: Starting back the VM instance"
time="2021-07-12T08:48:23Z" level=info msg="Starting VM instance:" InstanceZone=us-central1-b InstanceName=test-instance-1
time="2021-07-12T08:48:23Z" level=info msg="[Wait]: Wait for VM instance 'test-instance' to get in running state"
time="2021-07-12T08:48:23Z" level=info msg="[Status]: Checking VM instance status"
time="2021-07-12T08:48:24Z" level=info msg="The instance state is STAGING"
time="2021-07-12T08:48:28Z" level=info msg="The instance state is STAGING"
time="2021-07-12T08:48:31Z" level=info msg="The instance state is STAGING"
time="2021-07-12T08:48:34Z" level=info msg="The instance state is RUNNING"
time="2021-07-12T08:48:36Z" level=info msg="[Wait]: Wait for VM instance 'test-instance-1' to get in running state"
time="2021-07-12T08:48:36Z" level=info msg="[Status]: Checking VM instance status"
time="2021-07-12T08:48:37Z" level=info msg="The instance state is RUNNING"
time="2021-07-12T08:48:39Z" level=info msg="[Confirmation]: gcp-vm-instance-stop chaos has been injected successfully"
time="2021-07-12T08:48:39Z" level=info msg="[Info]: The instances under chaos(IUC) are: [test-instance test-instance-1]"
time="2021-07-12T08:48:41Z" level=info msg="[Status]: VM instance is in running state (post chaos)"
time="2021-07-12T08:48:41Z" level=info msg="[Status]: Verify that the AUT (Application Under Test) is running (post-chaos)"
time="2021-07-12T08:48:41Z" level=info msg="[Status]: No appLabels provided, skipping the application status checks"
time="2021-07-12T08:48:41Z" level=info msg="[The End]: Updating the chaos result of gcp-vm-instance-stop experiment (EOT)"
```

2021-07-12 08:53 UTC, neelanjan00 commented
Updated experiment ChaosResult:

```
Name:         gcp-vm-chaos-gcp-vm-instance-stop
Namespace:    default
Labels:       app.kubernetes.io/component=experiment-job
              app.kubernetes.io/part-of=litmus
              app.kubernetes.io/version=latest
              chaosUID=50d56c83-4ac1-4526-b30b-6b64712d2afa
              controller-uid=e2846d03-94cd-4023-80d4-cb6651dceda7
              job-name=gcp-vm-instance-stop-b4imfv
              name=gcp-vm-chaos-gcp-vm-instance-stop
Annotations:  <none>
API Version:  litmuschaos.io/v1alpha1
Kind:         ChaosResult
Metadata:
  Creation Timestamp:  2021-07-12T08:47:21Z
  Generation:          2
  Managed Fields:
    API Version:  litmuschaos.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .:
          f:app.kubernetes.io/component:
          f:app.kubernetes.io/part-of:
          f:app.kubernetes.io/version:
          f:chaosUID:
          f:controller-uid:
          f:job-name:
          f:name:
      f:spec:
        .:
        f:engine:
        f:experiment:
      f:status:
        .:
        f:experimentStatus:
        f:history:
    Manager:         experiments
    Operation:       Update
    Time:            2021-07-12T08:47:21Z
  Resource Version:  219492
  UID:               22f867ac-f69b-42af-8afe-626a160d5e14
Spec:
  Engine:      gcp-vm-chaos
  Experiment:  gcp-vm-instance-stop
Status:
  Experiment Status:
    Fail Step:                 N/A
    Phase:                     Completed
    Probe Success Percentage:  100
    Verdict:                   Pass
  History:
    Failed Runs:   0
    Passed Runs:   1
    Stopped Runs:  0
    Targets:
      Chaos Status:  reverted
      Kind:          VM
      Name:          test-instance
      Chaos Status:  reverted
      Kind:          VM
      Name:          test-instance-1
Events:
  Type    Reason   Age    From                               Message
  ----    ------   ----   ----                               -------
  Normal  Awaited  4m54s  gcp-vm-instance-stop-b4imfv-xjlz2  experiment: gcp-vm-instance-stop, Result: Awaited
  Normal  Pass     3m34s  gcp-vm-instance-stop-b4imfv-xjlz2  experiment: gcp-vm-instance-stop, Result: Pass
```

2021-07-12 10:59 UTC, neelanjan00 commented
Experiment name changed to `gcp-vm-disk-loss`

2021-07-12 11:00 UTC, neelanjan00 commented
Updated experiment logs:

```
W0712 10:55:46.379317       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2021-07-12T10:55:46Z" level=info msg="Experiment Name: gcp-vm-disk-loss"
time="2021-07-12T10:55:46Z" level=info msg="[PreReq]: Getting the ENV for the gcp-vm-disk-loss experiment"
time="2021-07-12T10:55:46Z" level=info msg="[PreReq]: Updating the chaos result of gcp-vm-disk-loss experiment (SOT)"
time="2021-07-12T10:55:46Z" level=info msg="The application information is as follows" App Namespace=default AppLabel= Ramp Time=0
time="2021-07-12T10:55:46Z" level=info msg="The volume information is as follows" Volume IDs="test-disk,test-disk-1" Zones="us-central1-a,us-central1-b" Ramp Time=0
time="2021-07-12T10:55:46Z" level=info msg="[Status]: Verify that the AUT (Application Under Test) is running (pre-chaos)"
time="2021-07-12T10:55:46Z" level=info msg="[Status]: No appLabels provided, skipping the application status checks"
time="2021-07-12T10:55:55Z" level=info msg="The selected disk volume is:" VolumeType=pd-balanced Status=READY InstanceName=test-instance VolumeName=test-disk
time="2021-07-12T10:56:00Z" level=info msg="The selected disk volume is:" VolumeType=pd-balanced Status=READY InstanceName=test-instance-1 VolumeName=test-disk-1
time="2021-07-12T10:56:07Z" level=info msg="[Chaos]: Detaching the disk volume from the instance"
time="2021-07-12T10:56:08Z" level=info msg="Detaching disk having:" Device=test-disk InstanceName=test-instance Status=RUNNING
time="2021-07-12T10:56:08Z" level=info msg="[Chaos]: Detaching the disk volume from the instance"
time="2021-07-12T10:56:10Z" level=info msg="Detaching disk having:" InstanceName=test-instance-1 Status=RUNNING Device=test-disk-1
time="2021-07-12T10:56:10Z" level=info msg="[Info]: Checking if the detachment process initiated"
time="2021-07-12T10:56:18Z" level=info msg="[Wait]: Wait for disk volume detachment for volume test-disk"
time="2021-07-12T10:56:18Z" level=info msg="[Status]: Checking disk volume status for detachment"
time="2021-07-12T10:56:23Z" level=info msg="[Info]: The volume state is detached"
time="2021-07-12T10:56:25Z" level=info msg="[Wait]: Wait for disk volume detachment for volume test-disk-1"
time="2021-07-12T10:56:25Z" level=info msg="[Status]: Checking disk volume status for detachment"
time="2021-07-12T10:56:27Z" level=info msg="[Info]: The volume state is detached"
time="2021-07-12T10:56:29Z" level=info msg="[Wait]: Waiting for the chaos interval of 30s"
time="2021-07-12T10:57:01Z" level=info msg="[Chaos]: Attaching the disk volume to the instance"
time="2021-07-12T10:57:04Z" level=info msg="Attaching disk having:" InstanceName=test-instance Status=RUNNING Device=test-disk
time="2021-07-12T10:57:04Z" level=info msg="[Wait]: Wait for disk volume attachment for volume test-disk"
time="2021-07-12T10:57:04Z" level=info msg="[Status]: Checking disk volume status for attachment"
time="2021-07-12T10:57:07Z" level=info msg="The selected disk volume is:" VolumeName=test-disk VolumeType=pd-balanced Status=READY InstanceName=test-instance
time="2021-07-12T10:57:07Z" level=info msg="[Info]: The volume state is attached"
time="2021-07-12T10:57:10Z" level=info msg="[Chaos]: Attaching the disk volume to the instance"
time="2021-07-12T10:57:15Z" level=info msg="Attaching disk having:" Status=RUNNING Device=test-disk-1 InstanceName=test-instance-1
time="2021-07-12T10:57:15Z" level=info msg="[Wait]: Wait for disk volume attachment for volume test-disk-1"
time="2021-07-12T10:57:15Z" level=info msg="[Status]: Checking disk volume status for attachment"
time="2021-07-12T10:57:18Z" level=info msg="The selected disk volume is:" VolumeName=test-disk-1 VolumeType=pd-balanced Status=READY InstanceName=test-instance-1
time="2021-07-12T10:57:18Z" level=info msg="[Info]: The volume state is attached"
time="2021-07-12T10:57:20Z" level=info msg="[Confirmation]: gcp-vm-disk-loss chaos has been injected successfully"
time="2021-07-12T10:57:20Z" level=info msg="[Status]: Verify that the AUT (Application Under Test) is running (post-chaos)"
time="2021-07-12T10:57:20Z" level=info msg="[Status]: No appLabels provided, skipping the application status checks"
time="2021-07-12T10:57:24Z" level=info msg="The selected disk volume is:" InstanceName=test-instance VolumeName=test-disk VolumeType=pd-balanced Status=READY
time="2021-07-12T10:57:28Z" level=info msg="The selected disk volume is:" Status=READY InstanceName=test-instance-1 VolumeName=test-disk-1 VolumeType=pd-balanced
time="2021-07-12T10:57:28Z" level=info msg="[The End]: Updating the chaos result of gcp-vm-disk-loss experiment (EOT)"
```

2021-07-12 11:01 UTC, neelanjan00 commented
Updated ChaosResult:

```
Name:         gcp-disk-chaos-gcp-vm-disk-loss
Namespace:    default
Labels:       app.kubernetes.io/component=experiment-job
              app.kubernetes.io/part-of=litmus
              app.kubernetes.io/version=latest
              chaosUID=a6d2ee16-a8e5-4f8a-a7cd-3e08aa7beb6e
              controller-uid=8c7f54fb-671d-4e37-a518-1e78e5dd2355
              job-name=gcp-vm-disk-loss-2w4803
              name=gcp-disk-chaos-gcp-vm-disk-loss
Annotations:  <none>
API Version:  litmuschaos.io/v1alpha1
Kind:         ChaosResult
Metadata:
  Creation Timestamp:  2021-07-12T10:55:46Z
  Generation:          2
  Managed Fields:
    API Version:  litmuschaos.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .:
          f:app.kubernetes.io/component:
          f:app.kubernetes.io/part-of:
          f:app.kubernetes.io/version:
          f:chaosUID:
          f:controller-uid:
          f:job-name:
          f:name:
      f:spec:
        .:
        f:engine:
        f:experiment:
      f:status:
        .:
        f:experimentStatus:
        f:history:
    Manager:         experiments
    Operation:       Update
    Time:            2021-07-12T10:55:46Z
  Resource Version:  225260
  UID:               ae011420-8ed6-4672-b342-20f62f60ef90
Spec:
  Engine:      gcp-disk-chaos
  Experiment:  gcp-vm-disk-loss
Status:
  Experiment Status:
    Fail Step:                 N/A
    Phase:                     Completed
    Probe Success Percentage:  100
    Verdict:                   Pass
  History:
    Failed Runs:   0
    Passed Runs:   1
    Stopped Runs:  0
    Targets:
      Chaos Status:  reverted
      Kind:          DiskVolume
      Name:          test-disk
      Chaos Status:  reverted
      Kind:          DiskVolume
      Name:          test-disk-1
Events:
  Type    Reason   Age    From                           Message
  ----    ------   ----   ----                           -------
  Normal  Awaited  5m9s   gcp-vm-disk-loss-2w4803-qc87h  experiment: gcp-vm-disk-loss, Result: Awaited
  Normal  Pass     3m27s  gcp-vm-disk-loss-2w4803-qc87h  experiment: gcp-vm-disk-loss, Result: Pass
```

2021-07-13 04:56 UTC, ispeakc0de commented on chaoslib/litmus/gcp-vm-disk-loss/lib/gcp-vm-disk-loss.go
> +		diskNamesList := strings.Split(experimentsDetails.DiskVolumeNames, ",")
Can we move this func just after the `waiting for RampTime`

2021-07-13 04:59 UTC, ispeakc0de commented on chaoslib/litmus/gcp-vm-disk-loss/lib/gcp-vm-disk-loss.go
> +func InjectChaosInSerialMode(experimentsDetails *experimentTypes.ExperimentDetails, targetDiskVolumeNamesList []string, clients clients.ClientSets, resultDetails *types.ResultDetails, eventsDetails *
We can use lower case func names if we are importing those functions outside of the pkg

2021-07-13 05:07 UTC, neelanjan00 commented on chaoslib/litmus/gcp-vm-disk-loss/lib/gcp-vm-disk-loss.go
> +		diskNamesList := strings.Split(experimentsDetails.DiskVolumeNames, ",")
Done.

2021-07-13 05:07 UTC, neelanjan00 commented on chaoslib/litmus/gcp-vm-disk-loss/lib/gcp-vm-disk-loss.go
> +func InjectChaosInSerialMode(experimentsDetails *experimentTypes.ExperimentDetails, targetDiskVolumeNamesList []string, clients clients.ClientSets, resultDetails *types.ResultDetails, eventsDetails *
Updated

2021-07-13 05:23 UTC, ispeakc0de commented on chaoslib/litmus/gcp-vm-disk-loss/lib/gcp-vm-disk-loss.go
> +		instanceName, err := gcp.GetVolumeAttachmentDetails(experimentsDetails.GCPProjectID, diskZonesList[i], diskNamesList[i])
It may return an error if disk is already detached, can we derive the instance names in the prepareChaos section and use further

2021-07-13 05:24 UTC, ispeakc0de commented on experiments/gcp/gcp-vm-disk-loss/experiment/gcp-vm-disk-loss.go
> +		"Ramp Time":  experimentsDetails.RampTime,
we can remove Ramp Time

2021-07-13 05:27 UTC, ispeakc0de commented on experiments/gcp/gcp-vm-disk-loss/rbac.yaml
> +  name: vm-disk-loss-sa
```suggestion
  name: gcp-vm-disk-loss-sa
```

2021-07-13 05:28 UTC, ispeakc0de commented on experiments/gcp/gcp-vm-disk-loss/test/test.yml
> +      serviceAccountName: vm-disk-loss-sa
```suggestion
      serviceAccountName: gcp-vm-disk-loss-sa
```

2021-07-13 05:28 UTC, ispeakc0de commented on experiments/gcp/gcp-vm-disk-loss/test/test.yml
> +            value: '0'
```suggestion
            value: ''
```

2021-07-13 05:36 UTC, ispeakc0de commented on pkg/cloud/gcp/disk-volume-status.go
> +	}
```suggestion
	if len(diskNamesList) != len(zonesList) || len(zonesList) != len(deviceNamesList) {
		return errors.Errorf("unequal number of disk names, zones, and device names found, please verify the input details")
	}
```

2021-07-13 05:43 UTC, ispeakc0de commented on pkg/cloud/gcp/disk-volume-status.go
> +func CheckDiskVolumeDetachmentInitialisation(gcpProjectID string, diskNamesList []string, instanceNamesList []string, zones []string) error {
Do we need this func? WaitingForDetach is also validating same thing

2021-07-13 05:44 UTC, ispeakc0de commented on pkg/gcp/gcp-vm-disk-loss/environment/environment.go
> +	experimentDetails.VolumeAffectedPerc, _ = strconv.Atoi(common.Getenv("VOLUME_AFFECTED_PERC", "0"))
we can remove unused attributes

2021-07-13 06:16 UTC, neelanjan00 commented on chaoslib/litmus/gcp-vm-disk-loss/lib/gcp-vm-disk-loss.go
> +		instanceName, err := gcp.GetVolumeAttachmentDetails(experimentsDetails.GCPProjectID, diskZonesList[i], diskNamesList[i])
A separate global variable `string instanceNamesList[]` now stores the associated instance names.

2021-07-13 06:17 UTC, neelanjan00 commented on experiments/gcp/gcp-vm-disk-loss/experiment/gcp-vm-disk-loss.go
> +		"Ramp Time":  experimentsDetails.RampTime,
Done

2021-07-13 06:21 UTC, neelanjan00 commented on experiments/gcp/gcp-vm-disk-loss/rbac.yaml
> +  name: vm-disk-loss-sa
Updated all of these changes.

2021-07-13 06:21 UTC, neelanjan00 commented on experiments/gcp/gcp-vm-disk-loss/test/test.yml
> +      serviceAccountName: vm-disk-loss-sa
updated

2021-07-13 06:22 UTC, neelanjan00 commented on experiments/gcp/gcp-vm-disk-loss/test/test.yml
> +            value: '0'
Updated

2021-07-13 06:23 UTC, neelanjan00 commented on pkg/cloud/gcp/disk-volume-status.go
> +	}
updated

2021-07-13 06:30 UTC, neelanjan00 commented on pkg/cloud/gcp/disk-volume-status.go
> +func CheckDiskVolumeDetachmentInitialisation(gcpProjectID string, diskNamesList []string, instanceNamesList []string, zones []string) error {
Removed `CheckDiskVolumeDetachmentInitialisation` function as well as detachment initialization check on account of being redundant as the `WaitForVolumeDetachment` function, immediately following it.

2021-07-13 06:34 UTC, neelanjan00 commented on pkg/gcp/gcp-vm-disk-loss/environment/environment.go
> +	experimentDetails.VolumeAffectedPerc, _ = strconv.Atoi(common.Getenv("VOLUME_AFFECTED_PERC", "0"))
Done

2021-07-13 09:01 UTC, ispeakc0de submitted a review, later dismissed

2021-07-13 12:17 UTC, uditgaurav requested changes

2021-07-13 12:17 UTC, uditgaurav commented on experiments/gcp/gcp-vm-disk-loss/experiment/gcp-vm-disk-loss.go
> +		log.Errorf("volume status check failed pre chaos, err: %v", err)
```suggestion
		log.Errorf("volume status check failed post chaos, err: %v", err)
```

2021-07-13 12:17 UTC, uditgaurav commented on pkg/cloud/gcp/disk-volume-status.go
> +func GetDiskVolumeState(diskName string, gcpProjectID string, instanceName string, zone string) (string, error) {
```suggestion
func GetDiskVolumeState(diskName , gcpProjectID , instanceName , zone string) (string, error) {
```
You don't need to provide type for every arg if it is same

2021-07-13 12:17 UTC, uditgaurav commented on chaoslib/litmus/gcp-vm-disk-loss/lib/gcp-vm-disk-loss.go
> +		}
can we shift these preparation steps before recording chaos duration? you can do this in PrepareDiskVolumeLoss function only?

2021-07-13 12:17 UTC, uditgaurav commented on pkg/gcp/gcp-vm-disk-loss/types/types.go
> +	RunID                    string
RunID is not required.

2021-07-13 12:17 UTC, uditgaurav commented on experiments/gcp/gcp-vm-disk-loss/experiment/gcp-vm-disk-loss.go
> +		failStep := "Verify the disk volume is attached to am instance (post-chaos)"
```suggestion
		failStep := "Verify the disk volume is attached to an instance (post-chaos)"
```

2021-07-13 12:41 UTC, neelanjan00 commented on pkg/gcp/gcp-vm-disk-loss/environment/environment.go
> +	experimentDetails.DeviceNames = common.Getenv("DEVICE_NAMES", "")
GCP APIs don't contain the device name, hence it needs to be manually entered

2021-07-13 13:06 UTC, neelanjan00 commented on chaoslib/litmus/gcp-vm-disk-loss/lib/gcp-vm-disk-loss.go
> +	//get the volume id or list of instance ids
The comment seems to be wrong, I have updated it now

2021-07-13 13:08 UTC, neelanjan00 commented on experiments/gcp/gcp-vm-disk-loss/experiment/gcp-vm-disk-loss.go
> +		log.Errorf("volume status check failed pre chaos, err: %v", err)
Updated

2021-07-13 13:17 UTC, neelanjan00 commented on pkg/cloud/gcp/disk-volume-status.go
> +func GetDiskVolumeState(diskName string, gcpProjectID string, instanceName string, zone string) (string, error) {
Agreed, I was only putting them so that some other variable of a different data type doesn't accidentally get passed through the function. I'd remove them.

2021-07-13 13:37 UTC, neelanjan00 commented on pkg/gcp/gcp-vm-disk-loss/types/types.go
> +	RunID                    string
updated

2021-07-13 13:37 UTC, neelanjan00 commented on chaoslib/litmus/gcp-vm-disk-loss/lib/gcp-vm-disk-loss.go
> +		}
updated

2021-07-13 13:42 UTC, neelanjan00 commented on experiments/gcp/gcp-vm-disk-loss/experiment/gcp-vm-disk-loss.go
> +		failStep := "Verify the disk volume is attached to am instance (post-chaos)"
corrected

2021-07-13 14:38 UTC, uditgaurav commented on pkg/gcp/gcp-vm-disk-loss/environment/environment.go
> +	experimentDetails.DeviceNames = common.Getenv("DEVICE_NAMES", "")
okay, we can revisit this later.

2021-07-13 14:48 UTC, uditgaurav commented on pkg/gcp/gcp-vm-disk-loss/types/types.go
> +	RunID                    string
This is still not updated.

2021-07-13 14:53 UTC, uditgaurav commented on chaoslib/litmus/gcp-vm-disk-loss/lib/gcp-vm-disk-loss.go
> +			if err = gcp.DiskVolumeDetach(instanceNamesList[i], experimentsDetails.GCPProjectID, diskZonesList[i], deviceNamesList[i]); err != nil {
How are you getting the `instanceNamesList` here it is not passed in `injectChaosInSerialMode`?
Do we need to define it globally can we define it inside injectChaosInSerialMode?

2021-07-13 14:57 UTC, neelanjan00 commented on pkg/gcp/gcp-vm-disk-loss/types/types.go
> +	RunID                    string
My apologies, finally fixed now 😅

2021-07-13 15:09 UTC, neelanjan00 commented on chaoslib/litmus/gcp-vm-disk-loss/lib/gcp-vm-disk-loss.go
> +			if err = gcp.DiskVolumeDetach(instanceNamesList[i], experimentsDetails.GCPProjectID, diskZonesList[i], deviceNamesList[i]); err != nil {
Fixed

2021-07-13 15:12 UTC, uditgaurav submitted a review, later dismissed

2021-07-13 16:01 UTC, ispeakc0de submitted a review, later dismissed

2021-07-14 05:02 UTC, uditgaurav approved these changes

2021-07-14 06:06 UTC, ispeakc0de approved these changes

2021-07-14 09:51 UTC, merged