New experiment for node restart using redfish API
litmuschaos/litmus-go pull request #404
Opened 2021-07-22 16:09 UTC by gpsingh-1991

**What this PR does / why we need it**: This PR would help introduce node restart of baremetal nodes using the redfish API.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #385 

**Special notes for your reviewer**:

**Checklist:**
-   [ ] Fixes #<issue number>
-   [ ] PR messages has document related information
-   [ ] Labelled this PR & related issue with `breaking-changes` tag
-   [ ] PR messages has breaking changes related information
-   [ ] Labelled this PR & related issue with `requires-upgrade` tag
-   [ ] PR messages has upgrade related information
-   [ ] Commit has unit tests
-   [ ] Commit has integration tests
-   [ ] E2E run Required for the changes

2021-07-23 03:31 UTC, ksatchit commented
@gpsingh-1991  thanks for the PR! Could you share any experiment run logs for reference? Also details of the environment this was tested against

2021-07-23 05:50 UTC, gpsingh-1991 commented
Hi @ksatchit . Please find the output from okteto run as below:

default:litmus-experiment okteto> go run bin/experiment/experiment.go -name redfish-node-restart
W0722 15:43:30.321489     124 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
INFO[2021-07-22T15:43:30Z] Experiment Name: redfish-node-restart        
INFO[2021-07-22T15:43:30Z] [PreReq]: Getting the ENV for the  experiment 
INFO[2021-07-22T15:43:30Z] [PreReq]: Updating the chaos result of  experiment (SOT) 
INFO[2021-07-22T15:43:30Z] [Info]: The Node information is as follows    Node=192.168.56.111 User=Admin Ramp Time=0
INFO[2021-07-22T15:43:30Z] [Status]: Verify that the NUT (Node Under Test) is running (pre-chaos) 
INFO[2021-07-22T15:43:33Z] 200 OK                                       
INFO[2021-07-22T15:43:33Z] [Verification]: Node is in running state(pre-chaos) 
INFO[2021-07-22T15:43:35Z] 204 No Content                               
INFO[2021-07-22T15:43:35Z] [Chaos]:Waiting for: 30s                     
INFO[2021-07-22T15:44:05Z] [Confirmation]:  chaos has been injected successfully 
INFO[2021-07-22T15:44:05Z] [Status]: Verify that the NUT (Node Under Test) is running (post-chaos) 
INFO[2021-07-22T15:44:08Z] 200 OK                                       
INFO[2021-07-22T15:44:08Z] [Verification]: Node is in running state(post-chaos) 
INFO[2021-07-22T15:44:08Z] [The End]: Updating the chaos result of  experiment (EOT)

2021-07-24 07:51 UTC, avaakash commented on chaoslib/litmus/redfish-node-restart/lib/redfish-node-restart.go
> +	time.Sleep(30 * time.Second)
We can use `common.WaitForDuration(experimentsDetails.ChaosDuration)` here

2021-07-24 07:51 UTC, avaakash commented on experiments/baremetal/redfish-node-restart/experiment/redfish-node-restart.go
> +func NodeRestart(clients clients.ClientSets) {
Can we rename this function to `RedfishNodeRestart`, it will be easier to keep track this way. Also, change it in the `experiment.go` file.

2021-07-24 07:52 UTC, avaakash commented on pkg/baremetal/redfish/redfish.go
> +func RebootNode(URL, user, password string) {
I think we can return an error from this function, so that the experiment fails if the API request fails, currently the `injectChaos` functions returns `nil` so the experiment will be treated as success even though the node didn't reboot due to API failure

2021-07-26 08:23 UTC, gpsingh-1991 commented on chaoslib/litmus/redfish-node-restart/lib/redfish-node-restart.go
> +	time.Sleep(30 * time.Second)
The parameter chaos duration does not make sense in this case. I just added 30s sleep just to make sure the restart is triggered(Could remove this).

2021-07-26 08:54 UTC, gpsingh-1991 commented on experiments/baremetal/redfish-node-restart/experiment/redfish-node-restart.go
> +func NodeRestart(clients clients.ClientSets) {
The file name already has redfish in the name. I think adding redfish again would be redundant.

2021-07-27 11:06 UTC, gpsingh-1991 commented on pkg/baremetal/redfish/redfish.go
> +func RebootNode(URL, user, password string) {
Done

2021-07-29 15:48 UTC, ishangupta-ds commented on chaoslib/litmus/redfish-node-restart/lib/redfish-node-restart.go
> +	//Starting the CPU stress experiment
comments can be updated.

2021-08-04 14:44 UTC, uditgaurav requested changes

2021-08-04 14:44 UTC, uditgaurav commented on chaoslib/litmus/redfish-node-restart/lib/redfish-node-restart.go
> +	log.Infof("[Chaos]:Waiting for: %vs", experimentsDetails.ChaosDuration)
Can we remove the hardcoded 30 seconds with the ChaosDuration ENV?

2021-08-04 14:44 UTC, uditgaurav commented on chaoslib/litmus/redfish-node-restart/lib/redfish-node-restart.go
> +
We can include Probe here. The code will be:
```go
// run the probes during chaos
if len(resultDetails.ProbeDetails) != 0 {
  if err = probe.RunProbes(chaosDetails, clients, resultDetails, "DuringChaos", eventsDetails); err != nil {
	  return err
  }
}
```

2021-08-04 14:44 UTC, uditgaurav commented on experiments/baremetal/redfish-node-restart/experiment/redfish-node-restart.go
> +		"Node":      experimentsDetails.IPMIIP,
```suggestion
		"Node IPMIIP":      experimentsDetails.IPMIIP,
```

2021-08-04 14:44 UTC, uditgaurav commented on pkg/baremetal/redfish/redfish.go
> +		log.Fatal(err.Error())
Can we please avoide log.Fatal and return errors.Errorf()

2021-08-04 14:44 UTC, uditgaurav commented on pkg/baremetal/redfish/redfish.go
> +		return "Unknown"
Can we return the error here?  Please check this for all other places.
```suggestion
		return  errors.Errorf("fail to get the node status, err: %v", msg)
```

2021-08-04 14:44 UTC, uditgaurav commented on chaoslib/litmus/redfish-node-restart/lib/redfish-node-restart.go
> +	return nil
```suggestion
	return redfishLib.RebootNode(URL, experimentsDetails.User, experimentsDetails.Password)
```

2021-08-04 14:44 UTC, uditgaurav commented on experiments/baremetal/redfish-node-restart/test/test.yml
> +          - name: RAMP_TIME
can we also include other variables like chaos duration and others(need to check)?

2021-08-04 14:44 UTC, uditgaurav commented on pkg/baremetal/redfish-node-restart/environment/environment.go
> +	experimentDetails.ChaosInterval, _ = strconv.Atoi(common.Getenv("CHAOS_INTERVAL", "10"))
Are we using chaos interval anywhere? If not we can remove it.

2021-08-04 14:49 UTC, uditgaurav requested changes

2021-08-04 14:49 UTC, uditgaurav commented on chaoslib/litmus/redfish-node-restart/lib/redfish-node-restart.go
> +	if err := injectChaos(experimentsDetails, clients); err != nil {
After injecting chaos can we also validate the experiment that is - Is the node status is getting down and once it gets down after that we can wait for some time and bring it back.

2021-08-05 05:22 UTC, ispeakc0de commented on chaoslib/litmus/redfish-node-restart/lib/redfish-node-restart.go
> +	if err := experimentExecution(experimentsDetails, clients, resultDetails, eventsDetails, chaosDetails); err != nil {
we can patch the target nodes' name & status inside chaosresult.
call the below function immediately after the experimentExecution function
```
common.SetTargets(experimentsDetails.TargetNode, "targeted", "node", chaosDetails)

```

2021-08-05 05:25 UTC, ispeakc0de commented on experiments/baremetal/redfish-node-restart/experiment/redfish-node-restart.go
> +	go common.AbortWatcherWithoutExit(experimentsDetails.ExperimentName, clients, &resultDetails, &chaosDetails, &eventsDetails)
```suggestion
	go common.AbortWatcher(experimentsDetails.ExperimentName, clients, &resultDetails, &chaosDetails, &eventsDetails)
```

2021-08-05 05:33 UTC, ispeakc0de commented on experiments/baremetal/redfish-node-restart/experiment/redfish-node-restart.go
> +	nodeStatus := redfishLib.GetNodeStatus(experimentsDetails.IPMIIP, experimentsDetails.User, experimentsDetails.Password)
Can you please add `AUTStatusCheck` and `CheckAuxiliaryApplicationStatu` in pre & post chaos sections?
refer: https://github.com/litmuschaos/litmus-go/blob/master/experiments/generic/node-restart/experiment/node-restart.go#L80

2021-08-05 05:35 UTC, ispeakc0de commented on experiments/baremetal/redfish-node-restart/test/test.yml
> +    spec:
Can you add serviceAccount name here ` serviceAccountName: redfish-node-restart-sa`

2021-08-05 05:36 UTC, ispeakc0de commented on experiments/baremetal/redfish-node-restart/test/test.yml
> +          ## default: litmus. Supported values: litmus, powerfulseal, chaoskube
```suggestion
```

2021-08-05 05:37 UTC, ispeakc0de commented on pkg/baremetal/redfish-node-restart/environment/environment.go
> +	experimentDetails.ChaosInjectCmd = common.Getenv("CHAOS_INJECT_COMMAND", "")
we can remove all the unused env here: ChaosInjectCmd, ChaosKillCmd, PodsAffectedPerc, TargetPods

2021-08-05 05:38 UTC, ispeakc0de commented on pkg/baremetal/redfish-node-restart/types/types.go
> +// ADD THE ATTRIBUTES OF YOUR CHOICE HERE
we can remove extra comments

2021-08-05 05:38 UTC, ispeakc0de commented on pkg/baremetal/redfish-node-restart/environment/environment.go
> +	experimentDetails.ChaosInjectCmd = common.Getenv("CHAOS_INJECT_COMMAND", "")
Also, remove from the typs.go

2021-08-05 05:40 UTC, ispeakc0de commented on pkg/baremetal/redfish/redfish.go
> +//rebootNode triggers hard reset on the target baremetal node
```suggestion
//RebootNode triggers hard reset on the target baremetal node
```

2021-08-05 10:31 UTC, gpsingh-1991 commented on experiments/baremetal/redfish-node-restart/test/test.yml
> +          - name: RAMP_TIME
Chaos duration is not needed as we are triggering restart (not power off and on).

2021-08-05 10:33 UTC, gpsingh-1991 commented on chaoslib/litmus/redfish-node-restart/lib/redfish-node-restart.go
> +	if err := injectChaos(experimentsDetails, clients); err != nil {
I am afraid this won't be applicable here as we are triggering restart not power down and up.

2021-08-20 17:36 UTC, ispeakc0de commented on experiments/baremetal/redfish-node-restart/experiment/redfish-node-restart.go
> +		result.RecordAfterFailure(&chaosDetails, &resultDetails, failStep, clients, &eventsDetails)
Can we create an event inside chaosengine. Refer: https://github.com/litmuschaos/litmus-go/blob/master/experiments/generic/container-kill/experiment/container-kill.go#L74

2021-08-20 17:36 UTC, ispeakc0de commented on experiments/baremetal/redfish-node-restart/experiment/redfish-node-restart.go
> +		result.RecordAfterFailure(&chaosDetails, &resultDetails, failStep, clients, &eventsDetails)
Similar for post-chaos AUTStatusCheck

2021-08-20 17:40 UTC, ispeakc0de commented on experiments/baremetal/redfish-node-restart/test/test.yml
> +          - name: RAMP_TIME
But we are are using chaos-duration here: https://github.com/gpsingh-1991/litmus-go/blob/master/chaoslib/litmus/redfish-node-restart/lib/redfish-node-restart.go#L44

2021-08-23 06:53 UTC, gpsingh-1991 commented on experiments/baremetal/redfish-node-restart/test/test.yml
> +          - name: RAMP_TIME
I added this to honour the comments. I have put the default value of 30s in environments file.

2021-08-23 18:07 UTC, ispeakc0de approved these changes

2021-08-30 17:43 UTC, uditgaurav requested changes

2021-08-30 17:43 UTC, uditgaurav commented on experiments/baremetal/redfish-node-restart/experiment/redfish-node-restart.go
> +		log.Errorf("[Verification]: Unable to get node power status. Error: ", err)
```suggestion
		log.Errorf("[Verification]: Unable to get node power status. Error: %v ", err)
```

2021-08-30 17:43 UTC, uditgaurav commented on experiments/baremetal/redfish-node-restart/experiment/redfish-node-restart.go
> +		log.Errorf("[Verification]: Unable to get node power status(pre-chaos). Error: ", err)
```suggestion
		log.Errorf("[Verification]: Unable to get node power status(pre-chaos). Error: %v", err)
```

2021-09-01 09:19 UTC, uditgaurav approved these changes

2021-09-01 09:46 UTC, ispeakc0de approved these changes

2021-09-01 09:47 UTC, merged