Process Kill Experiment and cmdProbe modification for m-agent
litmuschaos/litmus-go pull request #479
Opened 2022-01-14 15:24 UTC by neelanjan00

## Why We Need This PR
This PR adds the m-agent based Process Kill experiment and the inline cmdProbe modification for executing commands natively using m-agent

**Special notes for your reviewer**:
- No breaking changes
- Tested the experiment for positive and negative cases for Ubuntu, CentOS, RHEL, and SUSE Linux.

**Checklist:**
-   [ ] Fixes #<issue number>
-   [ ] PR messages has document related information
-   [ ] Labelled this PR & related issue with `breaking-changes` tag
-   [ ] PR messages has breaking changes related information
-   [ ] Labelled this PR & related issue with `requires-upgrade` tag
-   [ ] PR messages has upgrade related information
-   [ ] Commit has unit tests
-   [ ] Commit has integration tests
-   [ ] E2E run Required for the changes

Experiment logs for successful cmd probe execution:
```
W0114 15:17:41.006930       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2022-01-14T15:17:41Z" level=info msg="Experiment Name: process-kill"
time="2022-01-14T15:17:41Z" level=info msg="[PreReq]: Getting the ENV for the process-kill experiment"
time="2022-01-14T15:17:43Z" level=info msg="[PreReq]: Updating the chaos result of process-kill experiment (SOT)"
time="2022-01-14T15:17:47Z" level=info msg="[Info]: The process information is as follows" Process IDs=1608
time="2022-01-14T15:17:47Z" level=info msg="[Status]: Connecting to the agent"
time="2022-01-14T15:17:47Z" level=info msg="[Status]: Verify that the target processes are running"
time="2022-01-14T15:17:50Z" level=info msg="[Probe]: The cmd probe information is as follows" Phase=PreChaos Name=test-cmd-probe Command="cat /home/neelanjan/example.txt" Comparator="{string equal This is From GCP VM}" Source="{ false}" Run Properties="{5 2 1 0 0 false}" Mode=Edge
time="2022-01-14T15:17:50Z" level=info msg="[Probe]: Executing Cmd Probe via agent"
time="2022-01-14T15:17:50Z" level=info msg="[Probe]: {Actual value: This is From GCP VM}, {Expected value: This is From GCP VM}, {Operator: equal}"
time="2022-01-14T15:17:52Z" level=info msg="[Probe]: test-cmd-probe probe has been Passed 😄 " ProbeStatus=Passed ProbeName=test-cmd-probe ProbeType=cmdProbe ProbeInstance=PreChaos
time="2022-01-14T15:17:52Z" level=info msg="[Info]: Target processes list: [1608]"
time="2022-01-14T15:17:52Z" level=info msg="[Chaos]: Killing [1608] processes"
time="2022-01-14T15:17:52Z" level=info msg="[Chaos]: [1608] processes killed successfully"
time="2022-01-14T15:17:54Z" level=info msg="[Wait]: Waiting for chaos interval of 30s"
time="2022-01-14T15:18:24Z" level=info msg="[Confirmation]: process-kill chaos has been injected successfully"
time="2022-01-14T15:18:26Z" level=info msg="[Probe]: The cmd probe information is as follows" Mode=Edge Phase=PostChaos Name=test-cmd-probe Command="cat /home/neelanjan/example.txt" Comparator="{string equal This is From GCP VM}" Source="{ false}" Run Properties="{5 2 1 0 0 false}"
time="2022-01-14T15:18:26Z" level=info msg="[Probe]: Executing Cmd Probe via agent"
time="2022-01-14T15:18:29Z" level=info msg="[Probe]: test-cmd-probe probe has been Passed 😄 " ProbeType=cmdProbe ProbeInstance=PostChaos ProbeStatus=Passed ProbeName=test-cmd-probe
time="2022-01-14T15:18:29Z" level=info msg="[The End]: Updating the chaos result of process-kill experiment (EOT)"
```

Experiment run for unsuccessful cmd probe execution:
```
W0114 15:14:01.341103       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2022-01-14T15:14:01Z" level=info msg="Experiment Name: process-kill"
time="2022-01-14T15:14:01Z" level=info msg="[PreReq]: Getting the ENV for the process-kill experiment"
time="2022-01-14T15:14:03Z" level=info msg="[PreReq]: Updating the chaos result of process-kill experiment (SOT)"
time="2022-01-14T15:14:07Z" level=info msg="[Info]: The process information is as follows" Process IDs=1452
time="2022-01-14T15:14:07Z" level=info msg="[Status]: Connecting to the agent"
time="2022-01-14T15:14:08Z" level=info msg="[Status]: Verify that the target processes are running"
time="2022-01-14T15:14:10Z" level=info msg="[Probe]: The cmd probe information is as follows" Comparator="{string equal This is From GCP VM}" Source="{ false}" Run Properties="{5 2 1 0 0 false}" Mode=Edge Phase=PreChaos Name=test-cmd-probe Command="cat /home/neelanjan/example.txt"
time="2022-01-14T15:14:10Z" level=info msg="[Probe]: Executing Cmd Probe via agent"
time="2022-01-14T15:14:10Z" level=info msg="[Probe]: {Actual value: This is A Different Text}, {Expected value: This is From GCP VM}, {Operator: equal}"
time="2022-01-14T15:14:10Z" level=error msg="the test-cmd-probe cmd probe has been Failed, err: {actual value: This is A Different Text} is not equal to {expected value: This is From GCP VM}"
time="2022-01-14T15:14:12Z" level=info msg="[Probe]: Executing Cmd Probe via agent"
time="2022-01-14T15:14:13Z" level=error msg="the test-cmd-probe cmd probe has been Failed, err: {actual value: This is A Different Text} is not equal to {expected value: This is From GCP VM}"
time="2022-01-14T15:14:15Z" level=info msg="[Probe]: Executing Cmd Probe via agent"
time="2022-01-14T15:14:15Z" level=error msg="the test-cmd-probe cmd probe has been Failed, err: {actual value: This is A Different Text} is not equal to {expected value: This is From GCP VM}"
time="2022-01-14T15:14:17Z" level=info msg="[Probe]: Executing Cmd Probe via agent"
time="2022-01-14T15:14:17Z" level=error msg="the test-cmd-probe cmd probe has been Failed, err: {actual value: This is A Different Text} is not equal to {expected value: This is From GCP VM}"
time="2022-01-14T15:14:19Z" level=info msg="[Probe]: Executing Cmd Probe via agent"
time="2022-01-14T15:14:20Z" level=error msg="the test-cmd-probe cmd probe has been Failed, err: {actual value: This is A Different Text} is not equal to {expected value: This is From GCP VM}"
time="2022-01-14T15:14:22Z" level=error msg="[Probe]: test-cmd-probe probe has been Failed 😢 " ProbeStatus=Failed ProbeName=test-cmd-probe ProbeType=cmdProbe ProbeInstance=PreChaos
time="2022-01-14T15:14:22Z" level=info msg="[Info]: Target processes list: [1452]"
time="2022-01-14T15:14:22Z" level=info msg="[Chaos]: Killing [1452] processes"
time="2022-01-14T15:14:23Z" level=info msg="[Chaos]: [1452] processes killed successfully"
time="2022-01-14T15:14:25Z" level=info msg="[Wait]: Waiting for chaos interval of 30s"
time="2022-01-14T15:14:55Z" level=info msg="[Confirmation]: process-kill chaos has been injected successfully"
time="2022-01-14T15:14:57Z" level=info msg="[Probe]: The cmd probe information is as follows" Run Properties="{5 2 1 0 0 false}" Mode=Edge Phase=PostChaos Name=test-cmd-probe Command="cat /home/neelanjan/example.txt" Comparator="{string equal This is From GCP VM}" Source="{ false}"
time="2022-01-14T15:14:57Z" level=info msg="[Probe]: Executing Cmd Probe via agent"
time="2022-01-14T15:14:57Z" level=error msg="the test-cmd-probe cmd probe has been Failed, err: {actual value: This is A Different Text} is not equal to {expected value: This is From GCP VM}"
time="2022-01-14T15:14:59Z" level=info msg="[Probe]: Executing Cmd Probe via agent"
time="2022-01-14T15:14:59Z" level=error msg="the test-cmd-probe cmd probe has been Failed, err: {actual value: This is A Different Text} is not equal to {expected value: This is From GCP VM}"
time="2022-01-14T15:15:01Z" level=info msg="[Probe]: Executing Cmd Probe via agent"
time="2022-01-14T15:15:02Z" level=error msg="the test-cmd-probe cmd probe has been Failed, err: {actual value: This is A Different Text} is not equal to {expected value: This is From GCP VM}"
time="2022-01-14T15:15:04Z" level=info msg="[Probe]: Executing Cmd Probe via agent"
time="2022-01-14T15:15:04Z" level=error msg="the test-cmd-probe cmd probe has been Failed, err: {actual value: This is A Different Text} is not equal to {expected value: This is From GCP VM}"
ti [...]

2022-01-14 20:51 UTC, uditgaurav commented
Can we modify `.github/workflows` to push image with tag `m-agent`

2022-01-14 21:27 UTC, uditgaurav requested changes

2022-01-14 21:27 UTC, uditgaurav commented on chaoslib/litmus/process-kill/lib/process-kill.go
> +			log.Infof("[Chaos]: %s process killed successfully", strconv.Itoa(pid))
we can use %d or %v we don't need to change the pid type

2022-01-14 21:27 UTC, uditgaurav commented on chaoslib/litmus/process-kill/lib/process-kill.go
> +				return errors.Errorf("unintelligible feedback received from agent: %s", feedback)
for printing all error messages let's give `err:` in the msg before printing the actual error string we received.

Ex: `unintelligible feedback received from agent, err: %s`

2022-01-14 21:27 UTC, uditgaurav commented on chaoslib/litmus/process-kill/lib/process-kill.go
> +			if feedback != "ACTION_SUCCESSFUL" {
we can give a comment above, that only for the success of experiment we receive `ACTION_SUCCESSFUL ` output

2022-01-14 21:27 UTC, uditgaurav commented on contribute/developer-guide/templates/experiment.tmpl
> +			if err := probe.RunProbes(&chaosDetails, clients, &resultDetails, "PreChaos", &eventsDetails, nil);err != nil {
we are already setting up the websocketConnection variable in chaosDetails structure, do we need to pass `nil` here?

2022-01-14 21:27 UTC, uditgaurav commented on experiments/guest-os/process-kill/README.md
> +    <td> <a href="https://litmuschaos.github.io/litmus/experiments/categories/guest-os/process-kill/"> Here </a> </td>
we can update the link once we'll have it.

2022-01-14 21:27 UTC, uditgaurav commented on contribute/developer-guide/templates/experiment.tmpl
> +			if err := probe.RunProbes(&chaosDetails, clients, &resultDetails, "PostChaos", &eventsDetails, nil);err != nil {
same as above

2022-01-14 21:27 UTC, uditgaurav commented on experiments/guest-os/process-kill/experiment/process-kill.go
> +		return
We should have a post chaos check for the same. The post chaos check will check it the process is successfully killed or not

2022-01-14 21:27 UTC, uditgaurav commented on experiments/guest-os/process-kill/rbac.yaml
> +---
we can think of a better category name than `guest-os` maybe

2022-01-14 21:27 UTC, uditgaurav commented on pkg/cloud/process/process-operations.go
> +package process
Is this file of any use? We can remove it.

2022-01-14 21:27 UTC, uditgaurav commented on pkg/cloud/process/process-status.go
> +import (
it is not a cloud experiment so we can place it in a new/diff category 
`pkg/<category-name>/process-status.go`

2022-01-14 21:27 UTC, uditgaurav commented on pkg/messages/messages.go
> +	return agentError, nil
There won't be any change in agentError. We can check this logic

2022-01-14 21:27 UTC, uditgaurav commented on pkg/messages/messages.go
> +	return nil
```suggestion
	return conn.WriteJSON(Message{action, payload})
```

2022-01-14 21:27 UTC, uditgaurav commented on pkg/messages/messages.go
> +
please relook the dir structure - `pkg/<category-name>/messages.go`

2022-01-14 21:27 UTC, uditgaurav commented on pkg/guest-os/process-kill/types/types.go
> +	LIBImagePullPolicy string
do we need LIBImagePullPolicy?

2022-01-15 05:00 UTC, neelanjan00 commented on contribute/developer-guide/templates/experiment.tmpl
> +			if err := probe.RunProbes(&chaosDetails, clients, &resultDetails, "PreChaos", &eventsDetails, nil);err != nil {
I forgot to revert it here 😅

2022-01-15 05:11 UTC, neelanjan00 commented on experiments/guest-os/process-kill/experiment/process-kill.go
> +		return
I had thought of it but the issue is PIDs are assigned by the kernel to any process or daemon that needs a PID to be allocated i.e. they are recycled. It may potentially happen that upon killing a process with a particular PID, it gets immediately recycled by some other process or daemon and the experiment will fail in this case. What do you think @uditgaurav?

2022-01-15 05:13 UTC, neelanjan00 commented on experiments/guest-os/process-kill/rbac.yaml
> +---
I completely agree, we can inject fault on more than just `guest-os` here, Host OS can also be targeted and bare-metal nodes as well. I think just `os` would be a better category name. What do you think @uditgaurav ?

2022-01-15 05:13 UTC, neelanjan00 commented on pkg/cloud/process/process-status.go
> +import (
Let's think about `os` as the category?

2022-01-15 05:16 UTC, neelanjan00 commented on pkg/messages/messages.go
> +	return agentError, nil
I didn't understand, can you please explain a bit?

2022-01-15 05:24 UTC, neelanjan00 commented on pkg/guest-os/process-kill/types/types.go
> +	LIBImagePullPolicy string
Is it required for the Kubernetes part in general? If not, then we should remove it as it has no function in the core experiment logic.

2022-01-15 07:30 UTC, uditgaurav approved these changes

2022-01-15 07:31 UTC, merged