m-agent Design Refactor
litmuschaos/litmus-go pull request #489
Opened 2022-03-08 15:32 UTC by neelanjan00

**What this PR does / why we need it**:
- Gives the option to update the PORT of m-agent before installation as well as after m-agent installation
- Uses an updated message listener design for sending concurrent messages to the agent
- Adds a liveness check criteria during the experiment chaos interval 

**Which issue this PR fixes** 
m-agent#2

2022-03-14 05:10 UTC, gdsoumya requested changes

2022-03-14 05:10 UTC, gdsoumya commented on experiments/os/process-kill/experiment/process-kill.go
> +	if err := connections.CreateWebsocketConnections(chaosDetails.ExperimentName, experimentsDetails.AgentEndpoint, experimentsDetails.AuthToken, false, &chaosDetails); err != nil {
redundant experiment name data can just use chaosdetails variable directly

2022-03-14 05:10 UTC, gdsoumya commented on pkg/machine/common/messages/messages.go
> +		mutex.Lock()
Rlock and RUnlock

2022-03-14 09:30 UTC, neelanjan00 commented on build/Dockerfile
> +FROM golang:1.16 AS builder
@uditgaurav this difference was added as part of your vulnerability fix PR: https://github.com/litmuschaos/litmus-go/pull/488, can we change the version in the Dockerfile?

2022-03-14 11:00 UTC, gdsoumya approved these changes

2022-03-14 15:34 UTC, avaakash commented on experiments/os/process-kill/experiment/process-kill.go
> +	if err := process.ProcessStateCheck(chaosDetails.WebsocketConnections[0], experimentsDetails.ProcessIds); err != nil {
Why are we checking for only the 1st connection in the list?

2022-03-15 08:27 UTC, neelanjan00 commented on experiments/os/process-kill/experiment/process-kill.go
> +	if err := process.ProcessStateCheck(chaosDetails.WebsocketConnections[0], experimentsDetails.ProcessIds); err != nil {
In this particular experiment, we will have only one WebSocket connection, i.e., it will always target only one endpoint. Hence we can only use the first WebSocket connection. However, for other experiments like the cpu-stress experiment, we have multiple endpoints and connections as well, hence chaosDetails.WebsocketConnections is of type []*websocket.Conn

2022-03-16 07:02 UTC, avaakash approved these changes

2022-04-12 04:26 UTC, ksatchit approved these changes

2022-04-14 07:43 UTC, merged