GCP VM Instance Stop by Label
litmuschaos/litmus-go pull request #495
Opened 2022-03-21 15:14 UTC by neelanjan00

## What this PR does  
Adds the GCP VM Instance Stop by Label experiment

## Special notes for your reviewer
**Manual Test Cases Covered**
1. Incorrect label provided
2. Incorrect GCP project id
3. Incorrect instance zone
4. VMs not in a RUNNING state before the start of the experiment

2022-03-24 15:20 UTC, neelanjan00 commented
`gcp-vm-instance-stop` logs:
```
W0324 14:38:25.459008       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2022-03-24T14:38:25Z" level=info msg="Experiment Name: gcp-vm-instance-stop"
time="2022-03-24T14:38:25Z" level=info msg="[PreReq]: Procured the ENV for the gcp-vm-instance-stop experiment"
time="2022-03-24T14:38:27Z" level=info msg="[PreReq]: Updating the chaos result of gcp-vm-instance-stop experiment (SOT)"
time="2022-03-24T14:38:29Z" level=info msg="The instance information is as follows" Sequence=parallel Instance Names=neel-test-instance Zones=us-central1-a
time="2022-03-24T14:38:29Z" level=info msg="[Info]: The instances under chaos (IUC) are: [neel-test-instance]"
time="2022-03-24T14:38:30Z" level=info msg="[Status]: VM instance is in running state (pre-chaos)"
time="2022-03-24T14:38:30Z" level=info msg="[Info]: Target instanceID list, [neel-test-instance]"
time="2022-03-24T14:38:30Z" level=info msg="[Chaos]: Stopping neel-test-instance VM instance"
time="2022-03-24T14:38:32Z" level=info msg="Stopping VM instance:" InstanceZone=us-central1-a InstanceName=neel-test-instance
time="2022-03-24T14:38:32Z" level=info msg="[Wait]: Wait for VM instance neel-test-instance to get in stopped state"
time="2022-03-24T14:38:32Z" level=info msg="[Status]: Checking VM instance status"
time="2022-03-24T14:38:32Z" level=info msg="The neel-test-instance instance state is RUNNING"
time="2022-03-24T14:38:35Z" level=info msg="The neel-test-instance instance state is STOPPING"
time="2022-03-24T14:38:37Z" level=info msg="The neel-test-instance instance state is STOPPING"
time="2022-03-24T14:38:40Z" level=info msg="The neel-test-instance instance state is STOPPING"
time="2022-03-24T14:38:42Z" level=info msg="The neel-test-instance instance state is STOPPING"
time="2022-03-24T14:38:45Z" level=info msg="The neel-test-instance instance state is STOPPING"
time="2022-03-24T14:38:47Z" level=info msg="The neel-test-instance instance state is STOPPING"
time="2022-03-24T14:38:50Z" level=info msg="The neel-test-instance instance state is TERMINATED"
time="2022-03-24T14:38:52Z" level=info msg="[Wait]: Waiting for chaos interval of 30s"
time="2022-03-24T14:39:22Z" level=info msg="[Chaos]: Starting back neel-test-instance VM instance"
time="2022-03-24T14:39:23Z" level=info msg="Starting VM instance:" InstanceName=neel-test-instance InstanceZone=us-central1-a
time="2022-03-24T14:39:23Z" level=info msg="[Wait]: Wait for VM instance neel-test-instance to get in running state"
time="2022-03-24T14:39:23Z" level=info msg="[Status]: Checking VM instance status"
time="2022-03-24T14:39:23Z" level=info msg="The neel-test-instance instance state is TERMINATED"
time="2022-03-24T14:39:26Z" level=info msg="The neel-test-instance instance state is STAGING"
time="2022-03-24T14:39:29Z" level=info msg="The neel-test-instance instance state is STAGING"
time="2022-03-24T14:39:31Z" level=info msg="The neel-test-instance instance state is RUNNING"
time="2022-03-24T14:39:33Z" level=info msg="[Confirmation]: gcp-vm-instance-stop chaos has been injected successfully"
time="2022-03-24T14:39:33Z" level=info msg="[Info]: The instances under chaos (IUC) are: [neel-test-instance]"
time="2022-03-24T14:39:33Z" level=info msg="[Status]: Checking VM instance status"
time="2022-03-24T14:39:34Z" level=info msg="The neel-test-instance instance state is RUNNING"
time="2022-03-24T14:39:36Z" level=info msg="[Status]: VM instance is in running state (post-chaos)"
time="2022-03-24T14:39:36Z" level=info msg="[The End]: Updating the chaos result of gcp-vm-instance-stop experiment (EOT)"
```

2022-03-24 15:21 UTC, neelanjan00 commented
`gcp-vm-disk-loss` logs:
```
W0324 14:47:30.618991       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2022-03-24T14:47:30Z" level=info msg="Experiment Name: gcp-vm-disk-loss"
time="2022-03-24T14:47:30Z" level=info msg="[PreReq]: Getting the ENV for the gcp-vm-disk-loss experiment"
time="2022-03-24T14:47:32Z" level=info msg="[PreReq]: Updating the chaos result of gcp-vm-disk-loss experiment (SOT)"
time="2022-03-24T14:47:36Z" level=info msg="The volume information is as follows" Sequence=parallel Volume IDs="test-disk,test-disk-2" Zones="us-central1-a,us-central1-a"
time="2022-03-24T14:47:39Z" level=info msg="[Chaos]: Detaching the disk volume from the instance"
time="2022-03-24T14:47:40Z" level=info msg="Detaching disk having:" InstanceName=neel-test-instance Status=RUNNING Device=test-disk
time="2022-03-24T14:47:40Z" level=info msg="[Chaos]: Detaching the disk volume from the instance"
time="2022-03-24T14:47:41Z" level=info msg="Detaching disk having:" InstanceName=neel-test-instance Status=PENDING Device=test-disk-2
time="2022-03-24T14:47:41Z" level=info msg="[Wait]: Wait for disk volume detachment for volume test-disk"
time="2022-03-24T14:47:41Z" level=info msg="[Status]: Checking disk volume status for detachment"
time="2022-03-24T14:47:42Z" level=info msg="The selected disk volume is:" VolumeType=pd-balanced Status=READY InstanceName=neel-test-instance VolumeName=test-disk
time="2022-03-24T14:47:42Z" level=info msg="[Info]: The volume state is attached"
time="2022-03-24T14:47:44Z" level=info msg="[Info]: The volume state is detached"
time="2022-03-24T14:47:46Z" level=info msg="[Wait]: Wait for disk volume detachment for volume test-disk-2"
time="2022-03-24T14:47:46Z" level=info msg="[Status]: Checking disk volume status for detachment"
time="2022-03-24T14:47:47Z" level=info msg="The selected disk volume is:" Status=READY InstanceName=neel-test-instance VolumeName=test-disk-2 VolumeType=pd-balanced
time="2022-03-24T14:47:47Z" level=info msg="[Info]: The volume state is attached"
time="2022-03-24T14:47:49Z" level=info msg="[Info]: The volume state is detached"
time="2022-03-24T14:47:51Z" level=info msg="[Wait]: Waiting for the chaos interval of 30s"
time="2022-03-24T14:48:22Z" level=info msg="[Chaos]: Attaching the disk volume to the instance"
time="2022-03-24T14:48:23Z" level=info msg="Attaching disk having:" Device=test-disk InstanceName=neel-test-instance Status=RUNNING
time="2022-03-24T14:48:23Z" level=info msg="[Wait]: Wait for disk volume attachment for volume test-disk"
time="2022-03-24T14:48:23Z" level=info msg="[Status]: Checking disk volume status for attachment"
time="2022-03-24T14:48:24Z" level=info msg="[Info]: The volume state is detached"
time="2022-03-24T14:48:26Z" level=info msg="The selected disk volume is:" VolumeType=pd-balanced Status=READY InstanceName=neel-test-instance VolumeName=test-disk
time="2022-03-24T14:48:26Z" level=info msg="[Info]: The volume state is attached"
time="2022-03-24T14:48:29Z" level=info msg="[Chaos]: Attaching the disk volume to the instance"
time="2022-03-24T14:48:30Z" level=info msg="Attaching disk having:" Status=RUNNING Device=test-disk-2 InstanceName=neel-test-instance
time="2022-03-24T14:48:30Z" level=info msg="[Wait]: Wait for disk volume attachment for volume test-disk-2"
time="2022-03-24T14:48:30Z" level=info msg="[Status]: Checking disk volume status for attachment"
time="2022-03-24T14:48:31Z" level=info msg="[Info]: The volume state is detached"
time="2022-03-24T14:48:34Z" level=info msg="The selected disk volume is:" Status=READY InstanceName=neel-test-instance VolumeName=test-disk-2 VolumeType=pd-balanced
time="2022-03-24T14:48:34Z" level=info msg="[Info]: The volume state is attached"
time="2022-03-24T14:48:36Z" level=info msg="[Confirmation]: gcp-vm-disk-loss chaos has been injected successfully"
time="2022-03-24T14:48:37Z" level=info msg="[The End]: Updating the chaos result of gcp-vm-disk-loss experiment (EOT)"
```

2022-03-24 15:21 UTC, neelanjan00 commented
`gcp-vm-disk-loss-by-label` logs:
```
W0324 14:51:03.069361       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2022-03-24T14:51:03Z" level=info msg="Experiment Name: gcp-vm-disk-loss-by-label"
time="2022-03-24T14:51:03Z" level=info msg="[PreReq]: Getting the ENV for the gcp-vm-disk-loss-by-label experiment"
time="2022-03-24T14:51:05Z" level=info msg="[PreReq]: Updating the chaos result of gcp-vm-disk-loss-by-label experiment (SOT)"
time="2022-03-24T14:51:09Z" level=info msg="[Info]: The application information is as follows" Zones=us-central1-a Sequence=parallel Disk Volume Label="env:dev"
time="2022-03-24T14:51:10Z" level=info msg="[Info]: Targeting the attached disk volumes filtered from disk label" Number of attached disk volumes filtered=2
time="2022-03-24T14:51:11Z" level=info msg="[Chaos]: Detaching the disk volume from the instance"
time="2022-03-24T14:51:11Z" level=info msg="Detaching disk having:" Device=test-disk InstanceName=neel-test-instance Status=RUNNING
time="2022-03-24T14:51:11Z" level=info msg="[Wait]: Wait for disk volume detachment for volume test-disk"
time="2022-03-24T14:51:11Z" level=info msg="[Status]: Checking disk volume status for detachment"
time="2022-03-24T14:51:12Z" level=info msg="The selected disk volume is:" InstanceName=neel-test-instance VolumeName=test-disk VolumeType=pd-balanced Status=READY
time="2022-03-24T14:51:12Z" level=info msg="[Info]: The volume state is attached"
time="2022-03-24T14:51:14Z" level=info msg="The selected disk volume is:" Status=READY InstanceName=neel-test-instance VolumeName=test-disk VolumeType=pd-balanced
time="2022-03-24T14:51:14Z" level=info msg="[Info]: The volume state is attached"
time="2022-03-24T14:51:17Z" level=info msg="[Info]: The volume state is detached"
time="2022-03-24T14:51:19Z" level=info msg="[Wait]: Waiting for the chaos interval of 30s"
time="2022-03-24T14:51:50Z" level=info msg="[Chaos]: Attaching the disk volume to the instance"
time="2022-03-24T14:51:51Z" level=info msg="Attaching disk having:" InstanceName=neel-test-instance Status=RUNNING Device=test-disk
time="2022-03-24T14:51:51Z" level=info msg="[Wait]: Wait for disk volume attachment for volume test-disk"
time="2022-03-24T14:51:51Z" level=info msg="[Status]: Checking disk volume status for attachment"
time="2022-03-24T14:51:52Z" level=info msg="[Info]: The volume state is detached"
time="2022-03-24T14:51:54Z" level=info msg="The selected disk volume is:" VolumeName=test-disk VolumeType=pd-balanced Status=READY InstanceName=neel-test-instance
time="2022-03-24T14:51:54Z" level=info msg="[Info]: The volume state is attached"
time="2022-03-24T14:51:57Z" level=info msg="[The End]: Updating the chaos result of gcp-vm-disk-loss-by-label experiment (EOT)"
```

2022-04-01 05:01 UTC, neelanjan00 commented
@avaakash @Jonsy13 can you please review this PR?

2022-04-01 05:46 UTC, Jonsy13 submitted a review, later dismissed

2022-04-04 07:23 UTC, avaakash requested changes

2022-04-04 07:23 UTC, avaakash commented on pkg/cloud/gcp/vm-instance-status.go
> +			return errors.Errorf("%s vm instance is not in RUNNING state, current state: %v", instanceNamesList[i], instanceState)
```suggestion
			return errors.Errorf("%s instance is not in RUNNING state, current state: %v", instanceNamesList[i], instanceState)
```
At some places `instance` is used and some `vm instance` is used, we can use a single representation (can improve this in other experiments as well)

2022-04-04 07:23 UTC, avaakash commented on experiments/gcp/gcp-vm-instance-stop-by-label/experiment/gcp-vm-instance-stop-by-label.go
> +		msg := "AUT: Running"
Can change/remove the `AUT: Running` log as we are no longer checking for AUT or AuxApp.

2022-04-04 07:23 UTC, avaakash commented on experiments/gcp/gcp-vm-disk-loss-by-label/experiment/gcp-vm-disk-loss-by-label.go
> +		msg := "AUT: Running"
Can change/remove the `AUT: Running` log as we are no longer checking for AUT or AuxApp.

2022-04-04 07:23 UTC, avaakash commented on chaoslib/litmus/gcp-vm-instance-stop/lib/gcp-vm-instance-stop.go
> +				log.Infof("[Chaos]: Stopping %s VM instance", instanceNamesList[i])
At some places `instance` is used and some `vm instance` is used, we can use a single representation (can improve this in other experiments as well)

2022-04-05 04:46 UTC, neelanjan00 commented on experiments/gcp/gcp-vm-instance-stop-by-label/experiment/gcp-vm-instance-stop-by-label.go
> +		msg := "AUT: Running"
I have this marked as a common item for all the experiments, will raise a separate PR.

2022-04-05 04:47 UTC, neelanjan00 commented on chaoslib/litmus/gcp-vm-instance-stop/lib/gcp-vm-instance-stop.go
> +				log.Infof("[Chaos]: Stopping %s VM instance", instanceNamesList[i])
I have changed instances to vm instances in all places now.

2022-04-05 04:53 UTC, neelanjan00 commented on pkg/cloud/gcp/vm-operations.go
>  	log.InfoWithValues("Stopping VM instance:", logrus.Fields{
Although the process of stopping the VM instances has started at this point in execution yet they are not in a stopped state. Hence, `Stopping VM instance` sounds correct to me, as it is in present continuous tense and infers that (the experiment is) Stopping (the following) VM instance at the moment.

2022-04-05 07:03 UTC, avaakash submitted a review, later dismissed

2022-04-11 10:58 UTC, neelanjan00 commented
@Adarshkumar14 can you please review this PR?

2022-04-11 19:46 UTC, Adarshkumar14 approved these changes

2022-04-13 09:34 UTC, uditgaurav commented on chaoslib/litmus/gcp-vm-instance-stop-by-label/lib/gcp-vm-instance-stop-by-label.go
> +				log.Infof("[Chaos]: Stopping %s desired VM instance", instanceNamesList[i])
```suggestion
				log.Infof("[Chaos]: Stopping %s VM instance", instanceNamesList[i])
```

2022-04-13 09:34 UTC, uditgaurav commented on chaoslib/litmus/gcp-vm-instance-stop-by-label/lib/gcp-vm-instance-stop-by-label.go
> +			case "disable":
Can we give preference to enable over disable? If enable do this (...) or else the default case will run.

2022-04-13 09:34 UTC, uditgaurav commented on chaoslib/litmus/gcp-vm-instance-stop/lib/gcp-vm-instance-stop.go
> +				case "disable":
same as above enable over disable

2022-04-13 09:34 UTC, uditgaurav commented on experiments/gcp/gcp-vm-disk-loss-by-label/experiment/gcp-vm-disk-loss-by-label.go
> +		failStep := "[pre-chaos]: Failed to update the chaos result of pod-delete experiment (SOT), err: " + err.Error()
```suggestion
		failStep := "[pre-chaos]: Failed to update the chaos result of gcp-vm-disk-loss-by-label experiment (SOT), err: " + err.Error()
```

2022-04-13 09:34 UTC, uditgaurav commented on experiments/gcp/gcp-vm-disk-loss-by-label/experiment/gcp-vm-disk-loss-by-label.go
> +	log.InfoWithValues("[Info]: The application information is as follows", logrus.Fields{
```suggestion
	log.InfoWithValues("[Info]: The disk information is as follows", logrus.Fields{
```

2022-04-13 09:34 UTC, uditgaurav commented on experiments/gcp/gcp-vm-instance-stop-by-label/experiment/gcp-vm-instance-stop-by-label.go
> +		failStep := "[pre-chaos]: Failed to update the chaos result of pod-delete experiment (SOT), err: " + err.Error()
```suggestion
		failStep := "[pre-chaos]: Failed to update the chaos result of gcp-vm-instance-stop-by-label experiment (SOT), err: " + err.Error()
```

we can make the experiment name as variable as well.

2022-04-13 09:34 UTC, uditgaurav commented on experiments/gcp/gcp-vm-instance-stop-by-label/test/test.yml
> +
not reqiured, pls check other envs as well

2022-04-13 09:34 UTC, uditgaurav commented on pkg/cloud/gcp/disk-operations.go
> +	return "", errors.Errorf("%s disk not attached to any VM instance", diskName)
```suggestion
	return "", errors.Errorf("%s disk is not attached to any VM instance", diskName)
```

2022-04-13 09:34 UTC, uditgaurav commented on pkg/cloud/gcp/disk-operations.go
> +	log.InfoWithValues("[Info]: Targeting the attached disk volumes filtered from disk label", logrus.Fields{
can we also print the name as well along with the label?

2022-04-13 09:34 UTC, uditgaurav commented on pkg/cloud/gcp/disk-volume-status.go
> +			}
we can put this just after the `switch stage` & before `case "pre-chaos"` and append when the case is pre-chaos. Then we don't need a default case.

2022-04-13 09:34 UTC, uditgaurav commented on pkg/cloud/gcp/vm-instance-status.go
> +		return errors.Errorf("the number of vm instance names and the number of regions is not equal")
```suggestion
		return errors.Errorf("the number of vm instance names and the number of regions are not equal")
```

2022-04-13 09:34 UTC, uditgaurav commented on pkg/gcp/gcp-vm-instance-stop/types/types.go
> +	LIBImagePullPolicy       string
Are we using LIBImagePullPolicy as there is no helper?

2022-04-15 06:45 UTC, neelanjan00 commented on chaoslib/litmus/gcp-vm-disk-loss-by-label/lib/gcp-vm-disk-loss-by-label.go
> +	}
IMO there's not a requirement for it, can you please elaborate how it will help?

2022-04-15 06:48 UTC, neelanjan00 commented on chaoslib/litmus/gcp-vm-disk-loss-by-label/lib/gcp-vm-disk-loss-by-label.go
> +				}
The above code segment is analogical to the ebs-loss-by-tag experiment; we can take it as a common task in both.

2022-04-15 07:24 UTC, neelanjan00 commented on pkg/gcp/gcp-vm-instance-stop/types/types.go
> +	LIBImagePullPolicy       string
No, we are not using it. This needs to be corrected in kube-aws experiments as well.

2022-04-26 10:20 UTC, uditgaurav commented
Looks Good! 
Can we also try this experiment on a scale with 10-15 disks in both modes (serial and parallel)?

2022-04-26 10:20 UTC, uditgaurav submitted a review, later dismissed

2022-04-28 07:57 UTC, neelanjan00 commented
> Looks Good! Can we also try this experiment on a scale with 10-15 disks in both modes (serial and parallel)?

Experiment run using label selector for 15 disks:
[parallel-logs.txt](https://github.com/litmuschaos/litmus-go/files/8580671/parallel-logs.txt)
[serial-logs.txt](https://github.com/litmuschaos/litmus-go/files/8580672/serial-logs.txt)

2022-04-28 09:48 UTC, uditgaurav approved these changes

2022-04-28 09:51 UTC, avaakash approved these changes

2022-04-28 10:05 UTC, Jonsy13 requested changes

2022-04-28 10:05 UTC, Jonsy13 commented on chaoslib/litmus/gcp-vm-instance-stop-by-label/lib/gcp-vm-instance-stop-by-label.go
> +			log.Infof("[Info]: Target instanceID list, %v", instanceNamesList)
It should be `Target Instances list` as it is showing names of instances not IDs.

2022-04-28 10:21 UTC, uditgaurav approved these changes

2022-04-28 10:22 UTC, Jonsy13 approved these changes

2022-04-28 10:26 UTC, avaakash approved these changes

2022-04-28 12:24 UTC, merged