Fix(network-chaos): Add network interface as tunable in pod-level-network experiments
litmuschaos/litmus-go pull request #499
Opened 2022-03-30 08:26 UTC by uditgaurav

Signed-off-by: uditgaurav <udit@chaosnative.com>

**What this PR does / why we need it**:

- In pod level network experiments the recovery command supports the other network interfaces as well than eth0 and can be passed via `NETEWORK_INTERFACE` env.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Checklist:**
-   [ ] Fixes #<issue number>
-   [ ] PR messages has document related information
-   [ ] Labelled this PR & related issue with `breaking-changes` tag
-   [ ] PR messages has breaking changes related information
-   [ ] Labelled this PR & related issue with `requires-upgrade` tag
-   [ ] PR messages has upgrade related information
-   [ ] Commit has unit tests
-   [ ] Commit has integration tests
-   [ ] E2E run Required for the changes

2022-04-13 12:03 UTC, avaakash requested changes

2022-04-13 12:03 UTC, avaakash commented on .github/workflows/push.yml
> +      - network_chaos_cleanup_command_fix
Can we revert this change.

2022-04-13 12:03 UTC, avaakash commented on .github/workflows/push.yml
> +          tags: uditgaurav/go-runner:501
Can we revert this change.

2022-04-14 07:44 UTC, ksatchit approved these changes

2022-04-14 07:45 UTC, merged