Added Active Node Count Check using AWS APIs
litmuschaos/litmus-go pull request #500
Opened 2022-03-30 09:10 UTC by avaakash

Signed-off-by: Akash Shrivastava <akash@chaosnative.com>

**What this PR does / why we need it**:
This PR changes the current functionality of checking the active node count in AWS EC2 terminate experiment from using the K8s APIs to using the AWS APIs.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Checklist:**
-   [ ] Fixes #<issue number>
-   [ ] PR messages has document related information
-   [ ] Labelled this PR & related issue with `breaking-changes` tag
-   [ ] PR messages has breaking changes related information
-   [ ] Labelled this PR & related issue with `requires-upgrade` tag
-   [ ] PR messages has upgrade related information
-   [ ] Commit has unit tests
-   [ ] Commit has integration tests
-   [ ] E2E run Required for the changes

2022-04-01 04:32 UTC, neelanjan00 commented
@avaakash can you please add the logs of the experiment (with ManagedNodegroup enabled)?

2022-04-01 04:56 UTC, neelanjan00 requested changes

2022-04-01 04:56 UTC, neelanjan00 commented on experiments/kube-aws/ec2-terminate-by-id/experiment/ec2-terminate-by-id.go
> +	//PRE-CHAOS NODE STATUS CHECK
Can we add a log here to specify that the active node count check (pre-chaos) is being performed? Same for post chaos as well.

2022-04-01 04:56 UTC, neelanjan00 commented on experiments/kube-aws/ec2-terminate-by-tag/experiment/ec2-terminate-tag.go
>  	if err = status.AUTStatusCheck(experimentsDetails.AppNS, experimentsDetails.AppLabel, experimentsDetails.TargetContainer, experimentsDetails.Timeout, experimentsDetails.Delay, clients, &chaosDetails
We are supposed to remove all the AUT Checks and Auxiliary AUT checks as we will be changing the experiment RBAC scope to Namespace.

2022-04-01 04:56 UTC, neelanjan00 commented on pkg/cloud/aws/ec2/ec2-instance-status.go
> +	}
This condition check appears to be redundant as it is already being performed in `PreChaosNodeCountCheck` function. Can you please check?

2022-04-01 04:56 UTC, neelanjan00 commented on pkg/cloud/aws/ec2/ec2-instance-status.go
> +}
```suggestion
func findActiveNodeCount(autoScalingGroupName, region string, nodeList []*autoscaling.InstanceDetails) int {

	nodeCount := 0

	for _, id := range findInstancesInAutoScalingGroup(autoScalingGroupName, nodeList) {
		if instanceState, err := GetEC2InstanceStatus(id, region); err == nil && instanceState == "running" {
			nodeCount += 1
		}
	}
	
	return nodeCount
}
```

2022-04-01 05:00 UTC, neelanjan00 commented on pkg/cloud/aws/ec2/ec2-instance-status.go
> +		if err == nil && instanceState == "running" {
Is there any specific reason that we're not returning the `err` here if it is not nil?

2022-04-04 07:44 UTC, avaakash commented on experiments/kube-aws/ec2-terminate-by-tag/experiment/ec2-terminate-tag.go
>  	if err = status.AUTStatusCheck(experimentsDetails.AppNS, experimentsDetails.AppLabel, experimentsDetails.TargetContainer, experimentsDetails.Timeout, experimentsDetails.Delay, clients, &chaosDetails
As discussed with @ksatchit , we will be taking this change for all non-K8s experiments in a separate PR.

2022-04-04 07:47 UTC, avaakash commented on pkg/cloud/aws/ec2/ec2-instance-status.go
> +		if err == nil && instanceState == "running" {
Since this is a check to count the active nodes, an error message in getting the instance status can be assumed to mean that instance is not available and hence not counted as active node.

2022-04-04 07:51 UTC, avaakash commented on pkg/cloud/aws/ec2/ec2-instance-status.go
> +	}
Have added this check as a sanity here as well, so if in future additions/improvements affects the `PreChaosNodeCountCheck` function or manipulates the `autoScalingGroupName` variable in any sense, so this check in the function will alarm it in the testing that the `autoScalingGroupName` is not being provided properly.

2022-04-04 09:02 UTC, avaakash commented
### Experiment Logs
```
INFO[2022-04-04T14:26:01+05:30] Experiment Name: ec2-terminate-by-id         
INFO[2022-04-04T14:26:01+05:30] [PreReq]: Getting the ENV for the ec2-terminate-by-id experiment 
INFO[2022-04-04T14:26:01+05:30] [PreReq]: Updating the chaos result of ec2-terminate-by-id experiment (SOT) 
INFO[2022-04-04T14:26:05+05:30] The instance information is as follows        Chaos Namespace=litmus Instance ID="i-091ad52cb18b8dc03,i-072f97d9e7b37767c" Sequence=parallel Chaos Duration=30
INFO[2022-04-04T14:26:05+05:30] [Status]: Verify that the AUT (Application Under Test) is running (pre-chaos) 
INFO[2022-04-04T14:26:05+05:30] [Status]: No appLabels provided, skipping the application status checks 
INFO[2022-04-04T14:26:05+05:30] [Status]: Verify that the aws ec2 instances are in running state (pre-chaos) 
INFO[2022-04-04T14:26:05+05:30] [Info]: The instances under chaos(IUC) are: [i-091ad52cb18b8dc03 i-072f97d9e7b37767c] 
INFO[2022-04-04T14:26:07+05:30] [Status]: EC2 instance is in running state   
INFO[2022-04-04T14:26:07+05:30] [Status]: Counting number of active nodes in the node group (pre-chaos) 
INFO[2022-04-04T14:26:09+05:30] [Info]: Pre-Chaos Active Node Count: 3       
INFO[2022-04-04T14:26:09+05:30] [Info]: Target instanceID list, [i-091ad52cb18b8dc03 i-072f97d9e7b37767c] 
INFO[2022-04-04T14:26:09+05:30] [Chaos]: Stopping the desired EC2 instance   
INFO[2022-04-04T14:26:10+05:30] Stopping ec2 instance:                        InstanceId=i-091ad52cb18b8dc03 CurrentState=stopping PreviousState=running
INFO[2022-04-04T14:26:10+05:30] [Chaos]: Stopping the desired EC2 instance   
INFO[2022-04-04T14:26:10+05:30] Stopping ec2 instance:                        CurrentState=stopping PreviousState=running InstanceId=i-072f97d9e7b37767c
INFO[2022-04-04T14:26:10+05:30] [Wait]: Wait for EC2 instance 'i-091ad52cb18b8dc03' to get in stopped state 
INFO[2022-04-04T14:26:10+05:30] [Status]: Checking EC2 instance status       
INFO[2022-04-04T14:26:11+05:30] The instance state is stopping               
INFO[2022-04-04T14:26:13+05:30] The instance state is stopping                             
INFO[2022-04-04T14:26:29+05:30] The instance state is stopping               
INFO[2022-04-04T14:26:31+05:30] The instance state is shutting-down          
INFO[2022-04-04T14:26:34+05:30] The instance state is shutting-down          
INFO[2022-04-04T14:26:36+05:30] The instance state is shutting-down          
INFO[2022-04-04T14:26:38+05:30] The instance state is shutting-down          
INFO[2022-04-04T14:26:41+05:30] The instance state is terminated             
INFO[2022-04-04T14:26:43+05:30] [Wait]: Wait for EC2 instance 'i-072f97d9e7b37767c' to get in stopped state 
INFO[2022-04-04T14:26:43+05:30] [Status]: Checking EC2 instance status       
INFO[2022-04-04T14:26:43+05:30] The instance state is stopped                
INFO[2022-04-04T14:26:46+05:30] The instance state is stopped               
INFO[2022-04-04T14:28:23+05:30] The instance state is stopped                
INFO[2022-04-04T14:28:25+05:30] The instance state is stopped                
INFO[2022-04-04T14:28:27+05:30] The instance state is stopped                
INFO[2022-04-04T14:28:30+05:30] The instance state is shutting-down          
INFO[2022-04-04T14:28:32+05:30] The instance state is shutting-down          
INFO[2022-04-04T14:28:34+05:30] The instance state is terminated             
INFO[2022-04-04T14:28:36+05:30] [Wait]: Waiting for chaos interval of 30s    
INFO[2022-04-04T14:29:06+05:30] [Confirmation]: ec2-terminate-by-id chaos has been injected successfully 
INFO[2022-04-04T14:29:06+05:30] [Status]: Counting and verifying number of active nodes in the node group (post-chaos) 
INFO[2022-04-04T14:29:09+05:30] [Info]: Post-Chaos Active Node Count: 3      
INFO[2022-04-04T14:29:09+05:30] [Status]: Verify that the AUT (Application Under Test) is running (post-chaos) 
INFO[2022-04-04T14:29:09+05:30] [Status]: No appLabels provided, skipping the application status checks 
INFO[2022-04-04T14:29:09+05:30] [The End]: Updating the chaos result of ec2-terminate-by-id experiment (EOT)
```

2022-04-05 07:25 UTC, neelanjan00 commented on pkg/cloud/aws/ec2/ec2-instance-status.go
> +		if err == nil && instanceState == "running" {
In the `GetEC2InstanceStatus` function, we also have the was ec2 SDK function call for `DescribeInstances`, if an error is generated in that function's calling, then we should include that in the error message. Therefore, it will be better to append the error string and return it if not nil.

2022-04-06 06:01 UTC, neelanjan00 commented
fixes #506

2022-04-07 04:13 UTC, avaakash commented on pkg/cloud/aws/ec2/ec2-instance-status.go
> +		if err == nil && instanceState == "running" {
Even in a condition when the instance status fails for any of the instance, it will not increment the node count and the experiment will fail in the node count check step. So anyhow the experiment will fail. Hence adding a check here would just be another addition that wouldn't add much benefit. As for logging the error, we can add a log here stating why the ec2 instance status failed.

2022-04-12 06:16 UTC, neelanjan00 commented on pkg/cloud/aws/ec2/ec2-instance-status.go
> +		if err == nil && instanceState == "running" {
CC: @uditgaurav @ksatchit

2022-04-26 10:42 UTC, uditgaurav submitted a review, later dismissed

2022-04-26 10:51 UTC, uditgaurav commented on pkg/cloud/aws/ec2/ec2-instance-status.go
> +		if err == nil && instanceState == "running" {
IMO we can add a log for the error msg received and the failure can occur with the node count validation.

2022-04-26 10:52 UTC, uditgaurav commented
Looks Good, one minor [comment](https://github.com/litmuschaos/litmus-go/pull/500#discussion_r858570405).

2022-04-26 11:37 UTC, neelanjan00 approved these changes

2022-04-28 10:19 UTC, Jonsy13 commented on pkg/cloud/aws/ec2/ec2-instance-status.go
> +func PreChaosNodeCountCheck(instanceIDList []string, region string) (int, string, error) {
Let's add checks for nodeCount less than expected as discussed.

2022-04-28 15:07 UTC, neelanjan00 approved these changes

2022-05-10 10:13 UTC, uditgaurav approved these changes

2022-05-10 10:17 UTC, avaakash commented on pkg/cloud/aws/ec2/ec2-instance-status.go
> +		if err == nil && instanceState == "running" {
Added log stating failure of instance with error message and instance id.

2022-05-10 10:18 UTC, merged