Added experiment and lib for spring-boot
litmuschaos/litmus-go pull request #511
Opened 2022-04-28 13:42 UTC by cazeaux

Signed-off-by: Stéphane Cazeaux <stephane.cazeaux@orange.com>

**What this PR does / why we need it**:

This PR proposes a new experiment leveraging the [Chaos Monkey for Spring Boot](https://codecentric.github.io/chaos-monkey-spring-boot/) fault injection (application level fault injection).
It enables to inject configurable assauts to Spring Boot applications, using the k8s api to select target pods.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes litmuschaos/litmus#3538

**Special notes for your reviewer**:

**Checklist:**
-   [ ] Fixes litmuschaos/litmus#3538
-   [ ] PR messages has document related information
-   [ ] Labelled this PR & related issue with `breaking-changes` tag
-   [ ] PR messages has breaking changes related information
-   [ ] Labelled this PR & related issue with `requires-upgrade` tag
-   [ ] PR messages has upgrade related information
-   [ ] Commit has unit tests
-   [ ] Commit has integration tests
-   [ ] E2E run Required for the changes

2022-04-29 07:47 UTC, neelanjan00 commented
Hi @cazeaux , thank you so much for this PR! This is really great!

2022-05-25 05:55 UTC, neelanjan00 requested changes

2022-05-25 05:55 UTC, neelanjan00 commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +				endTime = time.After(timeDelay)
Can we initialize this statement outside the loop?

2022-05-25 05:55 UTC, neelanjan00 commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +			os.Exit(1)
These steps will be executed by the goroutine `AbortWatcher` which you have added in `experiment/spring-boot-chaos.go`, line number 70. Hence we can remove it. You need to instead add use the `SetTargets` function to set the target details in `chaosdetails` struct with the reverted `chaosStatus`.

2022-05-25 05:55 UTC, neelanjan00 commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +		endTime = time.After(timeDelay)
Can we initialize this statement outside the loop?

2022-05-25 05:55 UTC, neelanjan00 commented on experiments/spring-boot/rbac.yaml
> +kind: ClusterRole
Are we targetting any cluster-scoped resources? If not, we should rather use `Role` instead of `ClusterRole`

2022-05-25 05:55 UTC, neelanjan00 commented on experiments/spring-boot/spring-boot-chaos/experiment/spring-boot-chaos.go
> +		_ = events.GenerateEvents(&eventsDetails, clients, &chaosDetails, "ChaosEngine")
```suggestion
		events.GenerateEvents(&eventsDetails, clients, &chaosDetails, "ChaosEngine")
```

2022-05-25 05:56 UTC, neelanjan00 commented
Hi @cazeaux, can you please add the experiment execution logs in the comments?

2022-05-25 10:48 UTC, cazeaux commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +					os.Exit(1)
If I understand correctly, I must still keep the lines 237 to 239 and add the following lines after 239:
```go
common.SetTargets(pod.Name, "reverted", "pod", chaosDetails)
```

Correct ?

2022-05-25 16:23 UTC, cazeaux reviewed
Thank you for your detailed review, really appreciated.
I have taken into account all of them expect the `_ = ` thing because it was to avoid complaints from linter.

2022-05-25 16:23 UTC, cazeaux commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +func CheckChaosMonkey(experimentsDetails *experimentTypes.ExperimentDetails) (bool, error) {
Ok, I will do it this way

2022-05-25 16:23 UTC, cazeaux commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +func enableChaosMonkey(experimentsDetails *experimentTypes.ExperimentDetails, pod corev1.Pod) error {
Ok

2022-05-25 16:23 UTC, cazeaux commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +func setChaosMonkeyWatchers(experimentsDetails *experimentTypes.ExperimentDetails, pod corev1.Pod) error {
ok

2022-05-25 16:23 UTC, cazeaux commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +func setChaosMonkeyAssault(experimentsDetails *experimentTypes.ExperimentDetails, pod corev1.Pod) error {
ok

2022-05-25 16:23 UTC, cazeaux commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +func disableChaosMonkey(experimentsDetails *experimentTypes.ExperimentDetails, pod corev1.Pod) error {
ok

2022-05-25 16:23 UTC, cazeaux commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +	signChan := make(chan os.Signal, 1)
Indeed, I took this from another lib as example, but it is better to use signChan only.

2022-05-25 16:23 UTC, cazeaux commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +				log.Errorf("[Chaos]: Failed to set watchers, err: %v ", err)
You're right, I add the missing return

2022-05-25 16:23 UTC, cazeaux commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +				endTime = time.After(timeDelay)
Yes it is better that way.

2022-05-25 16:23 UTC, cazeaux commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +		endTime = time.After(timeDelay)
Yes

2022-05-25 16:23 UTC, cazeaux commented on experiments/spring-boot/rbac.yaml
> +kind: ClusterRole
You're right, i have changed to `Role`.

2022-05-25 16:23 UTC, cazeaux commented on experiments/spring-boot/spring-boot-chaos/experiment/spring-boot-chaos.go
> +		_ = events.GenerateEvents(&eventsDetails, clients, &chaosDetails, "ChaosEngine")
Actually I have done this to avoid complaints from linter. Is that a problem ?

2022-05-26 21:19 UTC, avaakash requested changes

2022-05-26 21:19 UTC, avaakash commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +	log.Infof("[Check]: Enabling Chaos Monkey on pod: %v", pod.Name)
```suggestion
	log.Infof("[Chaos]: Enabling Chaos Monkey on pod: %v", pod.Name)
```
Since this step is a part of the chaos injection process, can we make these changes at other places as well?

2022-05-26 21:19 UTC, avaakash commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +				"Target Pod": pod.Name,
Can we add parameters related to the chaos as well here in the logs? Eg: type of assault, related values. I guess there are a lot of chaos values, so if it is not possible to log all, we can have just a few common to all ones.

2022-05-26 21:19 UTC, avaakash commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +					common.SetTargets(pod.Name, "reverted", "pod", chaosDetails)
Even in case, the revert fails, the pod will be annotated as reverted, we can exit if the revert fails without annotating the pod.

2022-05-26 21:19 UTC, avaakash commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +				"Target Pod": pod.Name,
Can we add parameters related to the chaos as well here in the logs? Eg: type of assault, related values. I guess there are a lot of chaos values, so if it is not possible to log all, we can have just a few common to all ones.

2022-05-26 21:19 UTC, avaakash commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +						log.Errorf("Error in disable chaos monkey, err: %v", err)
```suggestion
						log.Errorf("Error in disabling chaos monkey, err: %v", err)
```
Can you edit this at other places as well?

2022-05-26 21:19 UTC, avaakash commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +			if err := disableChaosMonkey(experimentsDetails.ChaosMonkeyPort, experimentsDetails.ChaosMonkeyPath, pod); err != nil {
We also need to annotate the pods as `reverted` during normal execution flow. Can you add the logic here?

2022-05-26 21:19 UTC, avaakash commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +				return err
```suggestion
				return errors.Errorf("[Chaos]: Failed to set watchers, err: %v ", 
```
The error will cascade from bottom to top, so it is better to return the error rather than logging and returning separately. This is used throughout litmus-go, so we can follow this here and at other places.

2022-05-30 09:57 UTC, cazeaux commented
> can you please add the experiment execution logs

@neelanjan00 not sure to understand. You want that I put an execution logs here in the github comments ?

2022-05-30 09:59 UTC, neelanjan00 commented
> > can you please add the experiment execution logs
> 
> @neelanjan00 not sure to understand. You want that I put an execution logs here in the github comments ?

Yes @cazeaux , essentially the logs from the experiment pod that you are getting upon executing the experiment. I suppose you have tested it, right?

2022-05-30 10:01 UTC, cazeaux commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +	var err error
I have reverted this because I can't use concise assignement in the if due to the fact that `experimentsDetails.TargetPodList` is already declared.

2022-05-30 10:04 UTC, cazeaux commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +		}
I have reverted this as concise code doesn't work here because i need `resp` outside the scope of the if statement

2022-05-30 10:05 UTC, cazeaux commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +	// Deleting the application pod
ok

2022-05-30 10:11 UTC, cazeaux commented on experiments/spring-boot/spring-boot-chaos/experiment/spring-boot-chaos.go
> +	if _, err := litmusLIB.CheckChaosMonkey(experimentsDetails.ChaosMonkeyPort, experimentsDetails.ChaosMonkeyPath, experimentsDetails.TargetPodList); err != nil {
If chaos monkey is not present, it means that there is a mismatch between pod selector and possibility to apply chaos, so we can go to unexpected experiment. Thus I am in favor of aborting it.
But your point is good and we should fail only after checking all pods.

2022-05-30 10:47 UTC, cazeaux commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +				"Target Pod": pod.Name,
Good idea, I add a log directly in `PrepareChaos` with the activated assaults. There are too many other parameters to be logged.

2022-05-30 10:47 UTC, cazeaux commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +					common.SetTargets(pod.Name, "reverted", "pod", chaosDetails)
ok

2022-05-30 10:47 UTC, cazeaux commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +				"Target Pod": pod.Name,
Added in `PrepareChaos`

2022-05-30 10:50 UTC, cazeaux commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +			if err := disableChaosMonkey(experimentsDetails.ChaosMonkeyPort, experimentsDetails.ChaosMonkeyPath, pod); err != nil {
ok

2022-05-30 13:39 UTC, cazeaux commented
> > > can you please add the experiment execution logs
> > 
> > 
> > @neelanjan00 not sure to understand. You want that I put an execution logs here in the github comments ?
> 
> Yes @cazeaux , essentially the logs from the experiment pod that you are getting upon executing the experiment. I suppose you have tested it, right?

No problem, below the logs with the last modification based on the review:

```
INFO[2022-05-30T13:37:46Z] Experiment Name: spring-boot-chaos
INFO[2022-05-30T13:37:46Z] [PreReq]: Getting the ENV for the spring-boot-chaos experiment
INFO[2022-05-30T13:37:46Z] [PreReq]: Updating the chaos result of spring-boot-chaos experiment (SOT)
INFO[2022-05-30T13:37:48Z] [Info]: The application information is as follows  Chaos Duration=20 Namespace=podtato Label="app=spring-boot-demo"
INFO[2022-05-30T13:37:48Z] [PreCheck]: Geting targeted pods list
INFO[2022-05-30T13:37:48Z] [Chaos]:Number of pods targeted: 1
INFO[2022-05-30T13:37:48Z] [PreCheck]: Target pods list for chaos, [spring-boot-demo-84fc785847-rjgc7]
INFO[2022-05-30T13:37:48Z] [PreCheck]: Checking for ChaosMonkey endpoint in target pods
INFO[2022-05-30T13:37:48Z] [Check]: Checking pod: spring-boot-demo-84fc785847-rjgc7 (endpoint: http://10.244.0.26:8080/actuator/chaosmonkey)
INFO[2022-05-30T13:37:48Z] [Status]: Verify that the AUT (Application Under Test) is running (pre-chaos)
INFO[2022-05-30T13:37:48Z] [Status]: Checking whether application containers are in ready state
INFO[2022-05-30T13:37:50Z] [Status]: The Container status are as follows  container=springboot Pod=spring-boot-demo-84fc785847-rjgc7 Readiness=true
INFO[2022-05-30T13:37:52Z] [Status]: Checking whether application pods are in running state
INFO[2022-05-30T13:37:53Z] [Status]: The status of Pods are as follows   Pod=spring-boot-demo-84fc785847-rjgc7 Status=Running
INFO[2022-05-30T13:37:55Z] [Info]: Chaos monkeys watchers will be injected to the target pods as follows  Component=false Repository=false Controller=false RestController=true WebClient=false Service=false
INFO[2022-05-30T13:37:55Z] [Info]: Chaos monkeys assaults will be injected to the target pods as follows  CPU Assault=false Memory Assault=false Kill App Assault=false Latency Assault=true Exception Assault=false
INFO[2022-05-30T13:37:55Z] [Chaos]: Injecting on target pod              Target Pod=spring-boot-demo-84fc785847-rjgc7
INFO[2022-05-30T13:37:55Z] [Chaos]: Setting Chaos Monkey watchers on pod: spring-boot-demo-84fc785847-rjgc7
INFO[2022-05-30T13:37:55Z] [Chaos]: Setting Chaos Monkey assault on pod: spring-boot-demo-84fc785847-rjgc7
INFO[2022-05-30T13:37:55Z] [Chaos]: Activating Chaos Monkey assault on pod: spring-boot-demo-84fc785847-rjgc7
INFO[2022-05-30T13:37:55Z] [Chaos]: Enabling Chaos Monkey on pod: spring-boot-demo-84fc785847-rjgc7
INFO[2022-05-30T13:37:55Z] [Chaos]: Waiting for: 20s
INFO[2022-05-30T13:38:15Z] [Chaos]: Time is up for experiment: spring-boot-chaos
INFO[2022-05-30T13:38:15Z] [Chaos]: disabling chaos monkey on pods spring-boot-demo-84fc785847-rjgc7
INFO[2022-05-30T13:38:15Z] [Status]: Verify that the AUT (Application Under Test) is running (post-chaos)
INFO[2022-05-30T13:38:15Z] [Status]: Checking whether application containers are in ready state
INFO[2022-05-30T13:38:15Z] [Status]: The Container status are as follows  Readiness=true container=springboot Pod=spring-boot-demo-84fc785847-rjgc7
INFO[2022-05-30T13:38:17Z] [Status]: Checking whether application pods are in running state
INFO[2022-05-30T13:38:17Z] [Status]: The status of Pods are as follows   Pod=spring-boot-demo-84fc785847-rjgc7 Status=Running
INFO[2022-05-30T13:38:19Z] [The End]: Updating the chaos result of spring-boot-chaos experiment (EOT)
```

2022-05-30 13:57 UTC, cazeaux reviewed
All comments have been resolved

2022-05-31 14:35 UTC, avaakash commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +		if resp.StatusCode != 200 {
In case of error `Get` will return `nil` for `resp`, so this statement will throw a runtime error. You can return the error directly rather than flagging it. Or you can use the `hasErrors` flag in this statement as well.

2022-05-31 14:46 UTC, avaakash commented on experiments/spring-boot/spring-boot-chaos/experiment/spring-boot-chaos.go
> +	if _, err := litmusLIB.CheckChaosMonkey(experimentsDetails.ChaosMonkeyPort, experimentsDetails.ChaosMonkeyPath, experimentsDetails.TargetPodList); err != nil {
If you want to abort the experiment, you can return an error here and update the chaosresult as we are doing in the code above.

2022-05-31 15:09 UTC, cazeaux commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +		if resp.StatusCode != 200 {
Damn you're right !
I will go to the `continue` option.

2022-06-03 09:46 UTC, avaakash commented on experiments/spring-boot/spring-boot-chaos/experiment/spring-boot-chaos.go
> +	if _, err := litmusLIB.CheckChaosMonkey(experimentsDetails.ChaosMonkeyPort, experimentsDetails.ChaosMonkeyPath, experimentsDetails.TargetPodList); err != nil {
We also need to add the failStep and update chaosresult when we are failing the experiment
```
failStep := "[pre-chaos]: Some target pods don't have the chaos monkey endpoint, err: " + err.Error()
types.SetEngineEventAttributes(&eventsDetails, types.PreChaosCheck, "ChaosMonkey: Not Found", "Warning", &chaosDetails)
_ = events.GenerateEvents(&eventsDetails, clients, &chaosDetails, "ChaosEngine")
result.RecordAfterFailure(&chaosDetails, &resultDetails, failStep, clients, &eventsDetails)
```

2022-06-07 08:06 UTC, cazeaux commented on experiments/spring-boot/spring-boot-chaos/experiment/spring-boot-chaos.go
> +	if _, err := litmusLIB.CheckChaosMonkey(experimentsDetails.ChaosMonkeyPort, experimentsDetails.ChaosMonkeyPath, experimentsDetails.TargetPodList); err != nil {
Indeed, missed that, sorry. I have added this in last commit.

2022-06-08 06:48 UTC, avaakash approved these changes
LGTM! @uditgaurav can you take a look.

2022-06-21 13:09 UTC, neelanjan00 submitted a review, later dismissed

2022-06-21 13:12 UTC, neelanjan00 commented
Hi @cazeaux, the Build CI pipeline is failing (pre-checks), there's something being flagged by Go linter. Can you please fix it?

2022-07-01 07:42 UTC, cazeaux commented
Hello.

What are the last required actions/verifications/approvements before this PR can be merged ? Any action expected from me ?

2022-09-06 03:44 UTC, neelanjan00 commented
> Hello @neelanjan00
> 
> Any news on the possibility to merge this PR ? I have rebased to keep it up to date.

Hi @cazeaux, my sincere apologies for not being able to focus on this earlier. I and @ispeakc0de will take this up before the next release. We'd reach out through the Kubernetes Slack channel as we'd like to schedule a meeting with you to fully understand the experiment and ask a few questions.

2022-09-19 11:10 UTC, ispeakc0de commented on experiments/spring-boot/spring-boot-chaos/experiment/spring-boot-chaos.go
> +	}
```suggestion
	//PRE-CHAOS APPLICATION STATUS CHECK
	if chaosDetails.DefaultAppHealthCheck {
	log.Info("[Status]: Verify that the AUT (Application Under Test) is running (pre-chaos)")
	if err := status.AUTStatusCheck(experimentsDetails.AppNS, experimentsDetails.AppLabel, experimentsDetails.TargetContainer, experimentsDetails.Timeout, experimentsDetails.Delay, clients, &chaosDetails); err != nil {
		log.Errorf("Application status check failed, err: %v", err)
		failStep := "[pre-chaos]: Failed to verify that the AUT (Application Under Test) is in running state, err: " + err.Error()
		types.SetEngineEventAttributes(&eventsDetails, types.PreChaosCheck, "AUT: Not Running", "Warning", &chaosDetails)
		_ = events.GenerateEvents(&eventsDetails, clients, &chaosDetails, "ChaosEngine")
		result.RecordAfterFailure(&chaosDetails, &resultDetails, failStep, clients, &eventsDetails)
		return
	}
}
```

2022-09-19 11:11 UTC, ispeakc0de commented on experiments/spring-boot/spring-boot-chaos/experiment/spring-boot-chaos.go
> +	}
```suggestion
	// POST-CHAOS APPLICATION STATUS CHECK
	if chaosDetails.DefaultAppHealthCheck {
	log.Info("[Status]: Verify that the AUT (Application Under Test) is running (post-chaos)")
	if err := status.AUTStatusCheck(experimentsDetails.AppNS, experimentsDetails.AppLabel, experimentsDetails.TargetContainer, experimentsDetails.Timeout, experimentsDetails.Delay, clients, &chaosDetails); err != nil {
		log.Errorf("Application status check failed, err: %v", err)
		failStep := "[post-chaos]: Failed to verify that the AUT (Application Under Test) is running, err: " + err.Error()
		types.SetEngineEventAttributes(&eventsDetails, types.PostChaosCheck, "AUT: Not Running", "Warning", &chaosDetails)
		_ = events.GenerateEvents(&eventsDetails, clients, &chaosDetails, "ChaosEngine")
		result.RecordAfterFailure(&chaosDetails, &resultDetails, failStep, clients, &eventsDetails)
		return
	}
	}
```

2022-09-19 11:13 UTC, ispeakc0de commented on experiments/spring-boot/spring-boot-chaos/experiment/spring-boot-chaos.go
> +	go common.AbortWatcher(experimentsDetails.ExperimentName, clients, &resultDetails, &chaosDetails, &eventsDetails)
```suggestion
	go common.AbortWatcherWithoutExit(experimentsDetails.ExperimentName, clients, &resultDetails, &chaosDetails, &eventsDetails)
```

2022-09-19 11:18 UTC, ispeakc0de commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +					common.SetTargets(pod.Name, "reverted", "pod", chaosDetails)
```suggestion
				case <-signChan:
					log.Info("[Chaos]: Revert Started")
					if err := disableChaosMonkey(experimentsDetails.ChaosMonkeyPort, experimentsDetails.ChaosMonkeyPath, pod); err != nil {
						log.Errorf("Error in disabling chaos monkey, err: %v", err)
					} else{
					 common.SetTargets(pod.Name, "reverted", "pod", chaosDetails)
					}
			    // updating the chaosresult after stopped
			      failStep := "Chaos injection stopped!"
			     types.SetResultAfterCompletion(resultDetails, "Stopped", "Stopped", failStep)
			     result.ChaosResult(chaosDetails, clients, resultDetails, "EOT")
			     log.Info("[Chaos]: Revert Completed")
			    os.Exit(1)
```

2022-09-19 11:19 UTC, ispeakc0de commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +			os.Exit(1)
```suggestion
case <-signChan:
					log.Info("[Chaos]: Revert Started")
					if err := disableChaosMonkey(experimentsDetails.ChaosMonkeyPort, experimentsDetails.ChaosMonkeyPath, pod); err != nil {
						log.Errorf("Error in disabling chaos monkey, err: %v", err)
					} else{
					 common.SetTargets(pod.Name, "reverted", "pod", chaosDetails)
					}
			    // updating the chaosresult after stopped
			      failStep := "Chaos injection stopped!"
			     types.SetResultAfterCompletion(resultDetails, "Stopped", "Stopped", failStep)
			     result.ChaosResult(chaosDetails, clients, resultDetails, "EOT")
			     log.Info("[Chaos]: Revert Completed")
			    os.Exit(1)
```

2022-09-19 11:21 UTC, ispeakc0de commented on chaoslib/litmus/spring-boot-chaos/lib/spring-boot-chaos.go
> +			os.Exit(1)
```suggestion
		case <-signChan:
			log.Info("[Chaos]: Revert Started")
			for _, pod := range experimentsDetails.TargetPodList.Items {
				if err := disableChaosMonkey(experimentsDetails.ChaosMonkeyPort, experimentsDetails.ChaosMonkeyPath, pod); err != nil {
					log.Errorf("Error in disabling chaos monkey, err: %v", err)
				} else {
					common.SetTargets(pod.Name, "reverted", "pod", chaosDetails)
				}
			}
			// updating the chaosresult after stopped
			      failStep := "Chaos injection stopped!"
			     types.SetResultAfterCompletion(resultDetails, "Stopped", "Stopped", failStep)
			     result.ChaosResult(chaosDetails, clients, resultDetails, "EOT")
			     log.Info("[Chaos]: Revert Completed")
			    os.Exit(1)
```

2022-09-19 17:42 UTC, ispeakc0de approved these changes

2022-09-19 17:45 UTC, cazeaux reviewed
Hello

With this modification, the disableChaosMonkey now also changes the assault configuration. I believe that disabling chaos monkey is sufficient and avoids an unnecessary request.

2022-09-20 04:36 UTC, avaakash approved these changes

2022-09-20 05:07 UTC, neelanjan00 approved these changes

2022-09-20 06:34 UTC, ispeakc0de commented
> Hello
> 
> With this modification, the disableChaosMonkey now also changes the assault configuration. I believe that disabling chaos monkey is sufficient and avoids an unnecessary request.

Based on testing, I confirm that disabling ChaosMoney doesn't stop the assault. We need to manually stop the assault

2022-09-20 09:22 UTC, ksatchit approved these changes

2022-09-20 09:23 UTC, merged

2022-09-30 03:21 UTC, umamukkara commented
@cazeaux  - Congratulations on adding the Spring-boot support for Litmus. A big thank you from the Litmus community :)