feat(helper): Adding one helper per node
litmuschaos/litmus-go pull request #562
Opened 2022-09-13 14:52 UTC by ispeakc0de

Signed-off-by: Shubham Chaudhary <shubham.chaudhary@harness.io>

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Checklist:**
-   [ ] Fixes #<issue number>
-   [ ] PR messages has document related information
-   [ ] Labelled this PR & related issue with `breaking-changes` tag
-   [ ] PR messages has breaking changes related information
-   [ ] Labelled this PR & related issue with `requires-upgrade` tag
-   [ ] PR messages has upgrade related information
-   [ ] Commit has unit tests
-   [ ] Commit has integration tests
-   [ ] E2E run Required for the changes

2022-09-26 07:47 UTC, neelanjan00 commented on chaoslib/litmus/container-kill/helper/container-kill.go
> +		return err
Do we want to add the target information to the error as well?

2022-09-26 07:47 UTC, neelanjan00 commented on chaoslib/litmus/disk-fill/helper/disk-fill.go
> +			log.Warn("No required free space found!, It's Houseful")
It's Houseful? 😂

2022-09-26 07:47 UTC, neelanjan00 commented on chaoslib/litmus/http-chaos/helper/http-helper.go
> +		return fmt.Errorf(" failed to revert chaos, err: %v", strings.Join(errList, ","))
```suggestion
		return fmt.Errorf("failed to revert chaos, err: %v", strings.Join(errList, ","))
```

2022-09-26 07:47 UTC, neelanjan00 commented on chaoslib/litmus/http-chaos/helper/http-helper.go
> +	log.Info("[Chaos]: duration is over, reverting chaos")
```suggestion
	log.Info("[Chaos]: Chaos duration is over, reverting chaos")
```

2022-09-26 07:47 UTC, neelanjan00 commented on chaoslib/litmus/network-chaos/lib/network-chaos.go
> +		})
We should also add Jitter here

2022-09-26 07:47 UTC, neelanjan00 commented on chaoslib/litmus/pod-dns-chaos/helper/dnschaos.go
> +		log.Errorf("unable to kill dns interceptor process cry, err :%v", err)
The cry emoji is wrongly formatted

2022-09-26 07:47 UTC, neelanjan00 commented on chaoslib/litmus/stress-chaos/helper/stress-helper.go
> +				log.Errorf("unable to annotate the chaosresult for %v pod, err :%v", t.Name, err)
```suggestion
				log.Errorf("[Abort]: Unable to annotate the chaosresult for %v pod, err :%v", t.Name, err)
```

2022-09-26 07:47 UTC, neelanjan00 commented on chaoslib/litmus/stress-chaos/helper/stress-helper.go
> +				log.Errorf("unable to revert for %v pod, err :%v", t.Name, err)
```suggestion
				log.Errorf("[Abort]: Unable to revert for %v pod, err :%v", t.Name, err)
```

2022-09-26 07:47 UTC, neelanjan00 commented on pkg/utils/common/common.go
> +		log.Errorf("[ABORT]: failed to update result, err: %v", err)
```suggestion
		log.Errorf("[ABORT]: Failed to update result, err: %v", err)
```

2022-09-26 07:47 UTC, neelanjan00 commented on pkg/utils/common/common.go
> +	log.Info("[ABORT]: updated chaosresult post stop")
```suggestion
	log.Info("[ABORT]: Updated chaosresult post stop")
```

2022-09-26 07:47 UTC, neelanjan00 commented on pkg/utils/common/common.go
> +		log.Errorf("failed to create chaosresult abort event, err: %v", err)
```suggestion
		log.Errorf("[ABORT]: Failed to create chaosresult abort event, err: %v", err)
```

2022-09-26 11:34 UTC, avaakash commented on chaoslib/litmus/disk-fill/helper/disk-fill.go
> +			log.Warn("No required free space found!, It's Houseful")
The memory is partying XD

2022-09-26 11:39 UTC, neelanjan00 commented on chaoslib/litmus/disk-fill/helper/disk-fill.go
> +			log.Warn("No required free space found!, It's Houseful")
When disks have a better social life than you 🥲

2022-09-26 17:34 UTC, avaakash requested changes

2022-09-26 17:34 UTC, avaakash commented on chaoslib/litmus/http-chaos/helper/http-helper.go
> +	for _, t := range strings.Split(targetEnv, ";") {
Can we convert this into a common function if the same code is used in every helper?

2022-09-26 17:34 UTC, avaakash commented on chaoslib/litmus/http-chaos/helper/http-helper.go
> +	// proceed for chaos injection
```suggestion
```
this comment is no longer required

2022-09-29 12:26 UTC, ispeakc0de commented on chaoslib/litmus/container-kill/helper/container-kill.go
> +		return err
It is killing all containers at once so if I will  append all container/pod names into error then error msg will become too long. Anyways we are logging {podName and targetContainer} duo for all pods/containers

2022-11-10 04:15 UTC, ksatchit approved these changes

2022-11-16 05:21 UTC, uditgaurav approved these changes

2022-11-16 06:05 UTC, neelanjan00 approved these changes

2022-11-16 06:12 UTC, merged