feat(experiment): Converted Cassandra pod delete experiment in go
litmuschaos/litmus-go pull request #68
Opened 2020-08-04 07:11 UTC by uditgaurav

Signed-off-by: Udit Gaurav <udit.gaurav@mayadata.io>

2020-08-13 14:58 UTC, uditgaurav commented
Chaos Result
```yaml
Name:         cassandra-chaos-pod-delete
Namespace:    cassandra
Labels:       name=cassandra-chaos-pod-delete
Annotations:  <none>
API Version:  litmuschaos.io/v1alpha1
Kind:         ChaosResult
Metadata:
  Creation Timestamp:  2020-08-12T18:58:39Z
  Generation:          12
  Resource Version:    12726042
  Self Link:           /apis/litmuschaos.io/v1alpha1/namespaces/cassandra/chaosresults/cassandra-chaos-pod-delete
  UID:                 dc8aebdc-a149-4cb5-a788-7727d985bd30
Spec:
  Engine:      cassandra-chaos
  Experiment:  pod-delete
Status:
  Experimentstatus:
    Fail Step:  N/A
    Phase:      Completed
    Verdict:    Pass
Events:
  Type    Reason   Age   From                               Message
  ----    ------   ----  ----                               -------
  Normal  Summary  14m   cassandra-pod-delete-dnjj3v-bszqs  pod-delete experiment has been Passed
```
Chaos Engine
```yaml
Name:         cassandra-chaos
Namespace:    cassandra
Labels:       <none>
Annotations:  API Version:  litmuschaos.io/v1alpha1
Kind:         ChaosEngine
Metadata:
  Creation Timestamp:  2020-08-13T14:40:42Z
  Finalizers:
    chaosengine.litmuschaos.io/finalizer
  Generation:        25
  Resource Version:  12726070
  Self Link:         /apis/litmuschaos.io/v1alpha1/namespaces/cassandra/chaosengines/cassandra-chaos
  UID:               96180080-f691-4815-bcbc-50b8e0f196b4
Spec:
  Annotation Check:  false
  Appinfo:
    Appkind:              statefulset
    Applabel:             app=cassandra
    Appns:                cassandra
  Chaos Service Account:  cassandra-pod-delete-sa
  Components:
    Runner:
      Image:     litmuschaos/chaos-runner:1.6.2
  Engine State:  stop
  Experiments:
    Name:  cassandra-pod-delete
    Spec:
      Components:
        Env:
          Name:   TOTAL_CHAOS_DURATION
          Value:  15
          Name:   CHAOS_INTERVAL
          Value:  15
          Name:   FORCE
          Value:  false
          Name:   CASSANDRA_SVC_NAME
          Value:  cassandra
          Name:   KEYSPACE_REPLICATION_FACTOR
          Value:  3
          Name:   CASSANDRA_PORT
          Value:  9042
          Name:   CASSANDRA_LIVENESS_CHECK
          Value:  
        Status Check Timeouts:
      Rank:             0
  Job Clean Up Policy:  retain
Status:
  Engine Status:  completed
  Experiments:
    Experiment Pod:    cassandra-pod-delete-dnjj3v-bszqs
    Last Update Time:  2020-08-13T14:42:36Z
    Name:              cassandra-pod-delete
    Runner:            cassandra-chaos-runner
    Status:            Running
    Verdict:           Awaited
Events:
  Type    Reason                     Age   From                               Message
  ----    ------                     ----  ----                               -------
  Normal  ChaosEngineInitialized     16m   chaos-operator                     cassandra-chaos-runner created successfully
  Normal  ExperimentDependencyCheck  16m   cassandra-chaos-runner             Experiment resources validated for Chaos Experiment: 'cassandra-pod-delete'
  Normal  ExperimentJobCreate        16m   cassandra-chaos-runner             Experiment Job 'cassandra-pod-delete-dnjj3v' created for Chaos Experiment 'cassandra-pod-delete'
  Normal  PreChaosCheck              16m   cassandra-pod-delete-dnjj3v-bszqs  AUT is Running successfully
  Normal  ChaosInject                16m   cassandra-pod-delete-dnjj3v-bszqs  Injecting pod-delete chaos on application pod
  Normal  PostChaosCheck             15m   cassandra-pod-delete-dnjj3v-bszqs  AUT is Running successfully
  Normal  Summary                    14m   cassandra-pod-delete-dnjj3v-bszqs  pod-delete experiment has been Passed
  Normal  ExperimentJobCleanUp       14m   cassandra-chaos-runner             Experiment Job 'cassandra-pod-delete-dnjj3v' will be retained
  Normal  ChaosEngineCompleted       14m   chaos-operator                     Chaos Engine completed, will delete or retain the resources according to jobCleanUpPolicy
```

Experiment Logs:

```yaml
W0813 14:40:55.515268       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2020-08-13T14:40:55Z" level=info msg="[PreReq]: Getting the ENV for the  experiment"
time="2020-08-13T14:40:55Z" level=info msg="[PreReq]: Updating the chaos result of pod-delete experiment (SOT)"
time="2020-08-13T14:40:55Z" level=info msg="The application informations are as follows" Namespace=cassandra Label="app=cassandra" Ramp Time=0
time="2020-08-13T14:40:55Z" level=info msg="[Status]: Verify that the AUT (Application Under Test) is running (pre-chaos)"
time="2020-08-13T14:40:55Z" level=info msg="[Status]: Checking whether application pods are in running state"
time="2020-08-13T14:40:55Z" level=info msg="The running status of Pods are as follows" Pod=cassandra-0 Status=Running
time="2020-08-13T14:40:55Z" level=info msg="The running status of Pods are as follows" Pod=cassandra-1 Status=Running
time="2020-08-13T14:40:55Z" level=info msg="The running status of Pods are as follows" Pod=cassandra-2 Status=Running
time="2020-08-13T14:40:55Z" level=info msg="[Status]: Checking whether application containers are in running state"
time="2020-08-13T14:40:55Z" level=info msg="The running status of container are as follows" container=cassandra Pod=cassandra-0 Status=Running
time="2020-08-13T14:40:55Z" level=info msg="The running status of container are as follows" container=cassandra Pod=cassandra-1 Status=Running
time="2020-08-13T14:40:55Z" level=info msg="The running status of container are as follows" Pod=cassandra-2 Status=Running container=cassandra
time="2020-08-13T14:40:55Z" level=info msg="[Status]: Checking the load distribution on the ring (pre-chaos)"
time="2020-08-13T14:40:55Z" level=info msg="[NodeToolStatus]: The application pod name for checking load distribution: cassandra-2"
time="2020-08-13T14:40:55Z" level=info msg="[Check]: Checking for the distribution of load on the ring"
time="2020-08-13T14:40:59Z" level=info msg="[Check]: Check each replica should have some load"
I0813 14:40:59.999743       1 cassandra-pod-delete.go:402] Liveness Deployment Created successfully!
time="2020-08-13T14:41:00Z" level=info msg="Liveness service created successfully!"
time="2020-08-13T14:41:00Z" level=info msg="[Status]: Checking the status of the cassandra liveness pod"
time="2020-08-13T14:41:00Z" level=info msg="[Status]: Checking whether application pods are in running state"
time="2020-08-13T14:41:04Z" level=info msg="The running status of Pods are as follows" Pod=cassandra-liveness-deploy-549676d8cf-hh4kn Status=Running
time="2020-08-13T14:41:04Z" level=info msg="[Status]: Checking whether application containers are in running state"
time="2020-08-13T14:41:04Z" level=info msg="The running status of container are as follows" container=liveness-business-logic Pod=cassandra-liveness-deploy-549676d8cf-hh4kn Status=Running
time="2020-08-13T14:41:04Z" level=info msg="The running status of container are as follows" Status=Running container=webserver Pod=cassandra-liveness-deploy-549676d8cf-hh4kn
time="2020-08-13T14:41:04Z" level=info msg="[Liveness]: Record the resource version of liveness pod"
I0813 14:41:04.082655       1 cassandra-pod-delete.go:88] The targetPodList is: [cassandra-0]
I0813 14:41:04.091120       1 cassandra-pod-delete.go:169] The Resource Version list is: [12702779]
time="2020-08-13T14:41:04Z" level=info msg="Resource Version before chaos recorded successfully"
time="2020-08-13T14:41:04Z" level=info msg="[Confirmation]: The cassandra application liveness pod deployed successfully"
time="2020-08-13T14:41:04Z" level=info msg="[Info]: Killing the following pods" PodList="[cassandra-2]"
time="2020-08-13T14:41:04Z" level=info msg="[Wait]: Wait for the chaos interval 15s"
time="2020-08-13T14:41:19Z" level=info msg="[Status]: Verification for the recreation of application pod"
time="2020-08-13T14:41:19Z" level=info msg="[Status]: Checking whether app [...]

2020-08-13 19:01 UTC, ispeakc0de commented on pkg/apps/cassandra/cassandra-pod-delete.go
> +			Name: "cassandra-liveness-service",
same as above

2020-08-13 19:02 UTC, ispeakc0de commented on pkg/apps/cassandra/cassandra-pod-delete.go
> +					NodePort: 0,
Is this a mandatory field? as this is a clusterIP service

2020-08-13 19:05 UTC, ispeakc0de commented on pkg/apps/cassandra/cassandra-pod-delete.go
> +			Replicas: ptrint32(1),
you can also put a function like this 
`Replicas: func(i int32) *int32 { return &i }(1),`

2020-08-13 22:53 UTC, uditgaurav commented on pkg/apps/cassandra/cassandra-pod-delete.go
> +			Replicas: ptrint32(1),
it is already there

2020-08-14 07:13 UTC, ispeakc0de commented on pkg/apps/cassandra/cassandra-pod-delete.go
> +			Replicas: ptrint32(1),
Yeah instead of defining a separate function, I was asking for anonymous function

2020-08-14 07:49 UTC, uditgaurav commented on pkg/apps/cassandra/cassandra-pod-delete.go
> +	cmd := exec.Command("sh", "-c", `kubectl exec -it `+targetPod+` -n `+experimentsDetails.AppNS+` nodetool status | tail -n +6 | head -n -1`)
Tried that first but the command in VersionedParams does not support special characters like `$` in awk. So I wasn't able to filter the output due to this limitation I need to move on the other approach.

2020-08-14 07:51 UTC, ispeakc0de commented on pkg/apps/cassandra/cassandra-pod-delete.go
> +	cmd := exec.Command("sh", "-c", `kubectl exec -it `+targetPod+` -n `+experimentsDetails.AppNS+` nodetool status | tail -n +6 | head -n -1`)
Please refer this for awk commands

2020-08-14 07:55 UTC, ispeakc0de commented on pkg/apps/cassandra/cassandra-pod-delete.go
> +	cmd := exec.Command("sh", "-c", `kubectl exec -it `+targetPod+` -n `+experimentsDetails.AppNS+` nodetool status | tail -n +6 | head -n -1`)
Can you try to put the command like this, it supports all sh commands https://github.com/litmuschaos/litmus-go/blob/master/pkg/probe/cmdprobe.go#L143

2020-08-14 11:15 UTC, uditgaurav commented on pkg/apps/cassandra/cassandra-pod-delete.go
> +	cmd := exec.Command("sh", "-c", `kubectl exec -it `+targetPod+` -n `+experimentsDetails.AppNS+` nodetool status | tail -n +6 | head -n -1`)
Thanks for making it simple by `/pkg/utils/exec`!

2020-08-14 14:52 UTC, uditgaurav commented
latest logs:

```bash
W0814 14:50:48.527373       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2020-08-14T14:50:48Z" level=info msg="[PreReq]: Getting the ENV for the  experiment"
time="2020-08-14T14:50:48Z" level=info msg="[PreReq]: Updating the chaos result of pod-delete experiment (SOT)"
time="2020-08-14T14:50:48Z" level=info msg="The application informations are as follows" Namespace=cassandra Label="app=cassandra" Ramp Time=0
time="2020-08-14T14:50:48Z" level=info msg="[Status]: Verify that the AUT (Application Under Test) is running (pre-chaos)"
time="2020-08-14T14:50:48Z" level=info msg="[Status]: Checking whether application pods are in running state"
time="2020-08-14T14:50:48Z" level=info msg="The running status of Pods are as follows" Pod=cassandra-0 Status=Running
time="2020-08-14T14:50:48Z" level=info msg="The running status of Pods are as follows" Status=Running Pod=cassandra-1
time="2020-08-14T14:50:48Z" level=info msg="The running status of Pods are as follows" Pod=cassandra-2 Status=Running
time="2020-08-14T14:50:48Z" level=info msg="[Status]: Checking whether application containers are in running state"
time="2020-08-14T14:50:48Z" level=info msg="The running status of container are as follows" Pod=cassandra-0 Status=Running container=cassandra
time="2020-08-14T14:50:48Z" level=info msg="The running status of container are as follows" Status=Running container=cassandra Pod=cassandra-1
time="2020-08-14T14:50:48Z" level=info msg="The running status of container are as follows" container=cassandra Pod=cassandra-2 Status=Running
time="2020-08-14T14:50:48Z" level=info msg="[Status]: Checking the load distribution on the ring (pre-chaos)"
time="2020-08-14T14:50:48Z" level=info msg="[NodeToolStatus]: The application pod name for checking load distribution: cassandra-0"
time="2020-08-14T14:50:48Z" level=info msg="[Check]: Checking for the distribution of load on the ring"
time="2020-08-14T14:50:54Z" level=info msg="[Check]: Check each replica should have some load"
I0814 14:50:54.397278       1 liveness.go:359] Liveness Deployment Created successfully!
time="2020-08-14T14:50:54Z" level=info msg="Liveness service created successfully!"
time="2020-08-14T14:50:54Z" level=info msg="[Status]: Checking the status of the cassandra liveness pod"
time="2020-08-14T14:50:54Z" level=info msg="[Status]: Checking whether application pods are in running state"
time="2020-08-14T14:50:58Z" level=info msg="The running status of Pods are as follows" Status=Running Pod=cassandra-liveness-deploy-xvlbzg-546dd8cb5d-d86z9
time="2020-08-14T14:50:58Z" level=info msg="[Status]: Checking whether application containers are in running state"
time="2020-08-14T14:50:58Z" level=info msg="The running status of container are as follows" container=liveness-business-logic Pod=cassandra-liveness-deploy-xvlbzg-546dd8cb5d-d86z9 Status=Running
time="2020-08-14T14:50:58Z" level=info msg="The running status of container are as follows" Status=Running container=webserver Pod=cassandra-liveness-deploy-xvlbzg-546dd8cb5d-d86z9
time="2020-08-14T14:50:58Z" level=info msg="[Liveness]: Record the resource version of liveness pod"
I0814 14:50:58.503590       1 liveness.go:120] The Resource Version of liveness pod is recorded: 12888644
time="2020-08-14T14:50:58Z" level=info msg="Resource Version before chaos recorded successfully"
time="2020-08-14T14:50:58Z" level=info msg="[Confirmation]: The cassandra application liveness pod deployed successfully"
time="2020-08-14T14:50:58Z" level=info msg="[Info]: Killing the following pods" PodList="[cassandra-1]"
time="2020-08-14T14:50:58Z" level=info msg="[Wait]: Wait for the chaos interval 15s"
time="2020-08-14T14:51:13Z" level=info msg="[Status]: Verification for the recreation of application pod"
time="2020-08-14T14:51:13Z" level=info msg="[Status]: Checking whether application pods are in running state"
time="2020-08-14T14:51:13Z" level=info msg="The running status of Pods are as follows" Pod=cassandra-0 Status=Running
time="2020-08-14T14:51:13Z" level=info msg="The running status of Pods are as follows" Status=Running Pod=cassandra-1
time="2020-08-14T14:51:13Z" level=info msg="The running status of Pods are as follows" Status=Running Pod=cassandra-2
time="2020-08-14T14:51:13Z" level=info msg="[Status]: Checking whether application containers are in running state"
time="2020-08-14T14:51:13Z" level=info msg="The running status of container are as follows" container=cassandra Pod=cassandra-0 Status=Running
time="2020-08-14T14:51:13Z" level=info msg="The running status of container are as follows" Status=Running container=cassandra Pod=cassandra-1
time="2020-08-14T14:51:13Z" level=info msg="The running status of container are as follows" container=cassandra Pod=cassandra-2 Status=Running
time="2020-08-14T14:51:13Z" level=info msg="[Completion]: pod-delete chaos is done"
time="2020-08-14T14:51:13Z" level=info msg="[Confirmation]: The application pod has been deleted successfully"
time="2020-08-14T14:51:13Z" level=info msg="[Status]: Verify that the AUT (Application Under Test) is running (post-chaos)"
time="2020-08-14T14:51:13Z" level=info msg="[Status]: Checking whether application pods are in running state"
time="2020-08-14T14:51:13Z" level=info msg="The running status of Pods are as follows" Status=Running Pod=cassandra-0
time="2020-08-14T14:51:13Z" level=info msg="The running status of Pods are as follows" Status=Running Pod=cassandra-1
time="2020-08-14T14:51:13Z" level=info msg="The running status of Pods are as follows" Pod=cassandra-2 Status=Running
time="2020-08-14T14:51:13Z" level=info msg="[Status]: Checking whether application containers are in running state"
time="2020-08-14T14:51:13Z" level=info msg="The running status of container are as follows" container=cassandra Pod=cassandra-0 Status=Running
time="2020-08-14T14:51:13Z" level=info msg="The running status of container are as follows" container=cassandra Pod=cassandra-1 Status=Running
time="2020-08-14T14:51:13Z" level=info msg="The running status of container are as follows" Pod=cassandra-2 Status=Running container=cassandra
time="2020-08-14T14:51:13Z" level=info msg="[Status]: Checking the load distribution on the ring (post-chaos)"
time="2020-08-14T14:51:13Z" level=info msg="[NodeToolStatus]: The application pod name for checking load distribution: cassandra-0"
time="2020-08-14T14:51:13Z" level=info msg="[Check]: Checking for the distribution of load on the ring"
time="2020-08-14T14:51:18Z" level=info msg="[Check]: Check each replica should have some load"
time="2020-08-14T14:51:18Z" level=info msg="[Status]: Confirm that the cassandra liveness pod is running(post-chaos)"
time="2020-08-14T14:51:18Z" level=info msg="[Status]: Checking whether application pods are in running state"
time="2020-08-14T14:51:18Z" level=info msg="The running status of Pods are as follows" Pod=cassandra-liveness-deploy-xvlbzg-546dd8cb5d-d86z9 Status=Running
time="2020-08-14T14:51:18Z" level=info msg="[Status]: Checking whether application containers are in running state"
time="2020-08-14T14:51:18Z" level=info msg="The running status of container are as follows" Status=Running container=liveness-business-logic Pod=cassandra-liveness-deploy-xvlbzg-546dd8cb5d-d86z9
time="2020-08-14T14:51:18Z" level=info msg="The running status of container are as follows" Status=Running container=webserver Pod=cassandra-liveness-deploy-xvlbzg-546dd8cb5d-d86z9
time="2020-08-14T14:51:18Z" level=info msg="[CleanUP]: Getting ClusterIP of liveness service"
time="2020-08-14T14:51:18Z" level=info msg="The URL to check the status of liveness pod cycle: http://10.100.116.157:8088"
time="2020-08-14T14:51:20Z" level=info msg="[Verification]: Wait for liveness pod to come in CycleComplete state"
time="2020-08-14T14:51:20Z" level=info msg="Liveness pod to comes in CycleComplete state"
time="2020-08-14T14:51:20Z" level=info msg="[Liveness]: Record the resource [...]

2020-08-14 14:53 UTC, uditgaurav commented on pkg/apps/cassandra/cassandra-pod-delete.go
> +	targetPodList, err := pod_delete.PreparePodList(experimentsDetails, clients)
Ah! missed that one. Added now! Thanks!

2020-08-14 17:20 UTC, ispeakc0de commented on pkg/apps/cassandra/liveness.go
> +	klog.Info("Liveness Deployment Created successfully!")
log.info

2020-08-20 06:04 UTC, uditgaurav commented
```
W0820 06:02:42.420332       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2020-08-20T06:02:42Z" level=info msg="[PreReq]: Getting the ENV for the cassandra-pod-delete experiment"
time="2020-08-20T06:02:42Z" level=info msg="[PreReq]: Updating the chaos result of cassandra-pod-delete experiment (SOT)"
time="2020-08-20T06:02:42Z" level=info msg="The application informations are as follows" Ramp Time=0 Namespace=cassandra Label="app=cassandra"
time="2020-08-20T06:02:42Z" level=info msg="[Status]: Verify that the AUT (Application Under Test) is running (pre-chaos)"
time="2020-08-20T06:02:42Z" level=info msg="[Status]: Checking whether application pods are in running state"
time="2020-08-20T06:02:42Z" level=info msg="The running status of Pods are as follows" Pod=cassandra-0 Status=Running
time="2020-08-20T06:02:42Z" level=info msg="The running status of Pods are as follows" Pod=cassandra-1 Status=Running
time="2020-08-20T06:02:42Z" level=info msg="The running status of Pods are as follows" Status=Running Pod=cassandra-2
time="2020-08-20T06:02:42Z" level=info msg="[Status]: Checking whether application containers are in running state"
time="2020-08-20T06:02:42Z" level=info msg="The running status of container are as follows" container=cassandra Pod=cassandra-0 Status=Running
time="2020-08-20T06:02:42Z" level=info msg="The running status of container are as follows" Status=Running container=cassandra Pod=cassandra-1
time="2020-08-20T06:02:42Z" level=info msg="The running status of container are as follows" container=cassandra Pod=cassandra-2 Status=Running
time="2020-08-20T06:02:42Z" level=info msg="[Status]: Checking the load distribution on the ring (pre-chaos)"
time="2020-08-20T06:02:42Z" level=info msg="[NodeToolStatus]: The application pod name for checking load distribution: cassandra-0"
time="2020-08-20T06:02:42Z" level=info msg="[Check]: Checking for the distribution of load on the ring"
time="2020-08-20T06:02:46Z" level=info msg="[Check]: Check each replica is haveing some load"
time="2020-08-20T06:02:46Z" level=info msg="Liveness Deployment Created successfully!"
time="2020-08-20T06:02:46Z" level=info msg="Liveness service created successfully!"
time="2020-08-20T06:02:46Z" level=info msg="[Status]: Checking the status of the cassandra liveness pod"
time="2020-08-20T06:02:46Z" level=info msg="[Status]: Checking whether application pods are in running state"
time="2020-08-20T06:02:48Z" level=info msg="The running status of Pods are as follows" Pod=cassandra-liveness-deploy-xvlbzg-546dd8cb5d-fc5tz Status=Running
time="2020-08-20T06:02:48Z" level=info msg="[Status]: Checking whether application containers are in running state"
time="2020-08-20T06:02:48Z" level=info msg="The running status of container are as follows" Status=Running container=liveness-business-logic Pod=cassandra-liveness-deploy-xvlbzg-546dd8cb5d-fc5tz
time="2020-08-20T06:02:48Z" level=info msg="The running status of container are as follows" container=webserver Pod=cassandra-liveness-deploy-xvlbzg-546dd8cb5d-fc5tz Status=Running
time="2020-08-20T06:02:48Z" level=info msg="[Confirmation]: The cassandra application liveness pod deployed successfully"
time="2020-08-20T06:02:48Z" level=info msg="[Info]: Killing the following pods" PodList="[cassandra-1]"
time="2020-08-20T06:02:48Z" level=info msg="[Wait]: Wait for the chaos interval 15s"
time="2020-08-20T06:03:03Z" level=info msg="[Status]: Verification for the recreation of application pod"
time="2020-08-20T06:03:03Z" level=info msg="[Status]: Checking whether application pods are in running state"
time="2020-08-20T06:03:03Z" level=info msg="The running status of Pods are as follows" Pod=cassandra-0 Status=Running
time="2020-08-20T06:03:03Z" level=info msg="The running status of Pods are as follows" Status=Running Pod=cassandra-1
time="2020-08-20T06:03:03Z" level=info msg="The running status of Pods are as follows" Pod=cassandra-2 Status=Running
time="2020-08-20T06:03:03Z" level=info msg="[Status]: Checking whether application containers are in running state"
time="2020-08-20T06:03:03Z" level=info msg="The running status of container are as follows" container=cassandra Pod=cassandra-0 Status=Running
time="2020-08-20T06:03:03Z" level=info msg="The running status of container are as follows" Pod=cassandra-1 Status=Running container=cassandra
time="2020-08-20T06:03:03Z" level=info msg="The running status of container are as follows" container=cassandra Pod=cassandra-2 Status=Running
time="2020-08-20T06:03:03Z" level=info msg="[Completion]: cassandra-pod-delete chaos is done"
time="2020-08-20T06:03:03Z" level=info msg="[Confirmation]: The application pod has been deleted successfully"
time="2020-08-20T06:03:03Z" level=info msg="[Status]: Verify that the AUT (Application Under Test) is running (post-chaos)"
time="2020-08-20T06:03:03Z" level=info msg="[Status]: Checking whether application pods are in running state"
time="2020-08-20T06:03:03Z" level=info msg="The running status of Pods are as follows" Pod=cassandra-0 Status=Running
time="2020-08-20T06:03:03Z" level=info msg="The running status of Pods are as follows" Pod=cassandra-1 Status=Running
time="2020-08-20T06:03:03Z" level=info msg="The running status of Pods are as follows" Status=Running Pod=cassandra-2
time="2020-08-20T06:03:03Z" level=info msg="[Status]: Checking whether application containers are in running state"
time="2020-08-20T06:03:03Z" level=info msg="The running status of container are as follows" Pod=cassandra-0 Status=Running container=cassandra
time="2020-08-20T06:03:03Z" level=info msg="The running status of container are as follows" Pod=cassandra-1 Status=Running container=cassandra
time="2020-08-20T06:03:03Z" level=info msg="The running status of container are as follows" container=cassandra Pod=cassandra-2 Status=Running
time="2020-08-20T06:03:03Z" level=info msg="[Status]: Checking the load distribution on the ring (post-chaos)"
time="2020-08-20T06:03:03Z" level=info msg="[NodeToolStatus]: The application pod name for checking load distribution: cassandra-0"
time="2020-08-20T06:03:03Z" level=info msg="[Check]: Checking for the distribution of load on the ring"
time="2020-08-20T06:03:09Z" level=info msg="[Check]: Check each replica is haveing some load"
time="2020-08-20T06:03:09Z" level=info msg="[Status]: Confirm that the cassandra liveness pod is running(post-chaos)"
time="2020-08-20T06:03:09Z" level=info msg="[Status]: Checking whether application pods are in running state"
time="2020-08-20T06:03:09Z" level=info msg="The running status of Pods are as follows" Pod=cassandra-liveness-deploy-xvlbzg-546dd8cb5d-fc5tz Status=Running
time="2020-08-20T06:03:09Z" level=info msg="[Status]: Checking whether application containers are in running state"
time="2020-08-20T06:03:09Z" level=info msg="The running status of container are as follows" Status=Running container=liveness-business-logic Pod=cassandra-liveness-deploy-xvlbzg-546dd8cb5d-fc5tz
time="2020-08-20T06:03:09Z" level=info msg="The running status of container are as follows" Status=Running container=webserver Pod=cassandra-liveness-deploy-xvlbzg-546dd8cb5d-fc5tz
time="2020-08-20T06:03:09Z" level=info msg="[CleanUP]: Getting ClusterIP of liveness service"
time="2020-08-20T06:03:09Z" level=info msg="[Liveness]: Record the resource version of liveness pod (after-chaos)"
time="2020-08-20T06:03:09Z" level=info msg="The cassandra cluster is active"
time="2020-08-20T06:03:09Z" level=info msg="The URL to check the status of liveness pod cycle: http://10.100.209.234:8088"
time="2020-08-20T06:03:09Z" level=info msg="[Verification]: Wait for liveness pod to come in CycleComplete state"
time="2020-08-20T06:03:49Z" level=info msg="Cassandra liveness deployment deleted successfully"
time="2020-08-20T06:03:51Z" level=info msg="Cassandra liveness service deleted successfully"
time="2020-08-20T06:03:51Z" level=info msg="[The End]: Updating the ch [...]

2020-08-20 07:53 UTC, ispeakc0de requested changes

2020-08-20 07:53 UTC, ispeakc0de commented on en
> +apiVersion: litmuschaos.io/v1alpha1
Can we remove all the extra file?

2020-08-20 07:53 UTC, ispeakc0de commented on experiments/cassandra/pod-delete/pod-delete.go
> +		"Namespace": experimentsDetails.ChaoslibDetail.AppNS,
Can we display some cassandra related details as well here?

2020-08-20 07:53 UTC, ispeakc0de commented on experiments/cassandra/pod-delete/pod-delete.go
> +		log.Info("[Liveness]: Cassandra Liveness check skipped as it was not enabled")
log.Warning("[Liveness]: Cassandra Liveness check skipped as it was not enabled")

2020-08-20 07:53 UTC, ispeakc0de commented on experiments/cassandra/pod-delete/pod-delete.go
> +			failStep := "Including the litmus lib for pod-delete"
failStep := "Including the litmus lib for cassandra-pod-delete"

2020-08-20 07:53 UTC, ispeakc0de commented on experiments/cassandra/pod-delete/pod-delete.go
> +		failStep := "Including the litmus lib for pod-delete"
same as above

2020-08-20 07:53 UTC, ispeakc0de commented on pkg/cassandra/liveness.go
> +	experimentsDetails.RunID = GetRunID()
can we use our `/pkg/utils/common` pakage for runid?

2020-08-20 07:53 UTC, ispeakc0de commented on pkg/cassandra/liveness.go
> +// LivenessCheck will check the liveness of the cassandra application during chaos
// LivenessCheck will create an external liveness pod which will continuously check for the liveness of cassandra statefulset

2020-08-20 07:53 UTC, ispeakc0de commented on pkg/cassandra/liveness.go
> +	log.Info("[Liveness]: Record the resource version of liveness pod (after-chaos)")
can we remove this log?

2020-08-20 07:53 UTC, ispeakc0de commented on pkg/cassandra/liveness.go
> +			log.Info("[Verification]: Wait for liveness pod to come in CycleComplete state")
if !strings.Contains(string(data), "CycleComplete") {
log.Info("[Verification]: Wait for liveness pod to come in CycleComplete state")
				return errors.Errorf("Livenss pod is not in completed state")
			}
log.Info("Liveness pod to comes in CycleComplete state")

2020-08-20 07:53 UTC, ispeakc0de commented on pkg/cassandra/liveness.go
> +func GetRunID() string {
we can remove this as we will use our `/pkg/utils/common`

2020-08-20 07:53 UTC, ispeakc0de commented on pkg/cassandra/node-tools.go
> +	log.Info("[Check]: Check each replica is haveing some load")
typo, as this log in the end of the check so can we add a conclusion statement. 

Load is distributed over all the replica of cassandra

2020-08-20 07:53 UTC, ispeakc0de commented on pkg/generic/pod-delete/types/types.go
> +	LIBImage            string
where are we using lib image?

2020-08-20 08:32 UTC, ispeakc0de approved these changes

2020-08-31 09:10 UTC, ksatchit approved these changes

2020-08-31 09:10 UTC, ispeakc0de approved these changes

2020-08-31 09:11 UTC, merged