feat: Add a k6-loadgen chaos fault
litmuschaos/litmus-go pull request #687
Opened 2024-02-10 05:09 UTC by namkyu1999

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Checklist:**
-   [ ] Fixes #<issue number>
-   [ ] PR messages has document related information
-   [ ] Labelled this PR & related issue with `breaking-changes` tag
-   [ ] PR messages has breaking changes related information
-   [ ] Labelled this PR & related issue with `requires-upgrade` tag
-   [ ] PR messages has upgrade related information
-   [ ] Commit has unit tests
-   [ ] Commit has integration tests
-   [ ] E2E run Required for the changes

2024-02-15 06:56 UTC, neelanjan00 requested changes

2024-02-15 06:56 UTC, neelanjan00 commented on chaoslib/litmus/k6-loadgen/lib/k6-loadgen.go
> +	log.Info("[Wait]: waiting till the completion of the helper pod")
```suggestion
	log.Info("[Wait]: Waiting till the completion of the helper pod")
```

2024-02-15 06:56 UTC, neelanjan00 commented on pkg/load/k6-loadgen/types/types.go
> +
```suggestion
```

2024-02-15 06:56 UTC, neelanjan00 commented on pkg/types/types.go
> +	chaosDetails.Labels = map[string]string{}
Why do we need this field?

2024-02-15 06:56 UTC, neelanjan00 commented on chaoslib/litmus/k6-loadgen/lib/k6-loadgen.go
> +						},
If an end user, who is executing the fault, doesn't have access to the host file system, they won't be able to create the script there and thus execute the fault. Therefore, we should use a ConfigMap to store the script and mount it here. The name of the ConfigMap can be an experiment input (we can have a default name).

2024-02-15 08:33 UTC, namkyu1999 commented on chaoslib/litmus/k6-loadgen/lib/k6-loadgen.go
> +						},
I changed this implement so that the script file is mounted in the helper pod using a secret name while taking the name of the secret as an experiment ENV input of `go-runner`.

2024-02-15 08:41 UTC, namkyu1999 commented on pkg/types/types.go
> +	chaosDetails.Labels = map[string]string{}
It generates errer when we call `GetHelperLabels()` function because `chaosDetails.Labels` is not initialized. I added this code here to avoid errors that can occur when using the helper pod. If not reasonable, I'll move it to an experiment-specific area.

https://github.com/litmuschaos/litmus-go/blob/master/pkg/utils/common/pods.go#L116

2024-02-15 11:16 UTC, neelanjan00 approved these changes

2024-02-15 11:19 UTC, neelanjan00 commented on pkg/load/k6-loadgen/types/types.go
> +	IsTargetContainerProvided bool
Do we need this field?

2024-02-15 11:19 UTC, neelanjan00 commented on pkg/load/k6-loadgen/environment/environment.go
> +// ADDED FOR FEW MANDATORY FIELD
Please remove these
```suggestion
```

2024-02-16 07:12 UTC, namkyu1999 commented on pkg/load/k6-loadgen/types/types.go
> +	IsTargetContainerProvided bool
I cleaned up unused variables :)

2024-03-07 13:03 UTC, uditgaurav approved these changes

2024-03-07 13:49 UTC, merged