chore(kafka): Add kafka broker pod failure experiment in litmus-go
litmuschaos/litmus-go pull request #93
Opened 2020-08-24 18:35 UTC by uditgaurav

Signed-off-by: Udit Gaurav <udit.gaurav@mayadata.io>

2020-09-29 18:32 UTC, uditgaurav commented
logs:

```bash
udit@ubuntu ~/g/s/g/l/litmus-go> go run experiments/kafka/kafka-broker-pod-failure/kafka-broker-pod-failure.go --kubeconfig=$HOME/.kube/config 
INFO[2020-09-29T23:57:06+05:30] [PreReq]: Getting the ENV for the kafka-broker-pod-failure 
INFO[2020-09-29T23:57:06+05:30] [PreReq]: Updating the chaos result of kafka-broker-pod-failure experiment (SOT) 
INFO[2020-09-29T23:57:08+05:30] The application informations are as follows   Kafka Label= Ramp Time=0 Kafka Namespace=default
INFO[2020-09-29T23:57:08+05:30] [Status]: Verify that the Kafka cluster is healthy(pre-chaos) 
INFO[2020-09-29T23:57:08+05:30] [Status]: Verify that all kafka pods are running 
INFO[2020-09-29T23:57:08+05:30] [Status]: Checking whether application containers are in running state 
INFO[2020-09-29T23:57:08+05:30] The running status of container are as follows  container=k8skafka Pod=kafka-kafka-0 Status=Running
INFO[2020-09-29T23:57:08+05:30] The running status of container are as follows  Status=Running container=kafka-node-exporter Pod=kafka-kafka-0
INFO[2020-09-29T23:57:08+05:30] The running status of container are as follows  Status=Running container=k8skafka Pod=kafka-kafka-1
INFO[2020-09-29T23:57:08+05:30] The running status of container are as follows  Status=Running container=kafka-node-exporter Pod=kafka-kafka-1
INFO[2020-09-29T23:57:08+05:30] The running status of container are as follows  container=k8skafka Pod=kafka-kafka-2 Status=Running
INFO[2020-09-29T23:57:08+05:30] The running status of container are as follows  Pod=kafka-kafka-2 Status=Running container=kafka-node-exporter
INFO[2020-09-29T23:57:10+05:30] [Status]: Checking whether application pods are in running state 
INFO[2020-09-29T23:57:11+05:30] The running status of Pods are as follows     Pod=kafka-kafka-0 Status=Running
INFO[2020-09-29T23:57:11+05:30] The running status of Pods are as follows     Pod=kafka-kafka-1 Status=Running
INFO[2020-09-29T23:57:11+05:30] The running status of Pods are as follows     Pod=kafka-kafka-2 Status=Running
INFO[2020-09-29T23:57:13+05:30] [Status]: Verify that all zookeeper pods are running 
INFO[2020-09-29T23:57:13+05:30] [Status]: Checking whether application containers are in running state 
INFO[2020-09-29T23:57:13+05:30] The running status of container are as follows  Status=Running container=kubernetes-zookeeper Pod=zookeeper-instance-zookeeper-0
INFO[2020-09-29T23:57:13+05:30] The running status of container are as follows  Pod=zookeeper-instance-zookeeper-1 Status=Running container=kubernetes-zookeeper
INFO[2020-09-29T23:57:13+05:30] The running status of container are as follows  Pod=zookeeper-instance-zookeeper-2 Status=Running container=kubernetes-zookeeper
INFO[2020-09-29T23:57:15+05:30] [Status]: Checking whether application pods are in running state 
INFO[2020-09-29T23:57:16+05:30] The running status of Pods are as follows     Pod=zookeeper-instance-zookeeper-0 Status=Running
INFO[2020-09-29T23:57:16+05:30] The running status of Pods are as follows     Status=Running Pod=zookeeper-instance-zookeeper-1
INFO[2020-09-29T23:57:16+05:30] The running status of Pods are as follows     Pod=zookeeper-instance-zookeeper-2 Status=Running
INFO[2020-09-29T23:57:18+05:30] [Status]: Obtain pod name of any one of the zookeeper pods 
INFO[2020-09-29T23:57:18+05:30] [Status]: Obtain the desired replica count of the Kafka statefulset 
INFO[2020-09-29T23:57:21+05:30] [Status]: All Kafka brokers are alive        
INFO[2020-09-29T23:57:21+05:30] [Liveness]: Set the kafka topic name         
INFO[2020-09-29T23:57:21+05:30] [Liveness]: Generate the kafka liveness spec from template 
INFO[2020-09-29T23:57:22+05:30] [Liveness]: Confirm that the kafka liveness pod is running 
INFO[2020-09-29T23:57:22+05:30] [Status]: Checking whether application containers are in running state 
INFO[2020-09-29T23:57:29+05:30] The running status of container are as follows  Status=Running container=kafka-consumer Pod=kafka-liveness
INFO[2020-09-29T23:57:29+05:30] The running status of container are as follows  container=kafka-producer Pod=kafka-liveness Status=Running
INFO[2020-09-29T23:57:31+05:30] [Status]: Checking whether application pods are in running state 
INFO[2020-09-29T23:57:31+05:30] The running status of Pods are as follows     Pod=kafka-liveness Status=Running
INFO[2020-09-29T23:57:33+05:30] [Liveness]: Obtain the leader broker ordinality for the topic (partition) created by kafka-liveness 
INFO[2020-09-29T23:57:38+05:30] [Liveness]: Determine the leader broker pod name 
INFO[2020-09-29T23:57:39+05:30] kafka broker will be selected randomly across the cluster 
INFO[2020-09-29T23:57:39+05:30] [Chaos]:Number of pods targeted: 1           
INFO[2020-09-29T23:57:39+05:30] [Info]: Killing the following pods            PodName=kafka-kafka-1
INFO[2020-09-29T23:57:40+05:30] [Wait]: Wait for the chaos interval 10s      
INFO[2020-09-29T23:57:50+05:30] [Status]: Verification for the recreation of application pod 
INFO[2020-09-29T23:57:50+05:30] [Status]: Checking whether application containers are in running state 
INFO[2020-09-29T23:57:50+05:30] The running status of container are as follows  Status=Running container=k8skafka Pod=kafka-kafka-0
INFO[2020-09-29T23:57:50+05:30] The running status of container are as follows  container=kafka-node-exporter Pod=kafka-kafka-0 Status=Running
INFO[2020-09-29T23:57:52+05:30] The running status of container are as follows  container=k8skafka Pod=kafka-kafka-0 Status=Running
INFO[2020-09-29T23:57:52+05:30] The running status of container are as follows  Pod=kafka-kafka-0 Status=Running container=kafka-node-exporter
INFO[2020-09-29T23:57:54+05:30] The running status of container are as follows  Status=Running container=k8skafka Pod=kafka-kafka-0
INFO[2020-09-29T23:57:54+05:30] The running status of container are as follows  container=kafka-node-exporter Pod=kafka-kafka-0 Status=Running
INFO[2020-09-29T23:57:57+05:30] The running status of container are as follows  Pod=kafka-kafka-0 Status=Running container=k8skafka
INFO[2020-09-29T23:57:57+05:30] The running status of container are as follows  container=kafka-node-exporter Pod=kafka-kafka-0 Status=Running
INFO[2020-09-29T23:57:57+05:30] The running status of container are as follows  container=k8skafka Pod=kafka-kafka-1 Status=Running
INFO[2020-09-29T23:57:57+05:30] The running status of container are as follows  Status=Running container=kafka-node-exporter Pod=kafka-kafka-1
INFO[2020-09-29T23:57:57+05:30] The running status of container are as follows  container=k8skafka Pod=kafka-kafka-2 Status=Running
INFO[2020-09-29T23:57:57+05:30] The running status of container are as follows  Status=Running container=kafka-node-exporter Pod=kafka-kafka-2
INFO[2020-09-29T23:57:59+05:30] [Status]: Checking whether application pods are in running state 
INFO[2020-09-29T23:57:59+05:30] The running status of Pods are as follows     Status=Running Pod=kafka-kafka-0
INFO[2020-09-29T23:57:59+05:30] The running status of Pods are as follows     Pod=kafka-kafka-1 Status=Running
INFO[2020-09-29T23:57:59+05:30] The running status of Pods are as follows     Status=Running Pod=kafka-kafka-2
INFO[2020-09-29T23:58:01+05:30] [Chaos]: Time is up for experiment: kafka-broker-pod-failure 
INFO[2020-09-29T23:58:01+05:30] [Completion]: kafka-broker-pod-failure chaos is done 
INFO[2020-09-29T23:58:01+05:30] [Confirmation]: The application pod has been deleted successfully 
INFO[2020-09-29T23:58:01+05:30] [Status]: Verify that the Kafka cluster is healthy(post-chaos) 
INFO[2020-09-29T23:58:01+05:30] [Status]: Verify that all kafka pods are running 
INFO[2020-09-29T23:58:01+05:30] [Status]: Checking whether application containers are in running state 
INFO[2020-09-29T23:58:01+05:30] The running status of container are as follows  Pod=kafka-kafka-0 Status=Running container=k8skafka
INFO[2020-09-29T23:58:01+05:30] The running status of container are as follows  Status=Running container=kafka-node-exporter Pod=kafka-kafka-0
INFO[2020-09-2 [...]

2020-09-29 18:44 UTC, uditgaurav commented
Choas Result:

```bash
Name:         kafka-broker-pod-failure
Namespace:    default
Labels:       name=kafka-broker-pod-failure
Annotations:  <none>
API Version:  litmuschaos.io/v1alpha1
Kind:         ChaosResult
Metadata:
  Creation Timestamp:  2020-09-29T13:11:39Z
  Generation:          25
  Resource Version:    160732
  Self Link:           /apis/litmuschaos.io/v1alpha1/namespaces/default/chaosresults/kafka-broker-pod-failure
  UID:                 8a17c70f-8f95-4d24-ab2f-c3af8cfafd86
Spec:
  Experiment:  kafka-broker-pod-failure
Status:
  Experimentstatus:
    Fail Step:  N/A
    Phase:      Completed
    Verdict:    Pass
Events:
  Type    Reason   Age    From  Message
  ----    ------   ----   ----  -------
  Normal  Summary  14m          kafka-broker-pod-failure experiment has been Passed
  Normal  Awaited  3m11s        experiment: kafka-broker-pod-failure, Result: Awaited
  Normal  Pass     80s          experiment: kafka-broker-pod-failure, Result: Pass
```

2020-10-01 11:44 UTC, ispeakc0de commented on build/generate_go_binary
> +go build -o build/_output/container-killer ./chaoslib/litmus/container_kill/helper
duplicate?

2020-10-01 11:49 UTC, ispeakc0de commented on experiments/kafka/kafka-broker-pod-failure/kafka-broker-pod-failure.go
> +			kafka.DisplayKafkaBrocker(&experimentsDetails)
typo

2020-10-01 11:58 UTC, ispeakc0de commented on experiments/kafka/kafka-broker-pod-failure/test/test.yml
> +          - name: ANSIBLE_STDOUT_CALLBACK
we can remove this

2020-10-01 11:58 UTC, ispeakc0de commented on experiments/kafka/kafka-broker-pod-failure/test/test.yml
> +            ## default: litmus. Supported values: litmus, powerfulseal
powerfulseal?

2020-10-01 11:59 UTC, ispeakc0de commented on pkg/kafka/display-kafka-broker-info.go
> +func DisplayKafkaBrocker(experimentsDetails *experimentTypes.ExperimentDetails) {
typo

2020-10-01 12:02 UTC, ispeakc0de commented on pkg/kafka/kafka-cluster-health.go
> +		if strings.Contains(kafkaAvailableBrokers, strconv.Itoa(ReplicaCount)) {
Can we check this condition?

2020-10-01 12:04 UTC, ispeakc0de commented on pkg/kafka/kafka-cluster-health.go
> +	return PodList.Items[0].Name, nil
random index?

2020-10-01 12:14 UTC, ispeakc0de commented on pkg/kafka/kafka-liveness-stream.go
> +		klog.Infof(fmt.Sprint(err) + ": " + stderr.String())
log

2020-10-01 12:15 UTC, ispeakc0de commented on pkg/kafka/kafka-liveness-stream.go
> +	cmd := exec.Command("sh", "-c", `kubectl get pods -l `+experimentsDetails.KafkaLabel+` --no-headers -o custom-columns=:metadata.name -n `+experimentsDetails.KafkaNamespace+` | grep '^.*-`+ordinality
we can directly use client-go for this

2020-10-01 12:15 UTC, ispeakc0de commented on pkg/kafka/kafka-liveness-stream.go
> +			Name: "kafka-liveness",
runid

2020-10-01 12:17 UTC, ispeakc0de commented on pkg/kafka/kafka-liveness-stream.go
> +							Value: "" + experimentsDetails.KafkaInstanceName + "",
why are you add blank string as prefix and suffix?

2020-10-01 12:18 UTC, ispeakc0de commented on pkg/kafka/kafka-liveness-stream.go
> +					Resources:       corev1.ResourceRequirements{},
we can remove the unused attributes

2020-10-05 09:58 UTC, ksatchit commented on pkg/kafka/kafka-cluster-health.go
> +}
Lets keep this commented - doesn't seem to be an universal kafka health check

2020-10-05 10:00 UTC, ksatchit commented on pkg/kafka/kafka-liveness-stream.go
> +	if experimentsDetails.KafkaSaslAuth == "" || experimentsDetails.KafkaSaslAuth == "disabled" {
Let us keep the scope restricted to nonAuth.

2020-10-05 10:01 UTC, ksatchit commented
When the pod-delete chaos is iterated, can we ensure we select the latest partition leader each time?

2020-10-10 11:04 UTC, ksatchit commented on experiments/kafka/kafka-broker-pod-failure/experiment/kafka-broker-pod-failure.go
> +			log.Fatalf("Application liveness check failed err: %v", err)
We need to record results here

2020-10-12 09:24 UTC, uditgaurav commented
# Case-1
## Liveness: enabled  Broker Pod Name: empty

```bash
INFO[2020-10-12T14:13:46+05:30] Experiment Name: kafka-broker-pod-failure    
INFO[2020-10-12T14:13:46+05:30] [PreReq]: Getting the ENV for the kafka-broker-pod-failure 
INFO[2020-10-12T14:13:46+05:30] [PreReq]: Updating the chaos result of kafka-broker-pod-failure experiment (SOT) 
INFO[2020-10-12T14:13:49+05:30] The application informations are as follows   Ramp Time=0 Kafka Namespace=default Kafka Label="app=kafka"
INFO[2020-10-12T14:13:49+05:30] [Status]: Verify that the Kafka cluster is healthy(pre-chaos) 
INFO[2020-10-12T14:13:49+05:30] [Status]: Verify that all kafka pods are running 
INFO[2020-10-12T14:13:49+05:30] [Status]: Checking whether application containers are in running state 
INFO[2020-10-12T14:13:50+05:30] The running status of container are as follows  Pod=kafka-kafka-0 Status=Running container=k8skafka
INFO[2020-10-12T14:13:50+05:30] The running status of container are as follows  container=kafka-node-exporter Pod=kafka-kafka-0 Status=Running
INFO[2020-10-12T14:13:50+05:30] The running status of container are as follows  container=k8skafka Pod=kafka-kafka-1 Status=Running
INFO[2020-10-12T14:13:50+05:30] The running status of container are as follows  container=kafka-node-exporter Pod=kafka-kafka-1 Status=Running
INFO[2020-10-12T14:13:50+05:30] The running status of container are as follows  container=k8skafka Pod=kafka-kafka-2 Status=Running
INFO[2020-10-12T14:13:50+05:30] The running status of container are as follows  Status=Running container=kafka-node-exporter Pod=kafka-kafka-2
INFO[2020-10-12T14:13:52+05:30] [Status]: Checking whether application pods are in running state 
INFO[2020-10-12T14:13:52+05:30] The running status of Pods are as follows     Pod=kafka-kafka-0 Status=Running
INFO[2020-10-12T14:13:52+05:30] The running status of Pods are as follows     Pod=kafka-kafka-1 Status=Running
INFO[2020-10-12T14:13:52+05:30] The running status of Pods are as follows     Pod=kafka-kafka-2 Status=Running
INFO[2020-10-12T14:13:54+05:30] [Status]: Verify that all zookeeper pods are running 
INFO[2020-10-12T14:13:54+05:30] [Status]: Checking whether application containers are in running state 
INFO[2020-10-12T14:13:55+05:30] The running status of container are as follows  Pod=zookeeper-instance-zookeeper-0 Status=Running container=kubernetes-zookeeper
INFO[2020-10-12T14:13:55+05:30] The running status of container are as follows  Pod=zookeeper-instance-zookeeper-1 Status=Running container=kubernetes-zookeeper
INFO[2020-10-12T14:13:55+05:30] The running status of container are as follows  Pod=zookeeper-instance-zookeeper-2 Status=Running container=kubernetes-zookeeper
INFO[2020-10-12T14:13:57+05:30] [Status]: Checking whether application pods are in running state 
INFO[2020-10-12T14:13:57+05:30] The running status of Pods are as follows     Status=Running Pod=zookeeper-instance-zookeeper-0
INFO[2020-10-12T14:13:57+05:30] The running status of Pods are as follows     Status=Running Pod=zookeeper-instance-zookeeper-1
INFO[2020-10-12T14:13:57+05:30] The running status of Pods are as follows     Pod=zookeeper-instance-zookeeper-2 Status=Running
INFO[2020-10-12T14:13:59+05:30] [Liveness]: Set the kafka topic name         
INFO[2020-10-12T14:13:59+05:30] [Liveness]: Generate the kafka liveness spec from template 
INFO[2020-10-12T14:14:00+05:30] [Liveness]: Confirm that the kafka liveness pod is running 
INFO[2020-10-12T14:14:00+05:30] [Status]: Checking whether application containers are in running state 
INFO[2020-10-12T14:14:07+05:30] The running status of container are as follows  container=kafka-consumer Pod=kafka-liveness-qhdpgq Status=Running
INFO[2020-10-12T14:14:07+05:30] The running status of container are as follows  container=kafka-producer Pod=kafka-liveness-qhdpgq Status=Running
INFO[2020-10-12T14:14:09+05:30] [Status]: Checking whether application pods are in running state 
INFO[2020-10-12T14:14:10+05:30] The running status of Pods are as follows     Pod=kafka-liveness-qhdpgq Status=Running
INFO[2020-10-12T14:14:12+05:30] [Liveness]: Obtain the leader broker ordinality for the topic (partition) created by kafka-liveness 
INFO[2020-10-12T14:14:16+05:30] [Liveness]: Determine the leader broker pod name 
INFO[2020-10-12T14:14:16+05:30] Kafka Broker is kafka-kafka-2                
INFO[2020-10-12T14:14:17+05:30] [Info]: Killing the following pods            PodName=kafka-kafka-2
INFO[2020-10-12T14:14:17+05:30] [Wait]: Wait for the chaos interval 10s      
INFO[2020-10-12T14:14:27+05:30] [Status]: Verification for the recreation of application pod 
INFO[2020-10-12T14:14:27+05:30] [Status]: Checking whether application containers are in running state 
INFO[2020-10-12T14:14:28+05:30] The running status of container are as follows  Status=Running container=k8skafka Pod=kafka-kafka-0
INFO[2020-10-12T14:14:28+05:30] The running status of container are as follows  Status=Running container=kafka-node-exporter Pod=kafka-kafka-0
INFO[2020-10-12T14:14:28+05:30] The running status of container are as follows  container=k8skafka Pod=kafka-kafka-1 Status=Running
INFO[2020-10-12T14:14:28+05:30] The running status of container are as follows  container=kafka-node-exporter Pod=kafka-kafka-1 Status=Running
INFO[2020-10-12T14:14:30+05:30] The running status of container are as follows  container=k8skafka Pod=kafka-kafka-0 Status=Running
INFO[2020-10-12T14:14:30+05:30] The running status of container are as follows  Status=Running container=kafka-node-exporter Pod=kafka-kafka-0
INFO[2020-10-12T14:14:30+05:30] The running status of container are as follows  container=k8skafka Pod=kafka-kafka-1 Status=Running
INFO[2020-10-12T14:14:30+05:30] The running status of container are as follows  Pod=kafka-kafka-1 Status=Running container=kafka-node-exporter
INFO[2020-10-12T14:14:33+05:30] The running status of container are as follows  container=k8skafka Pod=kafka-kafka-0 Status=Running
INFO[2020-10-12T14:14:33+05:30] The running status of container are as follows  container=kafka-node-exporter Pod=kafka-kafka-0 Status=Running
INFO[2020-10-12T14:14:33+05:30] The running status of container are as follows  container=k8skafka Pod=kafka-kafka-1 Status=Running
INFO[2020-10-12T14:14:33+05:30] The running status of container are as follows  Pod=kafka-kafka-1 Status=Running container=kafka-node-exporter
INFO[2020-10-12T14:14:35+05:30] The running status of container are as follows  Status=Running container=k8skafka Pod=kafka-kafka-0
INFO[2020-10-12T14:14:35+05:30] The running status of container are as follows  container=kafka-node-exporter Pod=kafka-kafka-0 Status=Running
INFO[2020-10-12T14:14:35+05:30] The running status of container are as follows  container=k8skafka Pod=kafka-kafka-1 Status=Running
INFO[2020-10-12T14:14:35+05:30] The running status of container are as follows  container=kafka-node-exporter Pod=kafka-kafka-1 Status=Running
INFO[2020-10-12T14:14:37+05:30] The running status of container are as follows  Pod=kafka-kafka-0 Status=Running container=k8skafka
INFO[2020-10-12T14:14:37+05:30] The running status of container are as follows  Status=Running container=kafka-node-exporter Pod=kafka-kafka-0
INFO[2020-10-12T14:14:37+05:30] The running status of container are as follows  Pod=kafka-kafka-1 Status=Running container=k8skafka
INFO[2020-10-12T14:14:37+05:30] The running status of container are as follows  container=kafka-node-exporter Pod=kafka-kafka-1 Status=Running
INFO[2020-10-12T14:14:40+05:30] The running status of container are as follows  container=k8skafka Pod=kafka-kafka-0 Status=Running
INFO[2020-10-12T14:14:40+05:30] The running status of container are as follows  container=kafka-node-exporter Pod=kafka-kafka-0 Status=Running
INFO[2020-10-12T14:14:40+05:30] The running status of container are as follows  container=k8skafka Pod=kafka-kafka-1 Status=Running
INFO[2020-10-12T14:14:40+05:30] The running status of container are as follows  Pod=kafka-kafka-1 Status=Running container [...]

2020-10-12 16:42 UTC, ispeakc0de requested changes

2020-10-12 16:42 UTC, ispeakc0de commented on bin/go-runner.go
> +	// // Uncomment to load all auth plugins
Can we remove one pair of slash?

2020-10-12 16:42 UTC, ispeakc0de commented on chaoslib/litmus/kafka-broker-pod-failure/lib/pod-delete.go
> +			if experimentsDetails.Force == true {
Can we add support for sequence as well?

2020-10-12 16:42 UTC, ispeakc0de commented on pkg/kafka/kafka-cluster-health.go
> +	/*
Can we remove this commented code?

2020-10-12 16:42 UTC, ispeakc0de commented on experiments/kafka/kafka-broker-pod-failure/experiment/kafka-broker-pod-failure.go
> +				log.Fatalf("Liveness check failed err: %v", err)
please change Fatel to Error at every place

2020-10-12 16:42 UTC, ispeakc0de commented on pkg/kafka/kafka-cluster-health.go
> +		return 0, errors.Errorf("Unable to get the pods err: %v", err)
Can we use Unable to find the error message at every place? unable to get looks like permission issue

2020-10-12 16:42 UTC, ispeakc0de commented on pkg/kafka/kafka-launch-stream-derive-leader-broker.go
> +	} else if experimentsDetails.KafkaLivenessStream != "enabled" {
do we need if-else here? or we can direct return `"",nil`?

2020-10-12 16:42 UTC, ispeakc0de commented on experiments/kafka/kafka-broker-pod-failure/experiment/kafka-broker-pod-failure.go
> +	if experimentsDetails.KafkaBroker == "" {
Do we need a separate if here or it can be else part of `if experimentsDetails.KafkaBroker != "" {`

2020-10-12 16:42 UTC, ispeakc0de commented on pkg/kafka/kafka-liveness-cleanup.go
> +// LivenessCleanup will generate kafka liveness deployment on the basic of given condition
can we revisit the comment for each function and change them?

2020-10-12 16:42 UTC, ispeakc0de commented on pkg/kafka/kafka-liveness-stream.go
> +	if len(podList.Items) == 0 {
Can we add a check for err!=nil as well?

2020-10-12 16:42 UTC, ispeakc0de commented on pkg/kafka/kafka-liveness-stream.go
> +					Resources:       corev1.ResourceRequirements{},
we can remove resources

2020-10-12 17:38 UTC, uditgaurav commented on experiments/kafka/kafka-broker-pod-failure/experiment/kafka-broker-pod-failure.go
> +	if experimentsDetails.KafkaBroker == "" {
Either way is fine But the conditions look good in this way don't want to make a bunch of if-else. Added a comment over it.

2020-10-12 17:39 UTC, uditgaurav commented on pkg/kafka/kafka-cluster-health.go
> +	/*
It for those who want to use it.

2020-10-12 17:40 UTC, ispeakc0de commented on experiments/kafka/kafka-broker-pod-failure/experiment/kafka-broker-pod-failure.go
> +	if experimentsDetails.KafkaBroker == "" {
Yeah. I thought It will save one clock cycle of the processor :P

2020-10-12 17:44 UTC, ispeakc0de commented on pkg/kafka/kafka-cluster-health.go
> +	/*
You mean If someone wants to use it. He has to uncomment it, build the custom image, and use it? Can we make it simple for them by tuning this via env?

2020-10-12 18:18 UTC, uditgaurav commented on chaoslib/litmus/kafka-broker-pod-failure/lib/pod-delete.go
> +			if experimentsDetails.Force == true {
Added

2020-10-12 18:19 UTC, uditgaurav commented on pkg/kafka/kafka-cluster-health.go
> +	/*
IDK if it is that much important to be used from ENV. cc @ksatchit

2020-10-13 05:29 UTC, ispeakc0de commented on experiments/kafka/kafka-broker-pod-failure/experiment/kafka-broker-pod-failure.go
> +				log.Errorf("Error: %v", err)
please add result patch as well
```yaml
failStep := "Including the litmus lib for kafka-broker-pod-failure"
types.SetResultAfterCompletion(&resultDetails, "Fail", "Completed", failStep)
result.ChaosResult(&chaosDetails, clients, &resultDetails, "EOT")
```

2020-10-13 05:32 UTC, ispeakc0de commented on experiments/kafka/kafka-broker-pod-failure/experiment/kafka-broker-pod-failure.go
> +			log.Errorf("Error in liveness cleanup err: %v", err)
same as above

2020-10-13 08:30 UTC, ispeakc0de approved these changes

2020-10-13 09:01 UTC, ksatchit approved these changes

2020-10-13 09:01 UTC, merged